### ISSUE TITLE
Can't collapse/open a read-only composite property

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#1]
If you have marked a composite property as read-only it is not possible to change the  collapse/open the widget in runtime. 

The > is not clickable
![image](https://user-images.githubusercontent.com/534670/32003178-a3327802-b99e-11e7-984d-298347c05ed0.png)

**Comment by JochenJankowai** [comment]
Should it be?

**Comment by r-englund** [comment]
IMO, yes.

**Comment by petersteneteg** [comment]
that will probably be very hard to implement, considering how qt works with enable/disable

**Comment by martinfalk** [comment]
I am with Rickard. Sometimes you want to have a composite as control. And setting all subproperties to read-only is a bit cumbersome compared to `CompositeProperty::setReadOnly`

why not overloading `CompositeProperty::setReadOnly` to set only subproperties to read-only? Of course, we might loose some subproperty state there, i.e. if one is already read-only...

**Comment by petersteneteg** [comment]
That is not the problem, the issue is when you set the parent of the composite as readonly then the parent will be disabled by qt and all the cildren, you don't get a setReadonly call to the composite, it only gets disabled, and I've not figured out how one can configure the dissabled states in qt

**Comment by petersteneteg** [comment]
If you figure out how that all good with me

**Comment by martinfalk** [comment]
maybe one could hijack `QWidget::changeEvent` [Qt docs](http://doc.qt.io/qt-5/qwidget.html#changeEvent)

**Comment by petersteneteg** [comment]
Maybe, but when disabled you will not get any more mouse events etc... 
we might have to disable composites in some other way, might be possible

**Comment by martinfalk** [comment]
Composites are weird.

**Comment by petersteneteg** [comment]
we have a related issue about the TF also...

**Comment by martinfalk** [comment]
see http://doc.qt.io/qt-5/qwidget.html#enabled-prop
in particular
> It it not possible to explicitly enable a child widget which is not a window while its parent widget remains disabled.

**Comment by petersteneteg** [comment]
I.e. we can't disable composites, only plain properties, which means we have to take care of propagating the readonly to the children our self...

**Comment by petersteneteg** [comment]
and make composites "fake" disabled then...

**Comment by petersteneteg** [comment]
not that they contain much that needs to be disabled anyway

**Comment by martinfalk** [comment]
https://stackoverflow.com/questions/8467527/qt-4-4-disabled-widgets-receiving-mouse-events

```c++
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
    if (ui->pushButton)
    {
        if (event->type() == QEvent::MouseButtonRelease)
        {
            qDebug() << "mouse button";
            return true;
        } else
        {
            return false;
        }
    } else
    {
        // pass the event on to the parent class
        return QMainWindow::eventFilter(obj, event);
    }
}
```
> This will work even if the button is disabled.

**Comment by martinfalk** [comment]
The question would be if an eventfilter within the composite property will be active even though the widget is disabled.

**Comment by petersteneteg** [comment]
@martinfalk I don't think that solution will scale very well...

**Comment by petersteneteg** [comment]
Think I have fix it... but have you noticed that our sliders work even when read only!

**Comment by petersteneteg** [comment]
Seems we already used martins trick above....

**Comment by petersteneteg** [comment]
Fixed
