### ISSUE TITLE
Module paths in About dialog

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#101]
Would it be possible to include "one more" folder in the about dialog? 
For example, the second modules in this screenshot is (i think) research-dev
![image](https://user-images.githubusercontent.com/534670/39618889-f84c4d5e-4f85-11e8-9d89-54143b910260.png)

**Comment by petersteneteg** [comment]
So right not the number of folders are not a constant, we select a subset of the paths that still be unique...

Though a bit about it, we should probably add some more information here.
We should
    1) check if it is a git repo or a local folder
    2) if git find the local branch name
    3) check if it is tracked and get the tracked remote and branch name 'git status -sb'
    4) if it is tracked we should get the url for that remote 'git config --get remote.<remote>.url'

this would allow us to write github.com/inviwo/inviwo.git:master which would be nice

should probably also specify the repo of each module in some way...

**Comment by ResearchDaniel** [comment]
Unfortunately, I don't think that we will prioritize this feature.
