### ISSUE TITLE
Documentation for ivw.data.MeshInport

### ISSUE THREAD

**Issue by Git-me-outta-here** [inviwo/inviwo#1013]
Please point me to the documentation of _ivw.data.MeshInport_.

I'm writing some inviwopy code where I want to access the mesh coordinates. With getData() I get a _ivw.data.Mesh_, which has a Buffer of type _ivw.data.BufferVec3FLOAT32_. How can I read this buffer?

**Comment by petersteneteg** [comment]
Hi

I think the `ivw.data.BufferVec3FLOAT32` should have a `data` property which hold the data it self. I will be exposed as a numpy array in python 
https://github.com/inviwo/inviwo/blob/82ffa68fea09ff16ae08a72c1a73a6cac8019a94/modules/python3/bindings/src/pybuffer.cpp#L133-L147

We are working on getting the python docs up on the webpage, but Im not sure of the progress @xeTaiz might know more.
In the mean type the poor mans solution can be to just write `help(some python var)` then python will print the pydoc for that class of that variable.

**Comment by Git-me-outta-here** [comment]
Thank you for the tip, the help() function is very nice!

I'm glad to hear you're working on the documentation :)
