### ISSUE TITLE
Problems with installation of Inviwo, home computer Windows 10.

### ISSUE THREAD

**Issue by A-R-A-C-T** [inviwo/inviwo#1024]
Thank you for reporting your issue, please ensure the following before submitting a new issue:
* Is your issue new? Please search the issue system to see if someone else have reported the same issue
* Have more than one issue/bug to report? Create one separate issue for each issue/bug.

Please fill out all applicable fields bellow:

**Issue**

Error in `helpwidget.cpp` line 171. "Cannot open collection file: C:\Users\Anton C. T�rnholm\AppData\Roaming/Inviwo/inviwo.qhc".
I've been following a lab paper trying to install Inviwo on my personal windows computer however upon starting I run into errors. Notice that my username is `Anton C. Tärnholm` with an `ä `which might have something to do with it. The update posted earlier today 2020-09-08 did not resolve the issue, despite redoing everything from the start.
Also there is nothing in the said above path, the appdata looks like: 
![image](https://user-images.githubusercontent.com/33392750/92497516-bbe94880-f1f9-11ea-964d-7637ccec364d.png)

The code that throws the error is the following: 
```C++
    if (!helpEngine_->setupData()) {
        const std::string error = utilqt::fromQString(helpEngine_->error());
        delete helpEngine_;
        throw Exception("Failed to setup the help engine:" + error, IVW_CONTEXT);
    }
```

**Steps to reproduce**

I'll just go ahead and attach the lab-paper in which I have followed. 
Starting on step 3.2. I have clean installations of Visual Studio, Qt, Cmake, Git. Paths are set up correctly.
[LabScript_Lab0.pdf](https://github.com/inviwo/inviwo/files/5189207/LabScript_Lab0.pdf)

My file structure can be seen bellow:
![image](https://user-images.githubusercontent.com/33392750/92495344-16cd7080-f1f7-11ea-8c18-fbf4b0d596ac.png)

The inviwo folder contains the source [files as cloned from gitHub ](https://github.com/inviwo/inviwo), the build contains the build from CMake/Visual Studio and the TNM067 contains external modules.

Running CMake and going through the steps I run into some dev-warnings but also some oddities adding the external modules. The external modules are added as: 
![image](https://user-images.githubusercontent.com/33392750/92495766-9bb88a00-f1f7-11ea-9a67-d086fbbb4a7c.png)

They show up in CMake and I can check their boxes, when configuring again I receive the following log: 
![image](https://user-images.githubusercontent.com/33392750/92495919-c60a4780-f1f7-11ea-9bce-3aa32f0d7b46.png)
![image](https://user-images.githubusercontent.com/33392750/92495970-d3bfcd00-f1f7-11ea-8544-b4048906c918.png)

I think that the "contired" message at the end might indicate that something is wrong?

Moving on to start Visual Studio 16 2019 (x64) I set the solution configuration to `RelWithDbgInfo` instead of `Debug`, I build it and all goes well. Then when starting the program (Debug->Start Debugging / F5) I get the error described at the top.
![image](https://user-images.githubusercontent.com/33392750/92496587-9c055500-f1f8-11ea-9f51-1358e556ff3b.png)

I'm afraid I don't really know how to provide you with any log files, despite your instructions to do so. I'm sorry.
I was also uncertain of what title to use and if I should have added any labels, I apologize for the inconvenience. Let me know and I'll change it to something more appropriate.

**Environment information**
* Operating System: Microsoft Windows 10 Education
* Compiler/IDE: Microsoft Visual Studio Community 2019, Version 16.7.2 (x64)
* QT Version: 5.15.0 -> msvc2019_64
* Python version:  N/A

If possible, copy/paste the Inviwo log into the issue. If Inviwo is crashing before it is possible to attach a log you can start Inviwo with the -c flag to log to console or -l filename.html to log to a file.

**Comment by petersteneteg** [comment]
I have an other idea about what the issue might be, will investigate tomorrow

**Comment by petersteneteg** [comment]
@Auyo-S I just merge #1025 which I hope should fix this issue. I you have the possibility it would be great if you could try out the latest master and see how it goes.

**Comment by A-R-A-C-T** [comment]
> @Auyo-S I just merge #1025 which I hope should fix this issue. I you have the possibility it would be great if you could try out the latest master and see how it goes.

I'll give it a try and get back to you. Thank you!

**Comment by A-R-A-C-T** [comment]
@petersteneteg Hi again Peter, I have now tried your solution and it **works perfectly!** Thank you ever so much! I'll go ahead and close the issue. Take care!
