### ISSUE TITLE
inja Visual Studio compile errors

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#1045]
**Issue**
Get errors when compiling meta:

> inja.hpp(91,30): error C2065: 'not': undeclared identifier

**Environment information**
* Operating System: Windows
* Compiler/IDE: Microsoft Visual Studio Community 2019 Version 16.7.5

27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(91,34): error C2146: syntax error: missing ';' before identifier 'empty'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(91,39): warning C4834: discarding return value of function with 'nodiscard' attribute
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(123,49): error C2146: syntax error: missing ';' before identifier 'and'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(123,49): error C2065: 'and': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(123,53): error C2146: syntax error: missing ';' before identifier 'close_match'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(192,68): error C2146: syntax error: missing ')' before identifier 'and'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(192,68): error C2065: 'and': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(192,72): error C2146: syntax error: missing ';' before identifier 'level'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(192,82): error C2059: syntax error: ')'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(192,86): error C2059: syntax error: 'break'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(193,24): error C2065: 'inner': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(193,40): error C2065: 'inner': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(193,12): error C2672: 'std::regex_match': no matching overloaded function found
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(193,6): error C2780: 'bool std::regex_match(const std::basic_string<_Elem,_StTraits,_StAlloc> &&,std::match_results<basic_string<_Elem,_StTraits,_StAlloc>::const_iterator,_Alloc> &,const std::basic_regex<_Elem,_RxTraits> &,std::regex_constants::match_flag_type)': expects 4 arguments - 2 provided
27>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\regex(2182): message : see declaration of 'std::regex_match'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(193,6): error C2780: 'bool std::regex_match(const std::basic_string<_Elem,_StTraits,_StAlloc> &,std::match_results<basic_string<_Elem,_StTraits,_StAlloc>::const_iterator,_Alloc> &,const std::basic_regex<_Elem,_RxTraits> &,std::regex_constants::match_flag_type)': expects 4 arguments - 2 provided
27>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\regex(2174): message : see declaration of 'std::regex_match'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(193,6): error C2780: 'bool std::regex_match(const _Elem *,std::match_results<const _Elem*,_Alloc> &,const std::basic_regex<_Elem,_RxTraits> &,std::regex_constants::match_flag_type)': expects 4 arguments - 2 provided
27>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\regex(2166): message : see declaration of 'std::regex_match'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(193,6): error C2780: 'bool std::regex_match(_BidIt,_BidIt,const std::basic_regex<_Elem,_RxTraits> &,std::regex_constants::match_flag_type)': expects 4 arguments - 2 provided
27>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\regex(2147): message : see declaration of 'std::regex_match'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(193,6): error C2780: 'bool std::regex_match(_BidIt,_BidIt,std::match_results<_BidIt,_Alloc> &,const std::basic_regex<_Elem,_RxTraits> &,std::regex_constants::match_flag_type)': expects 5 arguments - 2 provided
27>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\regex(2139): message : see declaration of 'std::regex_match'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(194,29): error C2065: 'inner': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(194,45): error C2065: 'inner': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(194,17): error C2672: 'std::regex_match': no matching overloaded function found
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(194,11): error C2780: 'bool std::regex_match(const std::basic_string<_Elem,_StTraits,_StAlloc> &&,std::match_results<basic_string<_Elem,_StTraits,_StAlloc>::const_iterator,_Alloc> &,const std::basic_regex<_Elem,_RxTraits> &,std::regex_constants::match_flag_type)': expects 4 arguments - 2 provided
27>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\regex(2182): message : see declaration of 'std::regex_match'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(194,11): error C2780: 'bool std::regex_match(const std::basic_string<_Elem,_StTraits,_StAlloc> &,std::match_results<basic_string<_Elem,_StTraits,_StAlloc>::const_iterator,_Alloc> &,const std::basic_regex<_Elem,_RxTraits> &,std::regex_constants::match_flag_type)': expects 4 arguments - 2 provided
27>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\regex(2174): message : see declaration of 'std::regex_match'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(194,11): error C2780: 'bool std::regex_match(const _Elem *,std::match_results<const _Elem*,_Alloc> &,const std::basic_regex<_Elem,_RxTraits> &,std::regex_constants::match_flag_type)': expects 4 arguments - 2 provided
27>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\regex(2166): message : see declaration of 'std::regex_match'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(194,11): error C2780: 'bool std::regex_match(_BidIt,_BidIt,const std::basic_regex<_Elem,_RxTraits> &,std::regex_constants::match_flag_type)': expects 4 arguments - 2 provided
27>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\regex(2147): message : see declaration of 'std::regex_match'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(194,11): error C2780: 'bool std::regex_match(_BidIt,_BidIt,std::match_results<_BidIt,_Alloc> &,const std::basic_regex<_Elem,_RxTraits> &,std::regex_constants::match_flag_type)': expects 5 arguments - 2 provided
27>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\regex(2139): message : see declaration of 'std::regex_match'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(200,2): error C2059: syntax error: 'return'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(203,33): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(203,20): error C2146: syntax error: missing ';' before identifier 'search_closed'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(203,71): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(203,71): error C2143: syntax error: missing ',' before '&'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(203,160): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(204,39): error C2065: 'regex_statement': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(204,56): error C2065: 'regex_open': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(204,68): error C2065: 'regex_close': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(204,81): error C2065: 'regex_close': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(204,94): error C2065: 'open_match': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(204,9): error C3861: 'search_closed_on_level': identifier not found
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(208,17): error C2988: unrecognizable template declaration/definition
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(208,17): error C2143: syntax error: missing ';' before '<'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(208,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(208,17): error C2059: syntax error: '<'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(208,68): error C2065: 'T': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(208,71): error C2065: 'Regex': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(208,78): error C2065: 'S': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(208,64): error C2923: 'std::map': 'T' is not a valid template type argument for parameter '_Kty'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(208,64): error C2923: 'std::map': 'Regex' is not a valid template type argument for parameter '_Ty'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(208,64): error C2923: 'std::map': 'S' is not a valid template type argument for parameter '_Pr'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(208,64): error C2976: 'std::map': too few template arguments
27>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\map(75): message : see declaration of 'std::map'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(208,91): error C2143: syntax error: missing ';' before '{'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(208,91): error C2447: '{': missing function header (old-style formal list?)
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(1039,63): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(1039,63): error C2988: unrecognizable template declaration/definition
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(1039,63): error C2143: syntax error: missing ',' before '&'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(1040,20): error C2641: cannot deduce template arguments for 'Environment'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(1040,20): error C2027: use of undefined type 'Environment'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(929): message : see declaration of 'Environment'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(1040,37): error C2065: 'data': undeclared identifier
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(1043,1): error C2988: unrecognizable template declaration/definition
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(1043,1): error C2059: syntax error: '}'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\ext\inja\src\inja.hpp(1043,1): error C2143: syntax error: missing ';' before '}'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\src\creator.cpp(51,24): error C2143: syntax error: missing ';' before '{'
27>C:\Users\danjo\Documents\inviwo\dev\tools\meta\src\creator.cpp(51,24): error C2447: '{': missing function header (old-style formal list?)
27>Done building project "inviwo-meta.vcxproj" -- FAILED.

**Comment by petersteneteg** [comment]
@martinfalk can you push your workaround?
