### ISSUE TITLE
Parallel Coordinates Plot never forgets about its axes

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#1050]
It appears that a Parallel Coordinate Plot remembers its axes forever. That is when plotting various dataframes, the column properties of the previous ones are still persistent.
To reproduce:
1. CSV source "iris.csv"
2. add a pcp visualizer
3. adjust one of the columns
4. delete the csv source
5. recreate csv source "iris.csv" and reconnect it.

The range selection is persistent even if you show another dataframe in between. That is the processor caches & serializes all axes it has ever seen.

**Comment by r-englund** [comment]
This is a feature, not a bug ;)

**Comment by martinfalk** [comment]
It's not documented ;-) And quite surprising.

**Comment by petersteneteg** [comment]
it should not do that.
