### ISSUE TITLE
error: ‘memcpy’ is not a member of ‘std’

### ISSUE THREAD

**Issue by phermosilla** [inviwo/inviwo#1091]
Hello,
First, thank you for your work. I am writing because I encountered an error during compilation on ubuntu 16.04 with g++ 9.3. When compiling the file _src/core/util/safecstr.cpp_ I obtained the error: _‘memcpy’ is not a member of ‘std’_.
I was able to fix it by adding the line _#include <cstring>_ to the file _include/inviwo/core/util/safecstr.h_. Is there another option to solve this problem? 
Best,
Pedro

**Comment by petersteneteg** [comment]
Hi, thanks for reporting!
I probably missed that include. Will push a fix.

**Comment by petersteneteg** [comment]
Should be fixed now
