### ISSUE TITLE
Assertion fail on startup

### ISSUE THREAD

**Issue by PetiteViking** [inviwo/inviwo#112]
I pulled master on inviwo and research today and get the following assertion failure on startup now:

![image](https://user-images.githubusercontent.com/2997626/39926248-e2811b72-552e-11e8-9c02-82e8c8576ff7.png)

On retry, the exception is thrown here:

![image](https://user-images.githubusercontent.com/2997626/39926305-16be35e6-552f-11e8-9c97-c9f85e4034bf.png)

Last inviwo call:

![image](https://user-images.githubusercontent.com/2997626/39926357-420ef85c-552f-11e8-8808-38be89d8e090.png)

Call stack:

![image](https://user-images.githubusercontent.com/2997626/39926410-6ef053d4-552f-11e8-9204-77f376b0b847.png)

After commenting out line 326 in inviwoapplicationqt.cpp, I can start Inviwo.

**Comment by JochenJankowai** [comment]
Addition: After commenting out the line, Inviwo starts but throws the same assertion failure when interacting with the network.

**Comment by r-englund** [comment]
Stacktrace of the new crash?

**Comment by petersteneteg** [comment]
Might be intressting to log what localeName it is trying to set

**Comment by r-englund** [comment]
> Might be intressting to log what localeName it is trying to set

It looked normal, I don't remember which is was, but something like en-GB

**Comment by r-englund** [comment]
Also, it did not disappear after a rebuild

**Comment by petersteneteg** [comment]
Any news on this?

**Comment by JochenJankowai** [comment]
I pulled latest, uncommented the line and it appears to be working now.
