### ISSUE TITLE
Issue with GLUI IntMinMax property not linking properly with other processors

### ISSUE THREAD

**Issue by Ram-is-me** [inviwo/inviwo#1134]
**Issue**

When using the GLUI processor, adding the IntMinMax property, and linking it with other properties, say the clipping values of a cube proxy geometry processor, the values in the GLUI property don't reflect on the actual properties of the processor. However, the property settings I set for the GLUI property get reflected on the actual property (such as redefining min/max values), but the actual minimum and maximum set, either on the canvas or through the properties tab on the GLUI properties window don't reflect on the actual property in the targeted processor.

**Steps to reproduce**

Step 1: Open up an example such as image_stack_volume.inv example. 
Step 2: Create a new GLUI Processor and create a new IntMinMax property.
Step 3: Link the property to the Clip X slices property of the cube proxy geometry processor. 
Step 4: Try to change the values through the slider available on the canvas and observe no changes.  

**Environment information**
* Operating System: Windows
* Compiler/IDE: Visual Studio 2019
* QT Version: 5.13
* Python version: 3.6

If possible, copy/paste the Inviwo log into the issue. If Inviwo is crashing before it is possible to attach a log you can start Inviwo with the -c flag to log to console or -l filename.html to log to a file.

**Comment by martinfalk** [comment]
Hi @Ram-is-me,

did you enable the clipping in the `Cube Proxy Geometry` processor? This one is disabled by default.
When following your steps I could not reproduce the issue.

![image](https://user-images.githubusercontent.com/9251300/111980459-a0df8580-8b06-11eb-9f30-8e6657b9243a.png)

**Comment by Ram-is-me** [comment]
Yes, I tried it on my side and this example seems to be working. But this doesn't seem to work on the Boron example from Example Workspaces. Am I doing something wrong here? 

![UIerror2](https://user-images.githubusercontent.com/31698996/112001544-136f5600-8b45-11eb-9ccd-078c17bd3e1d.PNG)

**Comment by martinfalk** [comment]
Still not able to reproduce the behavior even with the boron workspace.

However, I noted that it is important to create the link in the Link Editor by dragging the connection from Cube Proxy Geometry to the UI processor. This ensures that the bounds are properly set. Otherwise the GLUI ranges (default: [-100,100]) will override the one in Cube Proxy Geometry.

**Comment by martinfalk** [comment]
Which version of Inviwo are you using? Are you on the latest master or you compiling an earlier release?

**Comment by Ram-is-me** [comment]
I've just been using the 0.9.11 release for Windows. I guess I'll try building it from the source code now and see if I can reproduce it after that.

**Comment by Ram-is-me** [comment]
I managed to build it from the source code directly and the issue isn't there. I guess it was an issue on my side. Thanks for the support!

**Comment by martinfalk** [comment]
glad to hear it solved itself.
