### ISSUE TITLE
DataFrame min/max property

### ISSUE THREAD

**Issue by sigsid** [inviwo/inviwo#1138]
Issue:
For a property in a dataframe used in the parallel coordinates processor, when you "force" the min/max range for the axis (by selecting property settings for axis range) this will unfortunately be reset each time you update the data. It would be nice if there was some way you could "save" this setting so you wouldn't have to adjust the range each time the data is updated...

Suggestion:
The dataframe column could have a min/max values per (ordinal) column (maybe stored as MetaData), which then can be used for the parallel coordinates processor when setting min/max range of the axis.

**Comment by martinfalk** [comment]
The idea is to provide some additional min/max values instead of computing those from the column. Similar to DataRange/ValueRange in volumes.

**Comment by martinfalk** [comment]
Column ranges based on the data as well as overrides have been added in PR #1216,  81b71563a4bf52ea12c968375504d25a82fcb3d9
