### ISSUE TITLE
Image Layout + Port Inspector causes incomplete FBO

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#1153]
The `Image Layout` processor in combination with the port inspector causes OpenGL errors like incomplete FBO attachments on unused image inputs. This also subsequently breaks the currently shown layout.

**Cause:** `Image Layout` creates resize events with size `(0, 0)` for unused inputs. Zero-size Images are not handled well in Inviwo.

**Scenario:**
1. create three background processors
2. connect them to a `Image Layout` with a canvas
3. change the layout to horizontal Split
4. hover the connection of the third, unused image 

This will cause an incomplete FBO attachment in the inspector due to an image size of `(0, 0)` and a re-evaluation of the network breaking the layout processor.

**Comment by petersteneteg** [comment]
What should happen with an image outport if the size 0? Should the processor be processed? What if there are multiple outports?

**Comment by martinfalk** [comment]
Valid questions. The `Image Layout` processor specifically sets the size to zero in order to ignore it later on. This might be considered a work-around since there is no support for _invalid_ image data on a port.
