### ISSUE TITLE
How does #include“***” in the shader tie the code together?

### ISSUE THREAD

**Issue by PengCheng-git** [inviwo/inviwo#1165]
Thank you for reporting your issue, please ensure the following before submitting a new issue:
* Is your issue new? Please search the issue system to see if someone else have reported the same issue
* Have more than one issue/bug to report? Create one separate issue for each issue/bug.

Please fill out all applicable fields bellow:

**Issue**

Describe the issue

**Steps to reproduce**

Please make a step to step guide on how to reproduce the issue

**Environment information**
* Operating System:
* Compiler/IDE:
* QT Version:
* Python version: 

If possible, copy/paste the Inviwo log into the issue. If Inviwo is crashing before it is possible to attach a log you can start Inviwo with the -c flag to log to console or -l filename.html to log to a file.

**Comment by ResearchDaniel** [comment]
All folders belonging to files added to the ShaderManager are searched. To add shaders in your own module you can add this in the module constructor (see for example the baseglmodule.cpp):
yourmodule::addShaderResources(ShaderManager::getPtr(), {getPath(ModulePath::GLSL)});

(replace yourmodule with the name of your module)

**Comment by ResearchDaniel** [comment]
Please re-open issue in case the answer was not sufficient.
