### ISSUE TITLE
Additional Property Information

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#117]
At the moment our properties provide very little information about their purpose. The only source for more detailed information is the processor entry shown in the help widget (if the processor is documented).

Sometimes, properties are not entirely self-describing. E.g. the use of wildcards in the file pattern property (`data/img_*_###.jpeg`) or the format string of the axis tick labels (`%.3f`). More details could be quite helpful.

At the moment, one solution is to add another `StringProperty` right before or after the property in question to show additional text.
Another option could be extending the existing tooltip with some additional, and short, help. But how and where should the help be defined within a property?

**Comment by martinfalk** [comment]
![image](https://user-images.githubusercontent.com/9251300/40173158-36311d84-59d1-11e8-92f8-4c34de48c4eb.png)

**Comment by r-englund** [comment]
One option could be to have an optional string/document in the property base class (called helpString_ or docString_) and incoperate that one in property::getDescription() ([property.cpp#L272-L290](https://github.com/inviwo/inviwo/blob/master/src/core/properties/property.cpp#L272-L290)) 
Then it would be visisble in the the property tooltip  ([propertywidgetqt.cpp#L397](https://github.com/inviwo/inviwo/blob/master/modules/qtwidgets/properties/propertywidgetqt.cpp#L397)). 

Another option, that would be slightly more visible is to have a question mark icon right next to the property which has a custom tool tip with the help text for that property.

**Comment by martinfalk** [comment]
like the Question mark icon next to the display string of the property

**Comment by petersteneteg** [comment]
Will close this in favour of the broader issue #181
