### ISSUE TITLE
Sponsor logos don't work well with dark mode

### ISSUE THREAD

**Issue by PetiteViking** [inviwo/inviwo#1183]
Hi!
The sponsor logos we have do not work very well in Github's dark mode.

![image](https://user-images.githubusercontent.com/2997626/132681311-ff051a9a-ac57-44a0-9fe7-31ba345efba5.png)

**Comment by petersteneteg** [comment]
Hehe nope :)

**Comment by petersteneteg** [comment]
Wonder what would be the easiest way to fix that?

**Comment by JochenJankowai** [comment]
Open files in paint, save as jpeg ;)

**Comment by petersteneteg** [comment]
https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/56
