### ISSUE TITLE
Precompiled headers with Qt6 break CMake

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#1194]
Tested with CMake 3.21.2 and Qt 6.1.3.

```cmake
CMake Error at cmake/cotire.cmake:2376 (file):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:QT_NO_UNICODE_DEFINES>

  $<TARGET_PROPERTY:prop> may only be used with binary targets.  It may not
  be used with add_custom_command or add_custom_target.  Specify the target
  to read a property from using the $<TARGET_PROPERTY:tgt,prop> signature
  instead.
Call Stack (most recent call first):
  cmake/cotire.cmake:2995 (cotire_generate_target_script)
  cmake/cotire.cmake:3385 (cotire_process_target_language)
  cmake/cotire.cmake:3569 (cotire_target)
  cmake/precompileheaders.cmake:142 (cotire)
  modules/qtwidgets/CMakeLists.txt:209 (ivw_compile_optimize_on_target)
```

see offending target property: https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/Qt6CoreMacros.cmake#n2424

**Comment by mousse183** [comment]
Hello, I would like to report exactly the same bug, but with Cmake 3.23.1, and Qt 6.3.1. Is there an update about the issue ?

Toolchain : Visual Studio
Architecture : amd64
Generator : Ninja

**Comment by petersteneteg** [comment]
@martinfalk, you started working on this at some point? 
You can disable PCH in cmake in the mean time: `IVW_CFG_PRECOMPILED_HEADERS = OFF`
