### ISSUE TITLE
Composite Processor creation upon deserialization issue

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#12]
It seems to be an issue when trying to deserialize a network with with a Composite Processor in it. 
Notice it when trying to load a network with a composite processor and got deserialization errors. 
This also seem to affect copy pasting of Composite Processors. 
**Steps to reproduce**

1.  Load the boron network
2. Select any set of processor and create a composite out of them (I selected the proxy+ entryexit + raycaster) 
3. Copy and paste the create composite processor
Result: 
```
Could not create Processor: "composite" of class "org.inviwo.CompositeProcessor" at line: 1. Reason: "org.inviwo.CompositeProcessor" Not found in factory.
```

**Comment by petersteneteg** [comment]
This is more of a copy paste error....

**Comment by petersteneteg** [comment]
We dont auto register all composites in the factory... hence the error

**Comment by r-englund** [comment]
> This is more of a copy paste error....

It is also an error when opening a saved network.

**Comment by petersteneteg** [comment]
when you save the new composite above?

**Comment by r-englund** [comment]
Saving and than loading a network with a composite processor in it. (That is practically the same as copy paste). 
We get the same behaviour regardless if the Composite Processor in question is "saved for later" or not.

**Comment by r-englund** [comment]
Any idea of how to solve this?

**Comment by petersteneteg** [comment]
yes
