### ISSUE TITLE
Toggleboxes in "View"-dropdown is not updating properly

### ISSUE THREAD

**Issue by RasmusHogslatt** [inviwo/inviwo#1213]
**Issue**
Clicking "View->Animation editor" checks the checkbox next to "Animation editor". When closing the animation editor, the choice is still checked. It should become unchecked when closing the window.

Because of this, the next time a user clicks "View->Animation editor", the box will now become unchecked again, despite the editor window now opening.

NOTICE: This happens for all choices in "View->Arbitrary selection", not just "Animation Editor".

**Steps to reproduce**
1. Click "View->Animation Editor"
2. Close the editor
3. Click "View". Notice the checkbox is still checked.
4. Click "Animation Editor".
5. Click "View". Notice the box is unchecked, but the animation editor is still open.

**Environment information**
* Operating System: Windows 10
* Compiler/IDE: Visual Studio 2019
* QT Version: 6.02
* Python version: 3.10

**Comment by martinfalk** [comment]
Could only reproduce for animation editor and demo navigator.
