### ISSUE TITLE
Misspelling in shaderobject.h file

### ISSUE THREAD

**Issue by grassofsky** [inviwo/inviwo#1222]
**misspellings**

Misspelling in [shaderobject.h file](https://github.com/inviwo/inviwo/blob/8edc7cb6430b12f0be7cdd62eaaa69ce29f1e64b/modules/opengl/include/modules/opengl/shader/shaderobject.h#L71).

` *     out vev4 PickingData; (location 1)`

Here, the `vev4` should be `vec4`

I hope some one can fix it when to commit code.

**Comment by petersteneteg** [comment]
Will fix the typo, just to verify, this only affected the comments not any code?

**Comment by grassofsky** [comment]
> Will fix the typo, just to verify, this only affected the comments not any code?

Thank you for your quick response. After searching around the code base, make sure that only affects the comments, but I found another place, see [shaderobject.h#L218](https://github.com/inviwo/inviwo/blob/8edc7cb6430b12f0be7cdd62eaaa69ce29f1e64b/modules/opengl/include/modules/opengl/shader/shaderobject.h#L218).

**Comment by petersteneteg** [comment]
Fixed now
