### ISSUE TITLE
glm overrides any() and all() in Python

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#1226]
It is not possible to use the basic python functions `all()` and `any()` due to a glm override.

Minimal example in Inviwo's python editor:
```python
import inviwopy  ## can even be commented out ...

if all([None]):
    print("foo")
```
Reported error:
```
TypeError: all(): incompatible function arguments. The following argument types are supported:
    1. (arg0: inviwopy.glm.bvec2) -> bool
    2. (arg0: inviwopy.glm.bvec3) -> bool
    3. (arg0: inviwopy.glm.bvec4) -> bool

Invoked with: [None]
Stacktrace (most recent call first):
foobar.py:4 in <module>
```

**Comment by martinfalk** [comment]
`help(any)` provides the following information
```
Help on built-in function any in module inviwopy.glm:

any(...) method of builtins.PyCapsule instance
    any(*args, **kwargs)
    Overloaded function.
    
    1. any(arg0: inviwopy.glm.bvec2) -> bool
    
    2. any(arg0: inviwopy.glm.bvec3) -> bool
    
    3. any(arg0: inviwopy.glm.bvec4) -> bool
```

**Comment by martinfalk** [comment]
So I am wondering why those functions are globally accessible. This also affects `clamp`, `compMax`, ...

In contrast, `logWarn()` is not accessible, but `inviwopy.logWarn()` is without `import inviwopy`.
 https://github.com/inviwo/inviwo/blob/78a3cfc36ae62c6dd544733c9bc507a384a1ed0e/modules/python3/bindings/src/pyglmtypes.cpp#L211-L226

**Comment by martinfalk** [comment]
After some digging around, I noticed that this is caused by arbitrary python processors that use `from inviwopy.glm import *`.
This indicates some global state pollution between processors and the python environment.

**Comment by petersteneteg** [comment]
Well that global "pollution" is how we register the python processors with the python runtime...

**Comment by petersteneteg** [comment]
@martinfalk is this solved? or are you looking for a more comprehensive solution?

**Comment by martinfalk** [comment]
I tracked down a number of those `import *` occurrences and also reverted to use the `builtins` module to access `builtins.any` and `builtins.all.`

Probably not much we can do about that.
