### ISSUE TITLE
Inviwo crashes at startup

### ISSUE THREAD

**Issue by kaimikael** [inviwo/inviwo#1228]
Thank you for reporting your issue, please ensure the following before submitting a new issue:
* Is your issue new? Please search the issue system to see if someone else have reported the same issue
* Have more than one issue/bug to report? Create one separate issue for each issue/bug.

Please fill out all applicable fields bellow:

**Issue**
Describe the issue
I attempt to start Inviwo, it gets as far as showing the splash screen with the text “Loading capabilities”, then it crashes.

**Steps to reproduce**
I downloaded the installer at https://github.com/inviwo/inviwo/releases/download/v0.9.11/Inviwo-v0.9.11-win.exe, ran it to install and then attempt to start Inviwo.
I can try starting from the taskbar or from the CMD window, it crashes at the same point.

Please make a step to step guide on how to reproduce the issue

**Environment information**
* Operating System: Windows 10 Enterprise, version 21H1, build 19043.1387, running in Parallels Desktop 17.1.0 (51516) under macOS 12.0.1
* Compiler/IDE: N/A
* QT Version: N/A
* Python version: N/A

If possible, copy/paste the Inviwo log into the issue. If Inviwo is crashing before it is possible to attach a log you can start Inviwo with the -c flag to log to console or -l filename.html to log to a file.

Running inviwo.exe -c or inviwo.exe /c gives no output in the console.  inviwo.exe -l log.html does not create any output file.
The information I have comes from the eventviewer:
*Error*
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-12-01T18:56:23.0667763Z" /> 
  <EventRecordID>2786</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>KAI-MIKAELJ371C</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>inviwo-cli.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5d6e09b7</Data> 
  <Data>unknown</Data> 
  <Data>0.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000000000</Data> 
  <Data>1410</Data> 
  <Data>01d7e6e5216f936e</Data> 
  <Data>C:\Program Files\Inviwo\0.9.11\bin\inviwo-cli.exe</Data> 
  <Data>unknown</Data> 
  <Data>986f7277-23b0-48d9-ab2f-14ef75168e78</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

*Information*
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-12-01T18:56:29.3288790Z" /> 
  <EventRecordID>2787</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>KAI-MIKAELJ371C</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>1894779450421650947</Data> 
  <Data>5</Data> 
  <Data>BEX64</Data> 
  <Data>Not available</Data> 
  <Data>0</Data> 
  <Data>inviwo-cli.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5d6e09b7</Data> 
  <Data>StackHash_ac46</Data> 
  <Data>0.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>PCH_19_FROM_ntdll+0x000000000009D8C4</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000000008</Data> 
  <Data /> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4548.tmp.dmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER46B0.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER46D0.tmp.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER46E6.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER46F7.tmp.txt</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_inviwo-cli.exe_ff6035a57213458508ef204ca94c1393b358c_8541abda_4914a9ff-c786-487b-9487-3a6df86bc296</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>986f7277-23b0-48d9-ab2f-14ef75168e78</Data> 
  <Data>268435456</Data> 
  <Data>f259775ca48a33362a4b9bdf0617a603</Data> 
  <Data>0</Data> 
  </EventData>
  </Event>

```

**Comment by petersteneteg** [comment]
Hi, thanks for reporting, I saw that you are running Inviwo under Parallels Desktop, Don't think we have ever tested doing that since Inviwo also runs natively on MacOSX (although you would have to build it your self). I suspect there might be a opengl issues, do you usually run OpenGL applications with Parallels Desktop?

**Comment by kaimikael** [comment]
Yeah, I finally got the macOS build working, just minutes ago :-)  (Still haven’t got the Windows build to behave, seems there is some environment variable that’s not correctly set.)

I’m running all kinds of software under Parallels and generally I don’t have any problems (using USB ports can be tricky, though).

**Comment by petersteneteg** [comment]
Hi
I will close this for now, if there are any updates or if this is still a problem please reopen and let me know!
