### ISSUE TITLE
Evaluating a processor based on subsets of brushing types

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#1237]
With the really nice new brushing and linking features I have come across an issue with processors that only require a subset of the brushing features. For example only filtering. 
Each hover event will invalidate the processor and, while it is possible to check for modifications and skip computations in that processor it will still cause connected processors to evaluate (even though no new data is set on the outport). 

What would be the recommended action to avoid subsequent processing here? 
Is setting a new isReady_ function the way to go? I would assume that it messes with other things.

@martinfalk @petersteneteg

**Comment by petersteneteg** [comment]
This should not have anything to do with isReady, the key here is in overloading Inport::invalidate. But for that to work we probably need to refactor the B&L a bit. I can put this on my todo...

**Comment by ResearchDaniel** [comment]
Adding a BrushingModification invalidation filter to constructor and/or a settter/getter for it should be fairly straightforward perhaps

**Comment by ResearchDaniel** [comment]
Seems to work well. Will make a PR

**Comment by petersteneteg** [comment]
There are some things related to the propagation in the B&L manager that needs to change for it to work properly I think.

**Comment by martinfalk** [comment]
Implemented in #1241
