### ISSUE TITLE
Failures due to missing submodules

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#128]
Checking out a fresh copy require additional steps, calling git submodule --init and update.
Can we detect if some folder is missing, such as ext/gtest/gtest, and execute the command from cmake?

**Comment by r-englund** [comment]
It should be possible to see if that folder is missing. 
If cmake can detect/find git, then we should be able to run that command from cmake. Else we should print an detailed error message. 
Not that the git command can only be executed if we are in a git repo. For example, when the source is  download as a zip-file from GitHub we do not get the submodules, nor is it a git repository.

**Comment by petersteneteg** [comment]
Think it is better the user runs git...
