### ISSUE TITLE
Regression test regression?

### ISSUE THREAD

**Issue by petersteneteg** [inviwo/inviwo#130]
What happened here?

![image](https://user-images.githubusercontent.com/3638222/40531091-9097b938-5ffb-11e8-9bd3-631b3807d745.png)

**Comment by r-englund** [comment]
Which job is that? Tried to find it on jenkins

**Comment by r-englund** [comment]
Ah, you can zoom  
http://jenkins.inviwo.org:8080/userContent/regress/report.html

**Comment by r-englund** [comment]
What are the units on y-axis? Could the tool tip be extended to include number of test that ran? And maybe even list commit hashes?

**Comment by r-englund** [comment]
The log messages around the time are: 

commit 553e0c57cb72bf69c7765edc696f4da76d3c3a86
Author: Peter Steneteg <peter@steneteg.se>
Date:   Sat Dec 9 22:41:11 2017 +0100

Core: bugfix closes inviwo/inviwo-dev#2039

commit edc1eb33bd968026e4fbb032b7fcf329d179fdba
Author: Martin Falk <martin.falk@liu.se>
Date:   Sat Dec 9 23:52:34 2017 +0100

PlottingGL: minor fix



* replaced deprecated TransferFunction calls

commit 027676c8a05d3012322d69fa68518f02191046ae
Merge: 44c9c2a5a a72384fc1
Author: Peter Steneteg <peter@steneteg.se>
Date:   Sat Dec 9 23:38:15 2017 +0100

Merge pull request inviwo/inviwo-dev#2038 from inviwo/feature/dockwidgetstate



Saving InviwoDockWidget state in setting in a consistent way.

commit 44c9c2a5a2be48657ee50e4610f3d287585df74a
Merge: 821e7b862 22ac65e98
Author: Peter Steneteg <peter@steneteg.se>
Date:   Sat Dec 9 23:37:49 2017 +0100

Merge pull request inviwo/inviwo-dev#2037 from inviwo/feature/networkeditor-fix



Networkeditor fixes for scene size etc

commit 821e7b8629223b4bf7656f101608c70c6c8dd3d4
Merge: 1881fe356 149e849eb
Author: Peter Steneteg <peter@steneteg.se>
Date:   Sat Dec 9 23:34:06 2017 +0100

Merge pull request inviwo/inviwo-dev#2040 from inviwo/feature/core-bugfix-2039



bugfix closes inviwo/inviwo-dev#2039

commit 149e849eb2d56710235815cf2649883176ec6d78
Author: Peter Steneteg <peter@steneteg.se>
Date:   Sat Dec 9 22:41:11 2017 +0100

Core: bugfix closes inviwo/inviwo-dev#2039

commit 22ac65e983acf039e8153563d87e2f49d293945a
Author: Peter Steneteg <peter@steneteg.se>
Date:   Sat Dec 9 22:05:21 2017 +0100

Qt: bugfix

commit a72384fc1e5a10a03b51ea142e35c40601027443
Author: Peter Steneteg <peter@steneteg.se>
Date:   Sat Dec 9 13:21:08 2017 +0100

Qt: Saving InviwoDockWidget state in setting in a consistent way.

commit 2a1f4a0b209c8147358656cd02fd97e866442148
Author: Peter Steneteg <peter@steneteg.se>
Date:   Sat Dec 9 20:56:15 2017 +0100

Qt: Networkeditor fixes for scene size

commit 1881fe356b176c6ad2b83ecc4039f3c8cecd0e40
Merge: c425d9ac0 756807819
Author: Martin Falk <martin.falk@liu.se>
Date:   Sat Dec 9 14:14:05 2017 +0100

Merge pull request inviwo/inviwo-dev#2034 from inviwo/fix/boolcomposite



QtWidgets: fixed widget state of BoolCompositeProperty, closes inviwo/inviwo-dev#2003

commit 75680781908f79df5043d678abe39ced7c4dead1
Author: Martin Falk <martin.falk@liu.se>
Date:   Sat Dec 9 12:55:29 2017 +0100

QtWidgets: fixed widget state of BoolCompositeProperty, closes inviwo/inviwo-dev#2003

* the UI state was not properly reflected if the property was unchecked by default

**Comment by petersteneteg** [comment]
the number is supposed to be normalized with respect to the number of test... but In not 100% sure how well that works...

**Comment by petersteneteg** [comment]
I think this is related to calling show on some dockwidgets... will close for now...
