### ISSUE TITLE
Inviwo fails to build on latest version of Visual Studio 2022 (17.3.2)

### ISSUE THREAD

**Issue by josejonasj** [inviwo/inviwo#1327]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://inviwo.org). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/inviwo/inviwo/issues) and [Discussions](https://github.com/inviwo/inviwo/discussionss) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in [Slack](https://join.slack.com/t/inviwo/shared_invite/enQtNTc2Nzc2NDQwNzIxLTRiMWM1ZWJiYjljZjkwNWE3OTk3MzYxODZlMDUyMzRmZjUzMzBiZjVhNTM3NWUyNzU1MjI4OWJjMzdkODViMzM) or in a [Discussion](https://github.com/inviwo/inviwo/discussionss).

### Problem description

Hello, I'm trying to build Inviwo master branch on Visual Studio 2022 version 17.3.1 but I'm getting a lot of errors like the following one:

`D:\inviwo\ext\flags\include\flags/flags.h(88,62): error C2065: 'b': undeclared identifier`

Compiling with an older compiler version solves the issue but I just wanted to let you know about it.

### Inviwo version

3e6679a

### Operating system?

Windows

### Compiler / Version

MSVC 2022 (14.33.31629)

### Qt Version

6.2.2

**Comment by ResearchDaniel** [comment]
Thanks for reporting!
There is hopefully a fix on the way:
https://github.com/inviwo/inviwo/pull/1328

**Comment by petersteneteg** [comment]
the build will still fail in other places... right now your best bet is to use a older version of the compiler and hope that Microsoft will fix this stuff soon. One can installer older versions of the compiler in the VSinstaller and set it either cmake using  https://cmake.org/cmake/help/latest/variable/CMAKE_VS_PLATFORM_TOOLSET_VERSION.html
or by setting VCToolsVersion enviroment variable, the version should be some think like "14.32.<something>" 
details here https://devblogs.microsoft.com/cppblog/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2019/
In the example they only use the major and minor version, but you need the patch version too...

**Comment by petersteneteg** [comment]
here is an example of the compiler regression https://godbolt.org/z/9PPEa476s

**Comment by josejonasj** [comment]
Thanks for the support.
