### ISSUE TITLE
Inviwo fails to build on Windows since the branch inviwo/feature/new-help-system was merged

### ISSUE THREAD

**Issue by josejonasj** [inviwo/inviwo#1330]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://inviwo.org). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/inviwo/inviwo/issues) and [Discussions](https://github.com/inviwo/inviwo/discussionss) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in [Slack](https://join.slack.com/t/inviwo/shared_invite/enQtNTc2Nzc2NDQwNzIxLTRiMWM1ZWJiYjljZjkwNWE3OTk3MzYxODZlMDUyMzRmZjUzMzBiZjVhNTM3NWUyNzU1MjI4OWJjMzdkODViMzM) or in a [Discussion](https://github.com/inviwo/inviwo/discussionss).

### Problem description

Hello, thanks for the most recent commit `bbef904fa` but now new errors showed up to me ([Build Output.txt](https://github.com/inviwo/inviwo/files/9427378/Build.Output.txt)). And those errors were only obtained since commit `30457dcec` because the previous commit `6f5305377` builds just fine.

But if you can build it without any issues, do you have any ideas why this might be happening?

Thanks.

### Inviwo version

`bbef904fa`

### Operating system?

Windows

### Compiler / Version

MSVC 2022 & MSVC2019

### Qt Version

6.2.2

**Comment by martinfalk** [comment]
Thanks for reporting this. Can you please specify the version of Visual Studio and the compiler you are using?
We just merged a fix for the latest Visual Studio 17.3.2.

You can see the full compiler version in the native tools command prompt with `cl /?`.

**Comment by josejonasj** [comment]
Hi @martinfalk , here you go:

Visual Studio 2022 version 17.3.2 (compiler version 19.33.31629)
Visual Studio 2019 version 16.9.5 (compiler version 19.28.29915)

Thanks.

**Comment by josejonasj** [comment]
Regarding the fix for the latest Visual Studio 17.3.2, I already tested it but it didn't work either.

**Comment by martinfalk** [comment]
Will investigate. The same errors appear on one of our machines as well.

**Comment by josejonasj** [comment]
That's great, thank you very much.

**Comment by petersteneteg** [comment]
I did see this error recently on VS2019 but VS2022 did not complain, can you confirm that It also fails on VS2022 for you? 
Seems the issue is about using lambdas as default args for the set and get... I can try and do a workaround...

**Comment by martinfalk** [comment]
@josejonasj have you tried using a fresh, that is empty, build folder and rerun CMake from scratch?

**Comment by josejonasj** [comment]
Yes, I did it a couple of times and got the same result.

**Comment by josejonasj** [comment]
I re-cloned the master branch in another drive and I got the same errors on the latest VS2022. As @petersteneteg said, it seems related to using lambdas as default arguments for set and get methods, like it is used on OrdinalRefProperty class.

**Comment by petersteneteg** [comment]
That is so strange that issue went away on all the other systems we have tested when they updated to the latest msvc version. Would be interesting to know what the difference is. I have a workaround for the lambda function issue in the works, but I've been home with sick kids this week... also not sure if that is the only issue on vs2019

**Comment by RasmusHogslatt** [comment]
I got the exact same issue on my machine (Windows 11, VS2022 Community, msvc143 and clang toolset). Any fix yet?
