### ISSUE TITLE
[BUG]: cefimageconverter.cpp compile error 

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#1355]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://inviwo.org). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/inviwo/inviwo/issues) and [Discussions](https://github.com/inviwo/inviwo/discussionss) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in [Slack](https://join.slack.com/t/inviwo/shared_invite/enQtNTc2Nzc2NDQwNzIxLTRiMWM1ZWJiYjljZjkwNWE3OTk3MzYxODZlMDUyMzRmZjUzMzBiZjVhNTM3NWUyNzU1MjI4OWJjMzdkODViMzM) or in a [Discussion](https://github.com/inviwo/inviwo/discussionss).

### Problem description

Could it be that the latest header include fixes has caused this error:

```
18>C:\Users\danjo\Documents\inviwo\dev\include\inviwo/core/util/introspection.h(91,43): error C2338: static_assert failed: 'ClassIdentifier is missing for type'
18>C:\Users\danjo\Documents\inviwo\dev\include\inviwo/core/datastructures/datatraits.h(82): message : see reference to function template instantiation 'const std::string &inviwo::util::classIdentifier<T>(void)' being compiled
18>        with
18>        [
18>            T=inviwo::Volume
18>        ]
18>C:\Users\danjo\Documents\inviwo\dev\include\inviwo/core/datastructures/datatraits.h(82): message : while compiling class template member function 'const std::string &inviwo::DataTraits<T,void>::classIdentifier(void)'
18>        with
18>        [
18>            T=inviwo::Volume
18>        ]
18>C:\Users\danjo\Documents\inviwo\dev\include\inviwo/core/ports/datainport.h(93): message : see reference to function template instantiation 'const std::string &inviwo::DataTraits<T,void>::classIdentifier(void)' being compiled
18>        with
18>        [
18>            T=inviwo::Volume
18>        ]
18>C:\Users\danjo\Documents\inviwo\dev\include\inviwo/core/ports/datainport.h(122): message : see reference to class template instantiation 'inviwo::DataTraits<T,void>' being compiled
18>        with
18>        [
18>            T=inviwo::Volume
18>        ]
18>C:\Users\danjo\Documents\inviwo\dev\include\inviwo/core/ports/datainport.h(121): message : while compiling class template member function 'inviwo::uvec3 inviwo::DataInport<inviwo::Volume,1,false>::getColorCode(void) const'
18>C:\Users\danjo\Documents\inviwo\dev\modules\webbrowser\src\cefimageconverter.cpp(65): message : see reference to class template instantiation 'inviwo::DataInport<inviwo::Volume,1,false>' being compiled
```

cefimageconverter is not using Volume. The problem is fixed if I include <inviwo/core/datastructures/volume/volume.h>

### Operating system?

Windows

**Comment by petersteneteg** [comment]
I think Martin started to look at this... I will also investigate. seems very strange

**Comment by petersteneteg** [comment]
This line causes a instantiation in MSVC https://github.com/inviwo/inviwo/blob/8dda8889b7dcab4afc69c8cb0c7b94a52c0c5499/modules/opengl/include/modules/opengl/texture/textureutils.h#L199
Clang does not seem to mind It, strange, Not sure if it is an compiler bug or not. But I will remove the forward declares...

**Comment by petersteneteg** [comment]
#1352  should fix this
