### ISSUE TITLE
[BUG]: Dangling pointer in RepresentationFactoryManager upon InviwoApplication destruction

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#1379]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://inviwo.org). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/inviwo/inviwo/issues) and [Discussions](https://github.com/inviwo/inviwo/discussionss) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in [Slack](https://join.slack.com/t/inviwo/shared_invite/enQtNTc2Nzc2NDQwNzIxLTRiMWM1ZWJiYjljZjkwNWE3OTk3MzYxODZlMDUyMzRmZjUzMzBiZjVhNTM3NWUyNzU1MjI4OWJjMzdkODViMzM) or in a [Discussion](https://github.com/inviwo/inviwo/discussionss).

### Problem description

`RepresentationFactoryManager` keeps reference to InviwoApplication's representation factory.
If InviwoApplication is destroyed and initialized again RepresentationFactoryManager::representationMetaFactory_ will point to the destroyed instance. 
 
[RepresentationFactoryManager::getRepresentationFactory() ](https://github.com/inviwo/inviwo/blob/a832ca089466d8bf50c221eed7974cbe10708398/include/inviwo/core/datastructures/representationfactorymanager.h#L186)

One possible solution:
Add functionality to reset the static factories and do this in the InviwoApplication destructor.

Any objections to such a solution or suggestions on another one?

**Comment by petersteneteg** [comment]
Don't think we support destroying and recreating InviwoApplication
