### ISSUE TITLE
Exceptions thrown in dispatchFront disappears 

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#143]
If an exception is thrown inside a dispatchFront callback it silently disappears. 
To reproduce, add `throw inviwo::Exception("test",IvwContext);` to any dispatchFront, for example in the SurfaceExtractionProcessor. 

This is probably related to `std::packaged_task` (see https://stackoverflow.com/a/16345305/600633)

**Comment by r-englund** [comment]
Probably true for the thread pool aswell.

**Comment by petersteneteg** [comment]
Did you do a get on the returned future? That will retrow the exception...

**Comment by r-englund** [comment]
Well, using the returned  future from the dispatchFront worked for me, I can now catch my exception. 
There are few things I am not 100 satisfied with this solution. 
* It works only in this place, if some other dispatchFront results in an exception, it would be list. 
* The code now looks off. There is a call to get on a future that returns void with a try catch around it. 
* 

It would be nice if this could be done in a more automatic way in processFront, similar to how we handle exceptions throw within a processor during network evaluation.  
I was very confused when the exception just disappeared. The code were I threw was not directly in the process front so I didn't know it was. What I expected was either a crash or a error message in the log, not that it disappeared

**Comment by petersteneteg** [comment]
This is not a bug. it is how it is designed to work...
