### ISSUE TITLE
How to properly use inviwo as a library

### ISSUE THREAD

**Issue by TheHugeManatee** [inviwo/inviwo#152]
Hi Inviwo Team,

I am trying to build an application based on inviwo using it as an external library. As a starting point I am going with the Qt minimal example, however I am already running into problems including inviwo properly at the cmake level: As far as I can see, there is no InvivoConfig.cmake generated during the build process, which from what I know necessary to cleanly include inviwo as an external library (using `find_package(inviwo REQUIRED)`) Am I missing some setting or is there any other way to create an independent project that does not "live" inside the inviwo cmake environment?

I am working on Windows with the latest CMake and Visual Studio updates, and I tried the cmake INSTALL target as well, but from what I can see this would extend to other platforms as well?

**Comment by petersteneteg** [comment]
At this point in time we provide no support for using inviwo as a subproject, like that. Should be possible to do, but it will probably require a fair amount of work... PRs would be welcome ;)

**Comment by TheHugeManatee** [comment]
I see, thanks for the answer! I found the IVW_EXTERNAL_PROJECTS setting which allows to integrate an inviwo-based standalone application into the inviwo build, so this is sufficient for my use case for now... 
Proper packaging would of course be cleaner at some point, but I understand that the work required is not trivial, so the current version is practical enough for now!

**Comment by petersteneteg** [comment]
Yes, that is one workaround we have at the moment. In the long term we would want to be able to include it as you suggest, but there is only so much time in a day. I will close this issue for now unless you object.
