### ISSUE TITLE
Alignment operations in TF editor

### ISSUE THREAD

**Issue by PetiteViking** [inviwo/inviwo#164]
It would be nice to have some alignment operators in the TF editor so one could e.g. bring all iso-values to one level and have them evenly spread out.

**Comment by petersteneteg** [comment]
Should be easy to add to the context menu. Martin and me talked about it when he refactored it, but he did not have time to implement all that...

**Comment by petersteneteg** [comment]
Think you can select multiple points and enter values in the editor on the right... will not spread then out evenly though...

**Comment by petersteneteg** [comment]
Think martin added this

**Comment by martinfalk** [comment]
Yes, part of PR #618
