### ISSUE TITLE
ButtonProperty is _modified_ during deserialization

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#165]
I noticed that the internal state of a `ButtonProperty` is set to `propertyModified_ = true;` (`setModified()`) during deserialization. In my opinion this is really bad since pressing the button itself will result in exactly the same state, i.e. "modified". 
This means that in the process function of my processor I am not able to differentiate between a regular button click and the first call of process after deserialization.

Bonus question: why should a processor with only a button property be evaluated after deserialization?

**Comment by petersteneteg** [comment]
All properties are modified on construction.

**Comment by martinfalk** [comment]
Should this be changed for the ButtonProperty then?

**Comment by petersteneteg** [comment]
Maybe
