### ISSUE TITLE
ResizeEvent is propagated before port connection is added

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#167]
Having a processor processing resize events, e.g. `ImageScaling`, reveals that `Processor::propagateEvent(Event* event, Outport* source)` is called before the port connection is added.
That is, checking `outport_.isConnected()` returns false.

**Comment by petersteneteg** [comment]
Why is this a problem

**Comment by martinfalk** [comment]
I consider this to be a bit inconsistent. As mentioned checking the port connection inside `propagateEvent()` will not work when an outport connection is added.

**Comment by martinfalk** [comment]
Just ran into this:
processor `A` with an optional `ImageInport`. When I connect the outport of processor `B` to this port, the output size of processor `B` is not adjusted and remains `8x8`
