### ISSUE TITLE
Formulas in processor help 

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#170]
Doxygen supports to include formulas in the documentation like this: 
`Generate a list of random points in \f$R^2\f$`
Doxygen will then generate a png image with black text and transparent background. This does not work well with our processor help, where we have a dark grey background. 

![image](https://user-images.githubusercontent.com/534670/41468253-9c015c3e-70a9-11e8-8ac8-7e447bdc4549.png)

I've tried to modify the css to modify the image but the css support by the qt help engine seems very limited.  For example, using 
```css
img.formulaInl {
	 filter: invert(100%);
}
```
will invert the result in the html file generated on disk, but the css will be ignored un the qt help engine. 
![image](https://user-images.githubusercontent.com/534670/41468263-a7516b42-70a9-11e8-9d49-bf591589ec33.png)

Adding a background color to the image works in both the html and in the qt widget. This might not look the most pleasing, but it works. 

![image](https://user-images.githubusercontent.com/534670/41468316-e2c0bc28-70a9-11e8-9cfd-7d9bee6beb74.png)

**Comment by r-englund** [comment]
One option could be to create an small standalone executable based only on CIMG for chaning black to text color

**Comment by petersteneteg** [comment]
Think you should be able to modify the image on the fly in 
QVariant HelpBrowser::loadResource(int type, const QUrl& name) in inviwo/src/qt/editor/helpwidget.cpp We already do that to restrict the width of images...

**Comment by petersteneteg** [comment]
I have some thought on not using doxygen for the processor help, but rather adding it directly as a inviwo::Document to the processor. That would probably break this feature :/...
