### ISSUE TITLE
Reorder Properties in UI

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#178]
Would be nice to be able to reorder properties, i.e. move them up or down. For example in the composite property. At the moment, the order is predetermined by the calls to `addProperty()`.

Reordering properties in a PropertyOwner is not sufficient, since deserialization is affected by the order of `addProperty()`
Suggestion: store some metadata to reorder properties upon deserialization.

**Comment by martinfalk** [comment]
Deserialization might also mess up the order in case some of the deserialized properties already exist. In this case, the "missing" properties will be appended to the property owner.

**Comment by martinfalk** [comment]
Member functions of `PropertyOwner` now include  
- `virtual void insertProperty(size_t index, Property& property);` 61049fa811c3fb842bac56b9ca0920e59e4bc899
- `virtual Property* removeProperty(size_t index);` 656a017c04a6dbc6cfa86a47c085cdaa26714bad

**Comment by petersteneteg** [comment]
Not a high priority
