### ISSUE TITLE
Move Processor help into Processor/Port/Property

### ISSUE THREAD

**Issue by petersteneteg** [inviwo/inviwo#181]
Sometimes it would be useful to be able to access the processor help from within inviwo, without using the help widget.

Would be nice to be able to add the property related help in the processor help to the tooltip of a property widget for example.

A way to do this would be to move the help text into the actual processor, instead of using the doxygen thing. If we also add help to the property and ports, we should be able to compose that automatically in a nice way.

This mean we will not have any docpages for doxygen though. But we might be able to generate that in the same way as we generate the processor images for doxygen now...

thoughts? suggestion?

**Comment by martinfalk** [comment]
I think that would be good to have. See also #117

**Comment by martinfalk** [comment]
How would you deal with the construction of the help text? Where does the information come from?

Build from e.g. `processor desc`, `<generated image>`, `additional information`, `list properties`, etc.

**Comment by petersteneteg** [comment]
My thinking was to add docs to properties and ports, and then compose that in the processor maybe, similar to how we do the other "info" stuff...

**Comment by petersteneteg** [comment]
Fixed
