### ISSUE TITLE
ValueWrapper can result in invalid XML

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#188]
The constructor `ValueWrapper(T val)` sets the name to empty string. When e.g. a `ValueWrapper<int>` is serialized this results in `< content="0" />`. Here the tag name is missing/empty.

Is this the intended behavior or should `Serializer::serialize(const std::string &key, data)` complain about empty keys?

See [source code](https://github.com/inviwo/inviwo/blob/master/include/inviwo/core/properties/valuewrapper.h#L44)

**Comment by r-englund** [comment]
Feels like we should throw an exception at somepoint if name is empty string. In the beggining of the serialize function maybe?

**Comment by martinfalk** [comment]
@r-englund I second that!

**Comment by petersteneteg** [comment]
Could we remove that constructor?

**Comment by petersteneteg** [comment]
I've removed that constructor...
