### ISSUE TITLE
Error messages during deserialization should be more informative

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#189]
When loading a workspace with misformed XML, the error messages are not really helpful.
For example:
```
Unable to load network D:/projects/inviwo/mysettings/workspaces/tests/listproperty.inv due to Type is unsupported <ticpp.cpp@250>
```

This particular error was caused by `< content="0" />` in the workspace file (see #188).
Wouldn't it be possible to at least print the string in question or even the surrounding property/processor? In particular since we have a defined context in this example, i.e. inside a property.

**Comment by petersteneteg** [comment]
You are welcome to implement more error messages, but since we don't, and should not, write xml manually, the return on the time invested seems very low to me...

**Comment by petersteneteg** [comment]
This is very far down on my list, will close for now.
