### ISSUE TITLE
Empty CompositeProperty not shown

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#190]
When adding a `CompositeProperty`, which does not have any sub properties, this composite will not show up in the property list.

However, removing the last sub property of a CompositeProperty (using `removeProperty()`) will result in the CompositeProperty stating "no properties available".
![image](https://user-images.githubusercontent.com/9251300/43207050-6908f416-9027-11e8-8091-6eb3856ce1c1.png)

**Comment by r-englund** [comment]
https://github.com/inviwo/inviwo/blob/master/modules/qtwidgets/properties/collapsiblegroupboxwidgetqt.cpp#L280-L284
```c++
if (showIfEmpty_ || !empty) {
        PropertyWidgetQt::setVisible(visible);
    } else {
        PropertyWidgetQt::setVisible(false);
}
```

**Comment by r-englund** [comment]
I guess it is not a bug, but a undocumented feature. Maybe print a log message when this happens?

**Comment by petersteneteg** [comment]
This is a bug. The behaviour should be constant. We need to hide them in certain circumstances, like when we are in app mode and most of them will be empty...

This might provide a challenge to the dynamic list property. Need to think about how that should work.

Logging this make no sense...

**Comment by martinfalk** [comment]
@petersteneteg then the question would be what the expected behavior is?

In my case, explicitly adding a CompositeProperty (without sub properties) but not showing up made me question whether the build is up-to-date.

**Comment by petersteneteg** [comment]
Me might have to take the app mode into account...

**Comment by ResearchDaniel** [comment]
This does not seem to be a major issue? There is an option showIfEmpty_ that can be set for the cases where it should show. It is probably fine to make sure it is not shown by default.
Re-open if you disagree
