### ISSUE TITLE
CompositeProperty linking

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#191]
The CompositeProperty only checks if the number of sub properties match, and then it is up to the individual sub properties.

This seems like a really bad idea.

https://github.com/inviwo/inviwo/blob/3e5953ae9172015fef34564b97a6db740af2f72f/src/core/properties/compositeproperty.cpp#L64-L75

**Comment by martinfalk** [comment]
How about matching based on ID but checking same position first?

**Comment by petersteneteg** [comment]
hmm, which Id? we can often link properties of different classes... so one can't really use class identifiers... 
The processor network as a canLink function to check if two properties can be linked...
But we rather check that when we create the link then on every evaluation of the link...

**Comment by martinfalk** [comment]
Maybe something similar to `ListProperty`? 
https://github.com/inviwo/inviwo/blob/ca2614c1408b938f42ee0f2145416e6e5dcc67f6/src/core/properties/listproperty.cpp#L111

**Comment by petersteneteg** [comment]
Unfortunately I don't think the set in listproperty is very clean either... Think this needs more thinking

**Comment by petersteneteg** [comment]
Btw the list Property one is broken...

**Comment by petersteneteg** [comment]
Fixed the list property now.

Don't really see the issue here?
