### ISSUE TITLE
Issues with CollapsibleGroupBoxWidgetQt

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#192]
`CollapsibleGroupBoxWidgetQt::onDidProperty()` is broken for two reasons when a property does not have a corresponding property widget.
1) newly added widgets are inserted into the vector holding the property widgets. This does not account for potentially "missing" widgets, i.e. the order of the property widgets might not correspond to the order in the property owner. In case the widget does not exist, nothing is added to the property widget vector!
2) `QGridLayout` does **not** support inserting rows into the layout. Adding a widget to an already occupied cell results in both widgets showing up on top of each other.

For 1) see
https://github.com/inviwo/inviwo/blob/e4007c17c286099a3d395cf6cd492ef32d3a849f/modules/qtwidgets/properties/collapsiblegroupboxwidgetqt.cpp#L324-L330

**Comment by martinfalk** [comment]
This also affects `CollapsibleGroupBoxWidgetQt::onWillRemoveProperty()` since the index is used to directly look up widgets.
https://github.com/inviwo/inviwo/blob/e4007c17c286099a3d395cf6cd492ef32d3a849f/modules/qtwidgets/properties/collapsiblegroupboxwidgetqt.cpp#L339-L346

**Comment by petersteneteg** [comment]
In the animation bransch we reorder widget by just removing add adding all off them. Still seems very fast...

**Comment by petersteneteg** [comment]
Maybe we need a dummy for when the widgets are missing

**Comment by martinfalk** [comment]
Working on a solution which creates a new grid layout when inserting new properties. When Properties are added at the end, they are simply appended.

**Comment by martinfalk** [comment]
Also adding nullptr to the property widget vector so property and property widget vectors are in sync.
