### ISSUE TITLE
Mark workspace files as binary in github?

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#2]
When doing code reviews, quite often those are bloated by changes in workspace files.

**Comment by r-englund** [comment]
Would that mean that you couldn't view the xml while browsing the source?

**Comment by petersteneteg** [comment]
@martinfalk thats why i did two commits, select the first one

**Comment by martinfalk** [comment]
@petersteneteg: I noticed that the second time. But clicking on "review" on github will show "all" changes...

**Comment by petersteneteg** [comment]
Yes, you have to filter your self

**Comment by r-englund** [comment]
Meeting: Action: Try in research-dev

**Comment by r-englund** [comment]
Tried on research-dev, don't think it works as we wanted to 
https://github.com/inviwo/research-dev/commit/e98caa93a260e2918c0fcc778c93d6f32ddbc535 
https://github.com/inviwo/research-dev/pull/52/files#diff-177939aa6bc74f04c3904d433a731dc1

**Comment by r-englund** [comment]
Does not seem possible
