### ISSUE TITLE
Canvas not shown when adding CanvasProcessor

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#203]
I noticed that when adding a `Canvas` processor to a network, the canvas windows does not show up. Only after double clicking the processor the canvas is visible.

Suspecting Qt behind this behavior since I changed version from 5.9.1 to 5.11.1 recently.

**Comment by martinfalk** [comment]
This version check in the constructor of `CanvasProcessorWidgetQt` does change the visibility status stored in the MetaData of the processor widget:
https://github.com/inviwo/inviwo/blob/2e1c41a9d1209dfa5fb9ea91928167eca1381754/modules/openglqt/canvasprocessorwidgetqt.cpp#L96-L105

Before, `ProcessorWidgetMetaData::visibility_` is `true`. But `QWidget::setVisible(false)` has side effects.

**Comment by martinfalk** [comment]
The problem is caused by nested usage of `util::KeepTrueWhileInScope ignore(&ignoreEvents_); ` on the same variable, i.e. `ignoreEvents_`. The inner use resets `ignoreEvents_` to false and hence the visibility status `false` is written to the metadata.

See #204

**Comment by petersteneteg** [comment]
@martinfalk this is fixed right?

**Comment by martinfalk** [comment]
fixed in #205
