### ISSUE TITLE
Option for resetting PythonScriptProcessor

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#207]
When creating a small python script for `PythonScriptProcessor` like
```python
import inviwopy
from inviwopy.properties import ButtonProperty
from inviwopy.data import *
import ivw.utils as inviwo_utils

def buttonCallback():
    print("button pressed")

if not "button" in self.properties:
    self.addProperty(ButtonProperty("button", "Button"))
    self.properties.button.onChange(buttonCallback)

def process(self):
    pass

def initializeResources(self):
    pass

self.setInitializeResources(initializeResources)
self.setProcess(process)
```

It is not possible to change the contents of the callback function afterwards since the property already exists. Currently there is no way besides either creating a new script processor with the same script or reloading the workspace.

**Comment by martinfalk** [comment]
In case the python script fails, it might crash Inviwo. This was tested for the `onChange` callback of the button.

**Comment by petersteneteg** [comment]
Dont use them...
