### ISSUE TITLE
Build error with new Visual Studio Update

### ISSUE THREAD

**Issue by VisComKreiser** [inviwo/inviwo#208]
Hey,

i can not build inviwo with the new Visual Studio 2017 Update 15.8.1 (15.8.0 also did not work).
I get internal compile errors which seem to be rooted that the latest C++ version is inforced through cmake.

I can fix most of it by using
`list(APPEND comp_opts "/std:c++14")`
instead of
`list(APPEND comp_opts "/std:c++latest")`
in the "/cmake/compileoptions.cmake" file.
However, the vectorfieldvisualization module still does not compile even with C++14.

This is the error list before switching to C++14
![image](https://user-images.githubusercontent.com/11948756/44391119-500ee700-a52f-11e8-8a6c-b4eb06be457a.png)

These are the errors from the vectorfieldvisualization module still afterwards
![image](https://user-images.githubusercontent.com/11948756/44391132-5735f500-a52f-11e8-9942-f7f080ed0ac4.png)

Best,
Julian

**Comment by petersteneteg** [comment]
Can you specify which update you are referring to? 15.8.1 or some other one?

**Comment by VisComKreiser** [comment]
i'm using 15.8.1, on 15.8.0 was the same problem.

**Comment by petersteneteg** [comment]
well at least you managed to compile inviwo-core, For me it bails out already in there...

**Comment by VisComKreiser** [comment]
even when switching back to C++14?

**Comment by VisComKreiser** [comment]
inviwo core was also the first module where the error occured for me, that is just not in the screenshot

**Comment by petersteneteg** [comment]
ahh ok.. same here then...

**Comment by petersteneteg** [comment]
ahh ok.. 
with std:c++14 it build all modules, in debug, Did you use release?

**Comment by VisComKreiser** [comment]
I tried both, it builds on Debug and Release, exept for the the vectorfield module, that one does not build on Debug at least, didn't try for Release.

**Comment by petersteneteg** [comment]
Ok, it built for me, but I might have a slightly different head branch...

**Comment by VisComKreiser** [comment]
wouldn't it also be more general if the **CMAKE_CXX_STANDARD** variable would be set instead of the compiler flags directly?

**Comment by petersteneteg** [comment]
we do also do  "set(CMAKE_CXX_STANDARD 14)" in globalconfig... std:c++latest is a VS specific flag... By having that it is possible to use newer feature outside of inviwos core, which is sometimes nice...

**Comment by petersteneteg** [comment]
https://developercommunity.visualstudio.com/content/problem/313656/fatal-error-c1001-an-internal-error-has-occurred-i-20.html

**Comment by petersteneteg** [comment]
using --std:c++17 also fails to compile...

**Comment by petersteneteg** [comment]
using --std:c++14 now...
