### ISSUE TITLE
Feature: spinner property semantics

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#221]
See https://github.com/inviwo/inviwo-dev/issues/1436

**Prototype:**
- Textbox with Spinner behavior (supports mouse wheel)
- drag blue dot up or down to adjust value
![image](https://user-images.githubusercontent.com/9251300/44993222-1bbd1100-af9a-11e8-96f3-9f2f40b6f048.png)

**Comment by ResearchDaniel** [comment]
How about adding/changing to arrows with a dot inbetween to make it easier to understand that you can drag it up/down?
^
•
Downarrow

**Comment by martinfalk** [comment]
way too small. The idea is to support touch as well. And dragging either of them will result in the same effect.

**Comment by martinfalk** [comment]
added in PR #226
