### ISSUE TITLE
Animation module compile error in XCode

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#222]
Get the following compile error in XCode:

> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:4333:13: No matching function for call to object of type 'std::__1::__less<std::__1::chrono::duration<double, std::__1::ratio<1, 1> >, inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<glm::vec<3, float, glm::qualifier::packed_highp> > > &>'

The error seem to appear on all instantiations of KeyFrameSequenceTyped. From what I can see the operator< is implemented for KeyFrameSequence. Any idea on how to resolve?

**Environment information**
* Operating System: Mac
* Compiler/IDE: LLVM 9.0/Xcode

Log:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:4333:13: No matching function for call to object of type 'std::__1::__less<std::__1::chrono::duration<double, std::__1::ratio<1, 1> >, inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > &>'
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/animationmodule.cpp:30:10: In file included from /Users/danieljonsson/Documents/inviwo/dev/modules/animation/animationmodule.cpp:30:
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/animationmodule.h:34:10: In file included from /Users/danieljonsson/Documents/inviwo/dev/modules/animation/animationmodule.h:34:
/Users/danieljonsson/Documents/inviwo/dev/include/inviwo/core/common/inviwomodule.h:33:10: In file included from /Users/danieljonsson/Documents/inviwo/dev/include/inviwo/core/common/inviwomodule.h:33:
/Users/danieljonsson/Documents/inviwo/dev/include/inviwo/core/common/inviwo.h:54:10: In file included from /Users/danieljonsson/Documents/inviwo/dev/include/inviwo/core/common/inviwo.h:54:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:10: In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:10: In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:15:10: In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:15:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:10: In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:10: In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:10: In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:4355:12: In instantiation of function template specialization 'std::__1::__upper_bound<std::__1::__less<std::__1::chrono::duration<double, std::__1::ratio<1, 1> >, inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > &> &, inviwo::util::IndirectIterator<std::__1::__wrap_iter<const std::__1::unique_ptr<inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> >, std::__1::default_delete<inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > > > *>, true>, std::__1::chrono::duration<double, std::__1::ratio<1, 1> > >' requested here
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:4364:19: In instantiation of function template specialization 'std::__1::upper_bound<inviwo::util::IndirectIterator<std::__1::__wrap_iter<const std::__1::unique_ptr<inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> >, std::__1::default_delete<inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > > > *>, true>, std::__1::chrono::duration<double, std::__1::ratio<1, 1> >, std::__1::__less<std::__1::chrono::duration<double, std::__1::ratio<1, 1> >, inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > &> >' requested here
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/datastructures/propertytrack.h:320:20: In instantiation of function template specialization 'std::__1::upper_bound<inviwo::util::IndirectIterator<std::__1::__wrap_iter<const std::__1::unique_ptr<inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> >, std::__1::default_delete<inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > > > *>, true>, std::__1::chrono::duration<double, std::__1::ratio<1, 1> > >' requested here
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/datastructures/propertytrack.h:172:5: In instantiation of member function 'inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> >::operator()' requested here
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3032:32: In instantiation of member function 'inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> >::PropertyTrack' requested here
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/factories/trackfactoryobject.h:63:74: In instantiation of function template specialization 'std::__1::make_unique<inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> >>' requested here
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/factories/trackfactoryobject.h:57:5: In instantiation of member function 'inviwo::animation::TrackFactoryObjectTemplate<inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> > >::create' requested here
/Users/danieljonsson/Documents/inviwo/dev/include/inviwo/core/util/stdextensions.h:58:35: In instantiation of member function 'inviwo::animation::TrackFactoryObjectTemplate<inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> > >::TrackFactoryObjectTemplate' requested here
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/animationsupplier.h:111:24: In instantiation of function template specialization 'inviwo::util::make_unique<inviwo::animation::TrackFactoryObjectTemplate<inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> > >>' requested here
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/animationmodule.cpp:54:8: In instantiation of function template specialization 'inviwo::animation::AnimationSupplier::registerTrack<inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> > >' requested here
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:703:10: Candidate function not viable: no known conversion from 'const inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> >' to 'const std::__1::chrono::duration<double, std::__1::ratio<1, 1> >' for 2nd argument
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:706:10: Candidate function not viable: 2nd argument ('const inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> >') would lose const qualifier
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:709:10: Candidate function not viable: no known conversion from 'const std::__1::chrono::duration<double, std::__1::ratio<1, 1> >' to 'inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > &&' for 1st argument
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:712:10: Candidate function not viable: no known conversion from 'const std::__1::chrono::duration<double, std::__1::ratio<1, 1> >' to 'inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > &&' for 1st argument

**Comment by petersteneteg** [comment]
@ResearchDaniel is this still the case?

**Comment by petersteneteg** [comment]
Ping @ResearchDaniel
