### ISSUE TITLE
Image Layers are not initialized

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#236]
Since ImageOutports always have some dummy data (8 by 8 pixel), the following network shows random artifacts despite the image source processor does not have any data set to its outport.

Here, the filename of ImageSource is not set.

![image](https://user-images.githubusercontent.com/9251300/45541250-da84f680-b80e-11e8-8052-922683fc87ba.png)

**Comment by martinfalk** [comment]
Should a color layer of an `Image` always be initialized?

**Comment by martinfalk** [comment]
Same applies when inspecting an unset ImageOutport with the PortInspector

![image](https://user-images.githubusercontent.com/9251300/45546523-d14f5600-b81d-11e8-8e79-719ef73293d8.png)

**Comment by ResearchDaniel** [comment]
I could reproduce it on Mac as well. Would setting the outport data to null in ImageSource resolve the issue?

**Comment by martinfalk** [comment]
Might solve this. But at the moment, the process function is only evaluated once you provide an existing file (connected to isReady()).

Need to test.

**Comment by ResearchDaniel** [comment]
Have a fix for it

**Comment by martinfalk** [comment]
Setting the image output of ImageSource to nullptr does the trick.
In `ImageSource::ImageSource()`:
```
    auto func = static_cast<void (ImageOutport::*)(std::shared_ptr<Image>)>(&ImageOutport::setData);
    (outport_.*(func))(nullptr);
```

**Comment by martinfalk** [comment]
When creating an `Image` from a single layer, e.g. a color image loaded from disk as done in `Image Source`, the other layers (picking, depth) are not initialized.
