### ISSUE TITLE
Unable to build source from release page

### ISSUE THREAD

**Issue by onc** [inviwo/inviwo#237]
**Issue**

Unable run CMake on the source code downloadable from the release section.

When downloading the zip file with the source code from the latest release from here (https://github.com/inviwo/inviwo/releases) CMake fails with the following error:

```
CMake Error at ext/utf/CMakeLists.txt:31 (add_custom_target):
  Cannot find source file:

    /Users/onze/Downloads/inviwo-0.9.9/ext/utf/utfcpp/source/utf8.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at cmake/globalmacros.cmake:582 (add_library):
  Cannot find source file:

    /Users/onze/Downloads/inviwo-0.9.9/ext/utf/utfcpp/source/utf8.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  modules/fontrendering/CMakeLists.txt:48 (ivw_create_module)
```

**Steps to reproduce**

Downloading the zip and running cmake. For example for macOS:

```
unzip inviwo-0.9.9.zip
cd inviwo-0.9.9
mkdir build && cd build
cmake ..
```

**Environment information**

* Operating System: macOS 10.13.6 and Windows 10 Pro
* CMake Versions: 
    - on macOS: 3.12.2
    - on Windows: 3.8.1

**Comment by martinfalk** [comment]
Hi,

it appears that submodules are not part of the zip file for some reason. We will be working on this.

Please note that the recommended way to build Inviwo is to access the source files via cloning the Inviwo  repository. Don't forget to initialize the submodules though.

To do this use either (works with git version 2.13 and later)
```
git clone --recurse-submodules git://github.com/inviwo/inviwo.git
```
or
```
git clone git://github.com/inviwo/inviwo.git
cd inviwo
git submodule update
git submodule init
```

**Comment by martinfalk** [comment]
#128

**Comment by onc** [comment]
hey martin,

(just to make this clear, I'm christian from ulm ;) )
cloning from git totally should be the way to go, that's true. But there are two reasons why we opened up this issue.

- While discussing the new homepage we where talking about where we would lead the user to download the source code and I think we ended up in the "Release" section of this repo, since this should be the latest stable version.
- We are currently working on setting up automated builds for inviwo and had some issues trying to build the current master (see #239). We then downloaded the zip from the release section and noticed that this version also fails to compile.

So this is just for your information that there might be something wrong. I'm not sure, but I think this zip-file is autogenerated by github, right?

**Comment by martinfalk** [comment]
No, there is currently a Jenkins job running in order to create the zip file. Using the download option on github will give you a zip file without any of the external submodules.

In our discussions, we discussed to remove the option to download the source code entirely, if I remember correctly. But there should be a prominent link to github (available for all platforms). If you insist, you could add a link to the source code, which redirects the user to the github page.

**Comment by onc** [comment]
Ok, I get it.

Also, we just wanted to point out that there is a zip file with source code where other people might expect to get a stable version of inviwo, but this does not compile.

If you are aware of that and the zip should be removed in the future we could close this issue I guess.

**Comment by martinfalk** [comment]
OK, will close this for now.
