### ISSUE TITLE
ImageOutport always has data

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#241]
By default, `ImageOutport` has an uninitialized default image (see #236). Therefore, querying this ImageOutport for its data (`ImageOutport::hasData()`) will return `true` even though no data has been set.

E.g. the background processor queries its inport whether it has data and then renders the input image.

**Comment by martinfalk** [comment]
Temporary fix: use `inport_.isReady()` instead.

**Comment by martinfalk** [comment]
`isReady()` is not sufficient in every case!

For instance, when using the `ImageSource` processor. The color layer contains the image but the picking layer is not initialized.

**Comment by petersteneteg** [comment]
humm, not sure what the issue is here exactly, the pickinglayer representation will be created on demand by the representation factory.

**Comment by petersteneteg** [comment]
and that layer should generally be initialized.

**Comment by petersteneteg** [comment]
maybe not in the gl case though?

**Comment by r-englund** [comment]
> 
> 
> humm, not sure what the issue is here exactly, the pickinglayer representation will be created on demand by the representation factory.

Did the representation factory exist in October 2018?

**Comment by petersteneteg** [comment]
No don't think so...

**Comment by martinfalk** [comment]
Closing the issue for now.
