### ISSUE TITLE
Removing ImagePort connections changes aspect ratio

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#244]
When removing image port connections on optional ports, the aspect ratio changes.

Network for reproducing this (using a non-square canvas size)
![image](https://user-images.githubusercontent.com/9251300/45553921-71fd4000-b835-11e8-9d90-5bbd759f90ae.png)

Before deletion:
![image](https://user-images.githubusercontent.com/9251300/45553937-80e3f280-b835-11e8-9254-ccac1fdd7db7.png)

After deletion:
![image](https://user-images.githubusercontent.com/9251300/45553955-8b05f100-b835-11e8-86f4-5848edeb88c4.png)

**Comment by martinfalk** [comment]
The issue is most likely caused by linked cameras (aspect ratio), a resize event spawned upon disconnect, and the default layer of an image (8 by 8 pixel).

Disconnecting the ImageOutport leads to a resize event of `uvec2(0, 0)` on the disconnected outport.
https://github.com/inviwo/inviwo/blob/76fa0dc8c6946c96cacdc40069fedb1e59f3cc2a/src/core/ports/imageport.cpp#L90-L96

In addition, an Image has a default layer of size 8x8 which affects the aspect ratio of the camera as well.

**Comment by martinfalk** [comment]
see #241

**Comment by ResearchDaniel** [comment]
Should a resize event be propagated on disconnect?
