### ISSUE TITLE
 Portinspector has side-effects on canvas contents

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#245]
When a PortInspector is created while using a non-square canvas, the aspect ratio of the cameras will change.
Potentially this is caused by bi-directional autolinking of the cameras.

See https://github.com/inviwo/inviwo-dev/issues/1339

**Comment by martinfalk** [comment]
The camera used in the port inspector network is not necessarily linked to the correct/matching camera.
For example having multiple independent raycasting pipelines, my port inspector camera is linked with the left-most pipeline despite inspecting the one on the right.

**Before**
<img width='512px' src='https://user-images.githubusercontent.com/9251300/48554063-af398900-e8dd-11e8-9bbb-eae3c716340a.png'/>

**With port inspector below Cube Proxy (right side)***
<img width='512px' src='https://user-images.githubusercontent.com/9251300/48554037-97620500-e8dd-11e8-9f98-1c7c2e9d86f6.png'/>

**Comment by petersteneteg** [comment]
Fixed in #312
