### ISSUE TITLE
`self` in PythonScriptProcessor 

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#247]
`self` in PythonScriptProcessor might be persistent in between multiple processors.

Likewise, objects added to `self` in a python script are not available the first time `process` gets called. When the script is reloaded a second time, the object is part of `self`.

Example:
```
self.pm = inviwopy.PickingMapper(self, 1, callback)

self.setInitializeResources(initializeResources)
self.setProcess(process)
```

Error:
```
Python Script Processor Error in Process: AttributeError: PropertyOwner (PythonScriptProcessor) does not have a property with identifier: 'pm'

At:
  C:/dev/data/vasp-chargedensity/vasp-rev3.py(184): process
```

**Comment by petersteneteg** [comment]
Use a python processor
