### ISSUE TITLE
Create a "Inviwo Jenkins" github user

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#25]
Right now it is peters GitHub account that is being used on Jenkins to be able to pull Inviwo source code and to set checks on PR and commits etc. 
I did some experimenting on getting Jenkins to push doc updates to gh-pages (#19). ATM, these commits looks like they are made by Peter. 

IMO, it would look a bit better if those commits and status updates used a Inviwo account instead. 

![image](https://user-images.githubusercontent.com/534670/36538335-4ae6a716-17d3-11e8-9c52-976691876aaf.png)

**Comment by r-englund** [comment]
Oh, right after clicking "Create issue" I realised we have the Inviwo-Team user. Maybe we can use something like that?

**Comment by ResearchDaniel** [comment]
I think that it could be more informative with a Jenkins-icon showing up?

**Comment by r-englund** [comment]
Agree

**Comment by ResearchDaniel** [comment]
http://mirrors.jenkins-ci.org/art/jenkins-logo/

**Comment by ResearchDaniel** [comment]
Do we have to create a "fake" inviwo-jenkins github user or is it possible to use a new team?

**Comment by r-englund** [comment]
Not sure you could use a Team to authenticate, guess you need a username/password. @petersteneteg might know more.

**Comment by martinfalk** [comment]
I would probably go for a specific "jenkins" user instead of the team. When using the Inviwo Team it would be strange to see the jenkins icons used there.

**Comment by ResearchDaniel** [comment]
@martinfalk We would create a new team called Jenkins

**Comment by martinfalk** [comment]
ah.

**Comment by petersteneteg** [comment]
Think erik created our inviwo team user....

**Comment by r-englund** [comment]
Probably.   
And it is actually a user (I/We thought it was a team in our github organization) https://github.com/Inviwo-Team

**Comment by petersteneteg** [comment]
We acctually have a Inviwo-Team user, I have the credentials if needed...

**Comment by petersteneteg** [comment]
Need to add it to the hooks also...

**Comment by petersteneteg** [comment]
Think this is done AFAIK
