### ISSUE TITLE
Closing Canvas / ColorDialog breaks window - Qt 5.11

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#251]
When closing the color dialog of a color property via the "x" button in the window title bar, the dialog cannot be reopened and only a small empty widget pops up.

![image](https://user-images.githubusercontent.com/9251300/45840619-b5fdb280-bd17-11e8-94ce-52614e954110.png)

Closing the dialog via <Esc> works fine.

**Comment by martinfalk** [comment]
This affects Qt 5.11.1

Also tested with Qt 5.9.1 where the dialog behaves as expected.

**Comment by martinfalk** [comment]
A similar effect occurs in the canvas widget when it is closed using the close button.
After re-showing the canvas widget, the contents remain black and the rendered output is not visible.

Only after hiding the canvas and reshowing it via the canvas processor, the contents are visible.

**Comment by petersteneteg** [comment]
Has anyone tried this in newer qt?

**Comment by r-englund** [comment]
Can reproduce qt 5.13(.0)

**Comment by r-englund** [comment]
Also in qt 5.13.1_preview

**Comment by r-englund** [comment]
Can reproduce with Color Property (tested with background), when double clicken a TF point in the TF editor. 
This also happens with the Ordinal Propety Settings widget and for the min max property settings widget

**Comment by r-englund** [comment]
Seems to be this or related to this qt bug https://bugreports.qt.io/browse/QTBUG-76509?jql=text%20~%20%22QDialog%22

**Comment by martinfalk** [comment]
Running into similar problem with ProcessorWidgetQt, which remains empty after a close.

see also https://bugreports.qt.io/browse/QTBUG-71519

**Comment by emmwel** [comment]
In Qt 5.14, the color dialog reappears incomplete (instead of being empty)

![image](https://user-images.githubusercontent.com/21198447/75983650-2e930780-5ee9-11ea-9e50-f4d01be85722.png)

**Comment by petersteneteg** [comment]
should be fixed now https://github.com/inviwo/inviwo/pull/939/commits/f205caf0d39e6fb83fd15a9b8f24d261d9b928c0
