### ISSUE TITLE
Dysfunctional web browser example workspace

### ISSUE THREAD

**Issue by Alboin** [inviwo/inviwo#269]
**Issue**

One of the example workspaces for the web browser processor uses a path that doesn't exist (for most of us)  to load the html-file, which means that the example workspace doesn't really work :) Maybe make the path relative to the workspace, or change the property so that the Inviwo user can browse a file instead of typing in the whole file-path?

Maybe the processor could have as an option to load an online webpage, but by default use a file browsing property?

![image](https://user-images.githubusercontent.com/8807821/46394031-01d13400-c6e8-11e8-9695-102d3e8cc3b7.png)

**Comment by ResearchDaniel** [comment]
Agree! 
Should add a file property and use that as default. Optional online page.

You are welcome to add it :)

**Comment by ResearchDaniel** [comment]
Closed by #270
