### ISSUE TITLE
filesystem::fileExists broken

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#272]
`_wstat()` in `filesystem::fileExists()` returns `false` despite that the given file exists.
https://github.com/inviwo/inviwo/blob/12ed7f1c4cce6d89740248e6f9fc2994dd048e69/src/core/util/filesystem.cpp#L216-L225

Example:
```
std::string filename = "H:/100__2_106135.svs.svs";
if (filesystem::fileExists(filename)) {
    LogInfo("file exists");
}
std::fstream f(filename);
if (f.is_open()) {
    LogInfo("file opened");
}
```
For some strange reason, the output is `file opened` and no indication that the file exists.

**Comment by ResearchDaniel** [comment]
Perhaps _wstat should be used instead of _stat for the buffer variable?

https://bugs.launchpad.net/sbcl/+bug/1267540

**Comment by martinfalk** [comment]
We are actually using `_wstat` and converting the input file name to UTF8 using a multibyte conversion in `util::toWstring()`

**Comment by petersteneteg** [comment]
std::filesystem::exists ...

**Comment by ResearchDaniel** [comment]
#idef C++17
So not yet complete solution

**Comment by petersteneteg** [comment]
Well we could change that to ;)

**Comment by petersteneteg** [comment]
Sorry, wrong button.

But on a serious side, we should really consider switching to 17. We have to consider how much extra work we have to put in to support by not using what is in 17, and what we gain by not requiring 17. I don't know of anyone or anything where we couldn't require 17, so why spend time and money on this...

**Comment by ResearchDaniel** [comment]
Sure, let's discuss it on the next meeting and check with others using it at IEEE VIS.

**Comment by petersteneteg** [comment]
Yes that is a good ide!

**Comment by martinfalk** [comment]
So, what's the short-term fix here?

**Comment by ResearchDaniel** [comment]
Seems like it is now supported by most compilers
https://en.cppreference.com/w/cpp/compiler_support
Time for a change :) ?

**Comment by petersteneteg** [comment]
Yes, we could use this now. But I would prefer to go over and replace as much of our filesystem stuff as possible in one go. And ideally I would also want to start using std::filesystem::path instead of std::string for all our paths...

**Comment by petersteneteg** [comment]
Done
