### ISSUE TITLE
OSX Deployment

### ISSUE THREAD

**Issue by petersteneteg** [inviwo/inviwo#281]
The deployed osx image has a bunch of issues
The generated image from travis can be found at:
https://github.com/inviwo/inviwo/releases/tag/v9.9.0.travis3

It gets the wrong base path, hence it can't load any shaders for example
>> Base Path: Applications/Inviwo.app/Contents/Resources

The about window starts out in a floating docked state

The dmg has a bunch of file that outside of the Inviwo.app folders
![image](https://user-images.githubusercontent.com/3638222/47962016-744e7000-e016-11e8-9ef5-38e8742245da.png)
Only Inviwo.app should be in this picture

The build info will not work since it is at the wrong location...

A lot of modules are missing in the travis build
![image](https://user-images.githubusercontent.com/3638222/47962030-b5468480-e016-11e8-8534-b16302cd3ad6.png)

@ResearchDaniel, @onc  Have you seen any of this?

**Comment by onc** [comment]
indeed, I get the same issues you describe. Alex and I have never built an app as a dmg and after being able to build the dmg, install it and being able to launch the application, we expected that everything works. But apparently, there are indeed some problems with the bundling... We might have to look into how to tell cmake how to pack the assets and libs.

**Comment by petersteneteg** [comment]
So the base path probably gets wrong somewhere here
https://github.com/inviwo/inviwo/blob/b425eec4dc167be154cb30720dbfe47d1c5b43a7/src/core/util/filesystem.cpp#L478-L500

and the extra and misplaced files come from erroneous CMake install commands. It't not so hard to fix but a bit tedious since it can be a bit hard to figure out where the source is...

**Comment by petersteneteg** [comment]
will use GitHub auction for all of this
