### ISSUE TITLE
Maximized window title bar bug on Windows (Qt bug?)

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#289]
**Issue**
On windows: Title bar consumes two rows and it is not possible to press close/minimize buttons 
![image](https://user-images.githubusercontent.com/8738140/48250483-c6b8d380-e3fe-11e8-8c4c-f19fe181a07f.png)

**Workaround**
Remove following register entries in Computer\HKEY_CURRENT_USER\Software\Inviwo Foundation\Inviwo\InviwoMainWindow
geometry
maximized
state

**Steps to reproduce**
Maximize Inviwo editor window

**Environment information**
* Operating System: Windows 10
* QT Version: 5.10.1

**Comment by ResearchDaniel** [comment]
Judging by the documentation here http://doc.qt.io/qt-5/application-windows.html#window-geometry it seems like frameGeometry().height() or y() position are not correct?

**Comment by martinfalk** [comment]
Seems like something went wrong when the window state was serialized by Qt. Closing this for now.
