### ISSUE TITLE
sqlite3.dll is missing after successful build

### ISSUE THREAD

**Issue by TheHugeManatee** [inviwo/inviwo#30]
While all other dlls get deployed correctly, sqlite3.dll seems to be missing.
This causes an exception to be thrown at qt/editor/qthelpwidget.cpp:167 with an error message of "cannot load sqlite database driver" when starting the application from within visual studio or from the bin/ folder.

Build Environment: Visual Studio Enterprise 2017, VCPKG, Qt 5.9.2
Applies to both debug and release builds

Console output additionally shows the following: 

> Warning: QSqlDatabase: QSQLITE driver not loaded (D:\lib\vcpkg\buildtrees\qt5-base\src\qtbase-5.9.2\src\sql\kernel\qsqldatabase.cpp:694, void __cdecl QSqlDatabasePrivate::init(const class QString &))
> Warning: QSqlDatabase: available drivers: QSQLITE QODBC QODBC3 QPSQL QPSQL7 (D:\lib\vcpkg\buildtrees\qt5-base\src\qtbase-5.9.2\src\sql\kernel\qsqldatabase.cpp:695, void __cdecl QSqlDatabasePrivate::init(const class QString &))
> Warning: QSqlDatabase: QSQLITE driver not loaded (D:\lib\vcpkg\buildtrees\qt5-base\src\qtbase-5.9.2\src\sql\kernel\qsqldatabase.cpp:694, void __cdecl QSqlDatabasePrivate::init(const class QString &))
> Warning: QSqlDatabase: available drivers: QSQLITE QODBC QODBC3 QPSQL QPSQL7 (D:\lib\vcpkg\buildtrees\qt5-base\src\qtbase-5.9.2\src\sql\kernel\qsqldatabase.cpp:695, void __cdecl QSqlDatabasePrivate::init(const class QString &))

**Comment by r-englund** [comment]
I've seen this or a similar issue before. Then it was related to the Windows path and the "wrong" Qt being found. This could happen when another application ships its own qt-dll and not including the sqlite3.dll (since they do not need it). 
For me this happens with for example Miktex, during installation/upgrade they put their bin folder in the beginning of the windows Path.  
Check your windows path to make sure your QT installation is the first path. (Note, you have to restart both visual studio and CMake for the changes to apply)

**Comment by TheHugeManatee** [comment]
I don't have any qt installation directly in my PATH as I am working with several versions, so I rely on the qt dlls to be in the binary directory (which vcpkg takes care of).
I don't think it is a problem of my environment being "polluted" by different Qt versions, as the dlls are all located correctly inside the <cmake build>/bin/Debug directory. However, since this is done by vcpkg, not the inviwo build itself, therefore it seems like this is more a bug in their qthelp deployment step and less an inviwo problem.
In any case, maybe it is possible to test for this scenario explicitly and provide an error message that is better to understand (it took me quite a while to get from the exception description to the actual root cause of the missing sqlite3.dll).

**Comment by ras0219-msft** [comment]
This is definitely a vcpkg bug -- we should deploy sqlite3.dll. Let me look into this, and if it looks like it will take more time to fix we can migrate this issue over to https://github.com/Microsoft/vcpkg. Sorry for the trouble, @r-englund!

**Comment by ras0219-msft** [comment]
@TheHugeManatee We should have fixed this issue in package version 5.9.2-5 -- could you confirm with `vcpkg list qt5-base` that you're on that version? If not, please pull the latest master, reinstall the package, and let us know if that fixes the issue :)

**Comment by TheHugeManatee** [comment]
Thanks for the quick investigation - I was indeed on package 5.9.2-3. Upgrading now, will update as soon as the rebuild finishes..

**Comment by TheHugeManatee** [comment]
Works on vcpkg with qt package 5.9.3-5 - problem solved! Thanks everybody!
