### ISSUE TITLE
Mac: INVALID_OPERATION when using ImageGLProcessor

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#322]
Processors based on ImageGLProcessor, for example Image Grayscale, produces invalid operation OpenGL error on line 83:
`utilgl::activateTargetAndCopySource(outport_, inport_, ImageType::ColorOnly);`
which traces to 
line 180 in imagegl.cpp:
`    target->activateBuffer(ImageType::AllLayers);
`
Output from processor is invalid after the error has occurred.

**Steps to reproduce**
Open a workspace including an image source, grayscale and canvas on Mac.

**Environment information**
* Operating System:
Mac OSX High Sierra 10.13.6
Intel Iris Graphics 550

**Comment by ResearchDaniel** [comment]
@martinfalk Any ideas?

**Comment by ResearchDaniel** [comment]
Call stack when loading imagebinary test workspace

#0	0x00000001132f041e in inviwo::getGLErrorString(unsigned int) at /Users/danieljonsson/Documents/inviwo/dev/modules/opengl/src/inviwoopengl.cpp:43
#1	0x00000001132f0b30 in inviwo::LogGLError(char const*, char const*, int) at /Users/danieljonsson/Documents/inviwo/dev/modules/opengl/src/inviwoopengl.cpp:103
#2	0x00000001134032c6 in inviwo::ShaderObject::upload() at /Users/danieljonsson/Documents/inviwo/dev/modules/opengl/src/shader/shaderobject.cpp:288
#3	0x00000001134020d2 in inviwo::ShaderObject::build() at /Users/danieljonsson/Documents/inviwo/dev/modules/opengl/src/shader/shaderobject.cpp:119
#4	0x00000001133bcceb in inviwo::Shader::build() at /Users/danieljonsson/Documents/inviwo/dev/modules/opengl/src/shader/shader.cpp:208
#5	0x000000010a891e85 in inviwo::ImageGLProcessor::initializeResources() at /Users/danieljonsson/Documents/inviwo/dev/modules/basegl/src/processors/imageprocessing/imageglprocessor.cpp:67

**Comment by martinfalk** [comment]
Have you tried checking for GL errors before activating the fbo? You could then also try synchronous GL debugging.
Don't see the connection between the call stack dump and the error message in the first post. What is the error message in case of image binary?

**Comment by ResearchDaniel** [comment]
You are probably right. Could it be caused by the fact that there is no vertex shader specified for ImageGLProcessor?
Adding a vertex shader in ImageGLProcessor seemed to resolve the second issue. Have not tried with the first one but that error could be caused by this one I guess.
`    , shader_({{ShaderType::Vertex, utilgl::findShaderResource("img_texturequad.vert")}, {ShaderType::Fragment, fragmentShader}},
              buildShader ? Shader::Build::Yes : Shader::Build::No)`

**Comment by martinfalk** [comment]
Don't think so. We have many processors just defining a fragment shader. And then a default vertex shader is added. Try increasing the debug level for GL.

https://github.com/inviwo/inviwo/blob/a1faefbe14c37941f5fb9316eba91bcc0f1063d5/modules/opengl/src/shader/shader.cpp#L68-L71

**Comment by ResearchDaniel** [comment]
Apparently one of the constructors do not add a vertex shader (the one used in this case):
```
Shader::Shader(
    const std::vector<std::pair<ShaderType, std::shared_ptr<const ShaderResource>>> &items,
    Build buildShader)
    : id_{glCreateProgram()}, warningLevel_{UniformWarning::Ignore} {
    for (auto &item : items) createAndAddShader(item.first, item.second);

    if (buildShader == Build::Yes) build();
    ShaderManager::getPtr()->registerShader(this);
}
```

**Comment by martinfalk** [comment]
Hm, true. Then it is weird that the GPU driver does not have a default implementation for the missing part, i.e. the vertex shader in this case. Not sure whether I like the idea of automatically adding one in this constructor though. On the other hand, we are doing exactly that in the fragment shader constructor.

**Comment by ResearchDaniel** [comment]
We could throw an exception either in the constructor or before uploading.

**Comment by martinfalk** [comment]
@petersteneteg would it be reasonable to add a default vertex shader?

**Comment by ResearchDaniel** [comment]
From the specification
Page 340 in https://www.khronos.org/registry/OpenGL/specs/gl/glspec44.core.pdf
> If the current vertex stage program object has no vertex shader, or no program
object is current for the vertex stage, the results of programmable vertex processing
are undefined.
