### ISSUE TITLE
Compile Error while accessing Volume with its original data type

### ISSUE THREAD

**Issue by VisComKreiser** [inviwo/inviwo#323]
Hey, I'm currently trying to access a volumes values using its original data type but get a compile error while doing so.
I have tried to do it the same way as in the **volumesubsample.cpp** file, but get the following message:

> binary operator '==' : no operator defined which takes a left-hand operand of type 'ValueType' (or there is no acceptable conversion)

Here are my corresponsing files
[volumemask.zip](https://github.com/inviwo/inviwo/files/2644570/volumemask.zip)

**Comment by JochenJankowai** [comment]
I'm no expert on dispatching by any stretch of the imagination but I think the problem might be that your `refIdx` is always an `int` whereas your `ValueType` could be anything, from `int` to `vec4`. In the latter case, the `operator==` would not be defined.

**Comment by petersteneteg** [comment]
Think jochen is right here...

**Comment by VisComKreiser** [comment]
yes, your guess was right.
in the end the comparison worked with the following:

```
using ValueType = util::PrecsionValueType<decltype(annoVol)>;
using P = typename util::same_extent<ValueType, unsigned int>::type;
if (glm::all(annoValue == P(refIdx))) {
    ...
}
```

`glm::all(...)`  is used to care for a varying number of components
