### ISSUE TITLE
Callback registration of ports

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#34]
Why is the interface for registering callbacks in a port so inconsistent?

- `onChange()` and `onInvalid()` support both, lambda expressions and member functions.
- `onConnect()` and `onDisconnect()` only support lambda expressions

**Comment by r-englund** [comment]
Possible reason: 
onChange/onInvalid was added first, before we had c++11 and lambda support.  We later added support for c++11 and could add the lambda call back to those two methods (The old method was keept for backwards compatibility?). Finally we add the onConnect/Disconnect callbacks and there we only use the lambdas.

**Comment by ResearchDaniel** [comment]
@martinfalk , @r-englund's reasoning is spot on. We did not use c++11 when the first functions  where written

**Comment by r-englund** [comment]
So, what action do we take:
1. Status quo (keep as it is) 
2. add member functions to ´onConnect´ and ´onDisconnect´
3. remove member functions to ´onChange´ and ´onInvalid´

if option 3, my suggestion would be to not completly remove them now, but make it deprecated and remove it in a not to distance future

**Comment by ResearchDaniel** [comment]
Vote: Depreceate old callbacks and remove them after some time

**Comment by martinfalk** [comment]
but then also adding member functions to callbacks, i.e. `CallBackList::addMemberCallback()`, should be deprecated. Same for `removeMemberFunction()`

Does anyone know the runtime overhead of using a lambda expression calling a member func instead of calling the member func directly?

**Comment by r-englund** [comment]
`CallBackList::addMemberFunction` actually creates a lambda, so my guess it that the lambda is faster

**Comment by petersteneteg** [comment]
The lambda is usually inlined unless you put it in a std:: function which we usually do for callbacks like this...

**Comment by martinfalk** [comment]
What about `BaseModuleCallback` in modulecallback.h?
There, only member functions are used.

**Comment by petersteneteg** [comment]
The modulecallbacks need a rewrite, the concept is quite cool, but the implementation should be a bit more general I think.

**Comment by martinfalk** [comment]
Deprecation warnings are in place. Member callbacks are still used in some places, e.g. SyntaxHighlighter. Requires RAII before they can be removed.

Closing this issue for now.
