### ISSUE TITLE
Surface Exraction Processor fails for GL volumes

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#348]
The surface extraction processor fails to extract surfaces for GL volumes. 
It fails to download the volume data from the GPU when the worker thread asks for a ram representation. 

A quickfix that works for me is to add a `vol->getRepresentation<VolumeRAM>();` to the `SurfaceExtraction::process`.

**Comment by r-englund** [comment]
How do I use a workerthread to download from GL to RAM? Do I need to enable a local gl context or something?

**Comment by petersteneteg** [comment]
Yes, Rendercontext::activateLocalRenderContext()

**Comment by r-englund** [comment]
Nice, that works. Question is where I should put it, a few possible places comes to mind
1. In the Surface Extraction processor, in the enqueued callback before calling the marching method
2. In the marching util functions
3. in ´VolumeGL2RAMConverter::update(...)´ and probably also `VolumeGL2RAMConverter::createFrom(...)
4. in `Texture::download`

If we go with 1. than we might have the same issue in other processors/util functions. If we go with 4, we also fix this for all processors/util functions and also images (if it is an issue there). But we might activate the context more times than necessary

**Comment by petersteneteg** [comment]
following previous example would be number 1...

**Comment by r-englund** [comment]
> 
> 
> following previous example would be number 1...

What examples?

**Comment by petersteneteg** [comment]
```
void VolumeRaycaster::process() {
    if (volumePort_.isChanged()) {
        auto newVolume = volumePort_.getData();

        if (newVolume->hasRepresentation<VolumeGL>()) {
            loadedVolume_ = newVolume;
        } else {
            dispatchPool([this, newVolume]() {
                RenderContext::getPtr()->activateLocalRenderContext();
                newVolume->getRep<kind::GL>();
                glFinish();
                dispatchFront([this, newVolume]() {
                    loadedVolume_ = newVolume;
                    invalidate(InvalidationLevel::InvalidOutput);
                });
            });
        }
    }
    ...
```

**Comment by r-englund** [comment]
For me it feels very strange to add `RenderContext::getPtr()->activateLocalRenderContext();` to the SurfaceExctractionProcessor since it is only CPU code. It feels odd that the processor developer needs to add this since Inviwo might have GPU representations behind the scene.
