### ISSUE TITLE
Tool Tip Positions are wrong when using SeperateImageSize

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#357]
Seems like it uses absolute pixel coordinates to set the location of the tooltip. (The tooltip is twice as far away from the top-left corner of the canvas than the mouse)

**Comment by r-englund** [comment]
![image](https://user-images.githubusercontent.com/534670/51241318-d532e680-197d-11e9-89ea-b0f211a87613.png)

**Comment by petersteneteg** [comment]
can not reproduce

**Comment by r-englund** [comment]
Me neither, guess it has been fixed
