### ISSUE TITLE
Missing markdown and py-gfm python modules fail build

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#363]
I think that the hard requirement on these two modules are a bit too much. Is it possible to just leave the changelog empty in the Get started screen? Took me 10 minutes to install them due to various (admin) issues.
Alternatively install the packages automatically. Btw, the hints about how to install them did not work in my case. 

They should be 
```
python -m pip install markdown py-gfm
```
instead of 
`python pip3 install markdown [py-gfm`

**Comment by martinfalk** [comment]
The idea is that the conversion script dies silently without writing anything. The build process should (which it doesn't at the moment, working on a fix). In addition, Visual Studio is too smart. It detects `Error:` in the output and flags it as error in the list. The welcome widget already has a fall-back in case the file does not exist and the repository contains a up-to-date html version of changelog. The script is supposed to update that html file if necessary, i.e. CHANGELOG.md has changed.

Typo addressed in c8ddcd6.
In most python installations (including anaconda), pip comes also as stand-alone tool. That is `pip install markdown py-gfm` can be called directly.
