### ISSUE TITLE
Tiff import

### ISSUE THREAD

**Issue by proudot** [inviwo/inviwo#389]
Hi, Thanks for releasing this very promising software!

I could not find a way import a classic multiple page tiff stack.  Any pointers ? 

I am also interested in loading a sequence of volume where each time point is a tiff stack. 

Thanks!

**Comment by martinfalk** [comment]
We actually have two implementations at hand which are unfortunately not yet public. We are working on it to make them available by next week.

**Comment by proudot** [comment]
Alright, thanks ! Looking forward :).

**Comment by petersteneteg** [comment]
There is now a tiffstack datareader that will be used by the volume source, and a image stack to volume processor, for file based stackes...

**Comment by proudot** [comment]
Thanks ! Looking forward to the new build :).
