### ISSUE TITLE
Compile error with < Qt 5.11

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#398]
QFontMetrics::horizontalAdvance is not introduced until Qt 5.11. Hence, compile errors occur for versions less than that.
https://doc.qt.io/qt-5/qfontmetrics.html#horizontalAdvance

Compile error 
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'horizontalAdvance': is not a member of 'QFontMetrics'	inviwo-module-qtwidgets	inviwo\dev\modules\qtwidgets\src\numberlineedit.cpp	102	

Came from commit b4c9511071631a2bf2dc7aad2d9522d4395fa2a1

**Comment by ResearchDaniel** [comment]
We need to test with Qt 5.6 on jenkins

**Comment by petersteneteg** [comment]
maybe it's time to update the qt requirement...
