### ISSUE TITLE
No warning/info when file in DataSource processor is not found

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#403]
The datasource processor (baseclass for MeshSource, Image Source, ...) is overloading the isReady call and is only ready if the file exists on disks. This is all good and by design but:
When this is happens in a regression test, the network is not evaluated since the source processor is not ready, but the regression test still outputs an image (empty image) and no reason why is shown (example: http://jenkins.inviwo.org:8080/job/modules/job/OpenMeshModule/Regression/report-2019-02-08T14_20_36.html).

**Comment by petersteneteg** [comment]
Suggestions?

**Comment by petersteneteg** [comment]
Logging seems quite verbose here i think...

**Comment by r-englund** [comment]
I agree that Logging when checking isReady might be to verbose. One option would be to print a warning for missing file while deserializing the fileproperty (https://github.com/inviwo/inviwo/blob/master/src/core/properties/fileproperty.cpp#L152-L158). Then you would get a warning if the file is missing while loading the network. 

Might also be good to print a warning if the network is not ready / has not been evaluated when saving the screenshots for the regression tests

**Comment by martinfalk** [comment]
I'm with @r-englund on this one. In my opinion there should even be a `LogError` when the file_ property changes and the file does not exist.

https://github.com/inviwo/inviwo/blob/9b8a06e6251398dbb775564da5d9293e1c83c669/modules/base/src/processors/volumesource.cpp#L85-L86

**Comment by martinfalk** [comment]
Also second @r-englund other suggestion for checking that the network has been evaluated at least once.

**Comment by r-englund** [comment]
Warning when saving non-ready canvases is easily be done https://github.com/inviwo/inviwo/commit/e7c01e7760f3f42adc03ad892de1fc4faa542760

**Comment by r-englund** [comment]
> I'm with @r-englund on this one. In my opinion there should even be a `LogError` when the file_ property changes and the file does not exist.

I agree, LogError or LogWarn. Unless it may give false negatives while editing.

**Comment by r-englund** [comment]
> 
> 
> > I'm with @r-englund on this one. In my opinion there should even be a `LogError` when the file_ property changes and the file does not exist.
> 
> I agree, LogError or LogWarn. Unless it may give false negatives while editing.

Or maybe not, while editing manually the widget shows an icon if the file is missing
![image](https://user-images.githubusercontent.com/534670/52487814-c0cdbc80-2bbe-11e9-950c-2e371c520493.png)

**Comment by martinfalk** [comment]
But there still needs to be some feedback! At least after deserialization. A processor might also "hard-code" some path for a file property, which is, e.g. not shipped. Then the small icon also does not help during regression testing.

**Comment by petersteneteg** [comment]
the saveCanvas should print an error / fail if the canvas processor is not ready...
