### ISSUE TITLE
Inviwo api doc extremly outdated 

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#438]
The link to the API doc in our README.md has not been updated in a very long time. https://inviwo.org/inviwo/doc/
This should maybe be done by Jenkins on each merge to always be up to date

**Comment by r-englund** [comment]
#85

**Comment by xeTaiz** [comment]
I wanna throw in a thought that I had earlier on that exact topic: How about a sphinx style docu? 
There's a converter from doxygen ([exhale](https://exhale.readthedocs.io/en/latest/#))
Might be really nice, especially if we can make a sphinx docu for the python stuff as well?


It does not work out of the box tho. There seem to be problems with parsing the `IVW_CORE_API ` flags we have in front of every class

**Comment by r-englund** [comment]
I am pro Sphinx/exhale if we can set it up nicely. One thing that is nice with doxygen is that you need only doxygen and nothing else (no other dependencies) to generate the documentation.
