### ISSUE TITLE
The download source link on webpage does not contain the inviwo source code

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#439]
The source code download button on https://inviwo.org/#downloads does not download a zip with the Inviwo source code but the build-zip (same as the Windows-portable).

**Comment by r-englund** [comment]
This is true for the link under all three "tabs" (Windows, MacOs, Linux)

**Comment by k1tesurfen** [comment]
I fixed the downloads for all platforms ([commit](https://github.com/inviwo/inviwo.github.io/commit/f19cd53c9413747a589608de170102e0555a9e38)). I hope this is the correct one now. @r-englund unfortunately I only have access to the inviwo-github-page repository, so I cannot close this issue or assign myself. For future website issues please open them on the webpage repository.

**Comment by petersteneteg** [comment]
you should have the rights now

**Comment by k1tesurfen** [comment]
> I fixed the downloads for all platforms ([commit](https://github.com/inviwo/inviwo.github.io/commit/f19cd53c9413747a589608de170102e0555a9e38)). I hope this is the correct one now. @r-englund unfortunately I only have access to the inviwo-github-page repository, so I cannot close this issue or assign myself. For future website issues please open them on the webpage repository.

As mentioned the links are now correct.
