### ISSUE TITLE
 the .inv save from example workspace boron.inv open failed.

### ISSUE THREAD

**Issue by ZYV037** [inviwo/inviwo#447]
1. open example workspace boron.inv.
2. volume resource modify to my "tunnel_drill.raw." and set.
[tunnel_drill.zip](https://github.com/inviwo/inviwo/files/2934904/tunnel_drill.zip)
![1](https://user-images.githubusercontent.com/11004657/53862260-c1247080-4021-11e9-97ff-60e2b1118f8f.png)

3. save workspace to boron.inv
4. reopen boron.inv.
![2](https://user-images.githubusercontent.com/11004657/53862279-cbdf0580-4021-11e9-8774-f30e4df5bc82.png)

![3](https://user-images.githubusercontent.com/11004657/53873251-e8d40280-403a-11e9-84b8-92bcb7b8be37.png)

**Environment information**
* Operating System: Win10
* Compiler/IDE: vs2017
* QT Version:5.12.1
* Python version: 3.7

**Comment by petersteneteg** [comment]
I was able to reproduce this, will investigate further

**Comment by petersteneteg** [comment]
Changing 
```
bool RawDataReaderDialogQt::show() {
    return QDialog::exec() == QDialog::Accepted;
}
```
to 
```
bool RawDataReaderDialogQt::show() {
    auto res = QDialog::exec();
    RenderContext::getPtr()->activateDefaultRenderContext();
    return res == QDialog::Accepted;
}
```
will fix the issue...

Problem is that the qt dialog steals the active opengl context :(

**Comment by ZYV037** [comment]
I'll check tomorrow.

**Comment by ZYV037** [comment]
fixed.
