### ISSUE TITLE
[volume source] not support Data format: unsigned int, float  

### ISSUE THREAD

**Issue by ZYV037** [inviwo/inviwo#448]
1. open example workspace boron.inv
2. volume resource select 1.raw. set data format.
[1.zip](https://github.com/inviwo/inviwo/files/2940708/1.zip)
![6or sy_i i3t_bql0tw2 co](https://user-images.githubusercontent.com/11004657/53950850-176bdf00-4108-11e9-95de-b291ef3705eb.png)
3. adjust Volume Raycaster TF & Isovalues.

![2](https://user-images.githubusercontent.com/11004657/53950632-90b70200-4107-11e9-815d-4088cc493ef0.jpg)

4. I can't get any color.
-------------------------------------------------------------------------------
Than I use [unsigned short] instead. I scaling the data by value /=1000000.

[2.zip](https://github.com/inviwo/inviwo/files/2940758/2.zip)
![1](https://user-images.githubusercontent.com/11004657/53950747-d247ad00-4107-11e9-9e72-7a0fbb5160fb.jpg)
It's normal.
--------------------------------------------------------------------------------
I think something is wrong with datatype used by volume source.

**Environment information**
* Operating System: Win10
* Compiler/IDE:vs2017
* QT Version:5.1.12
* Python version: 3.7

**Comment by petersteneteg** [comment]
The volume should be fine. It's rather that opengl needs a special sampler to sample 32bit interger data. And our standard raycaster does not support that.

**Comment by petersteneteg** [comment]
float data should be fine, did you have any issues with that?

**Comment by ZYV037** [comment]
nope.I'll try the float data and report.
