### ISSUE TITLE
The default demo (boron.inv) fails bcos the volume data path is wrong

### ISSUE THREAD

**Issue by mmmovania** [inviwo/inviwo#451]
Thank you for reporting your issue, please ensure the following before submitting a new issue:
* Is your issue new? Please search the issue system to see if someone else have reported the same issue
* Have more than one issue/bug to report? Create one separate issue for each issue/bug.

Please fill out all applicable fields bellow:

**Issue**
The default demo (boron.inv) fails because the volume data path is wrong

**Steps to reproduce**

Install the latest inviwo installation and run it. The default demo fails to load as the path of the boron.dat volume data is wrong. Fix is to change the path to the location of the data folder under installation folder of inviwo.

**Environment information**
* Operating System: Windows 8.1 64 bit
* Compiler/IDE: using prebuild binaries
* QT Version:using prebuild binaries
* Python version: using prebuild binaries

If possible, copy/paste the Inviwo log into the issue. If Inviwo is crashing before it is possible to attach a log you can start Inviwo with the -c flag to log to console or -l filename.html to log to a file.

**Comment by petersteneteg** [comment]
Think this is fixed in the master on github

**Comment by mmmovania** [comment]
Great thanks :)
