### ISSUE TITLE
PortInspectors does not work if there a background threads running. 

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#459]
PortInspectors does not work when having one or more background threads running in inviwo. 
In portinspector.cpp we create a new network for the port inspector, when this network is destroyed its destructor calls 'clear()' which calls 'application_->waitForPool();'.
Hence, we will not get a port inspector until the background threads are done even when the threads are not at all related to what is shown in the port inspectors. 

https://github.com/inviwo/inviwo/blob/4cf9880d8d88e78db01c301d4b36b514c8533ce3/src/core/ports/portinspector.cpp#L54

https://github.com/inviwo/inviwo/blob/4cf9880d8d88e78db01c301d4b36b514c8533ce3/src/core/network/processornetwork.cpp#L54-L57

https://github.com/inviwo/inviwo/blob/4cf9880d8d88e78db01c301d4b36b514c8533ce3/src/core/network/processornetwork.cpp#L283-L287

**Comment by petersteneteg** [comment]
Wait for pool should be removed from the network... but then all background jobs have to make sure that they don't use deleted processors, which is nothing new, but very hard to enforce...

**Comment by martinfalk** [comment]
What happens then if the port inspector has processors with background computations?

**Comment by petersteneteg** [comment]
Deadlock?
