### ISSUE TITLE
Wrong required CMake version

### ISSUE THREAD

**Issue by Lecrapouille** [inviwo/inviwo#462]
In https://github.com/inviwo/inviwo/wiki/Building-Inviwo-on-Linux in Required packages 
CMake 3.2 is needed but in fact CMake 3.8 or higher is required.

**Comment by r-englund** [comment]
Did it work for you with CMake 3.8? 
Anyway, I updated the wiki page to say 3.8 instead of 3.2, but we should also update it on other places where needed. Though i am not sure which version is needed and I think it is different on different platforms. @petersteneteg you should now better?

**Comment by ResearchDaniel** [comment]
I think that even 3.11/3.12 might be required in some cases

**Comment by r-englund** [comment]
Doing a search for `cmake_minimum_required` it says 3.2 but in the main CMakeLists, 3.8 in some of the meta modules and 3.13 for `fmt` 
https://github.com/inviwo/inviwo/search?q=cmake_minimum_required&unscoped_q=cmake_minimum_required

**Comment by r-englund** [comment]
> 
> 
> I think that even 3.11/3.12 might be required in some cases

I have 3.12 on my win machine at home (and it works)

**Comment by petersteneteg** [comment]
3.13 is only for the installing... 3.8 should work I think.

**Comment by r-englund** [comment]
When I got back from work a few weeks before christmas I had to update cmake to be able to build Inviwo. Had 3.11.4 installed before and updated to 3.13.2

**Comment by petersteneteg** [comment]
Did you have ivw_package ensbled?

**Comment by r-englund** [comment]
Probably

**Comment by Lecrapouille** [comment]
@r-englund Sorry I did not give all information.

I have an up-to-date debian 9.8:
```
lsb_release -da
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.8 (stretch)
Release:	9.8
Codename:	stretch
```

So my cmake version is 3.7.2:
```
cmake --version
cmake version 3.7.2
```
When doing cmake on your project, I have the error:
```
CMake Error at ext/json/CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.8 or higher is required.  You are running version 3.7.2
```

So I have to compile a cmake manually

**Comment by Lecrapouille** [comment]
@r-englund 

It seems this package is also needed
```
sudo apt-get install libqt5svg5-dev
```

You are right for cmake >= 3.13 ! I had to do that:
```
sudo apt remove --purge --auto-remove cmake
```
+ downloaded cmake-3.14 (https://cmake.org/download/) + compiled and cmake passed :)

I tried to compile but I got errors with glm (libglm-dev version installed on debian is 0.9.8.3-3). I compiled a 0.9.9.4 but still got compilation errors:
```
In file included from /home/qq/inviwo/include/inviwo/core/util/glm.h:51:0,
                 from /home/qq/inviwo/include/inviwo/core/common/inviwo.h:64,
                 from /home/qq/inviwo/include/inviwo/core/common/inviwomodule.h:33,
                 from /home/qq/inviwo/include/inviwo/core/common/inviwocore.h:34,
                 from /home/qq/inviwo/src/core/common/inviwocore.cpp:30:
/home/qq/inviwo/ext/glm/glm/glm/gtx/hash.hpp:72:14: error: ‘tquat’ is not a member of ‘glm’
  struct hash<glm::tquat<T,Q>>
              ^~~
/home/qq/inviwo/ext/glm/glm/glm/gtx/hash.hpp:72:27: error: wrong number of template arguments (2, should be 1)
  struct hash<glm::tquat<T,Q>>
```

to be continued :)

**Comment by r-englund** [comment]
Inviwo includes its own version of glm, so what you have installed on your machine should not matter. What I think is happening is that your compiler is compiling the template-function at hash.hpp:72. The function it self is probably never used anywhere in our codebase and since some compilers (I guess all the once we are using) skips compiling those function we haven't gotten that error yet. 
Try adding `#include <glm/gtc/quaternion.hpp>` to `/home/qq/inviwo/include/inviwo/core/util/glm.h`  around line 50 (before the include of hash.hpp) and let me know if that helps

**Comment by Lecrapouille** [comment]
Nop this did not help :( Maybe I need to pass some g++ flags ? I'll investigate it sooner, I cannot right now.

**Comment by petersteneteg** [comment]
What gcc version are you using, I would rekommend at least 7.3 have not tested on gcc 6.5 for some time...

**Comment by Lecrapouille** [comment]
@petersteneteg indeed I did not checked my gcc version first. On Debian 9.5 it's gcc 6 so I tried to download gcc 7.4 (from memory) but it failed on other part of the code. I'm sorry but my main computer just passed away so I cannot help you more for the moment :(

**Comment by martinfalk** [comment]
@Lecrapouille we did some clean-up and fixing prior the latest release. Inviwo should now compile with the later versions of gcc 6 (successfully tested with gcc 6.5).

**Comment by Lecrapouille** [comment]
@martinfalk thanks and sorry for the delay, I did not try back. I have the correct error message while since this time Debian has updated to 9.9 but did not upgrade their CMake :)
```
CMake Error at CMakeLists.txt:30 (cmake_minimum_required):
  CMake 3.12.0 or higher is required.  You are running version 3.7.2
```
