### ISSUE TITLE
Cannot open include file: 'b44ExpLogTable.h'

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#463]
Occasionally after running cmake (for example after a pull/rebase) i get the following error. I then have to re run cmake again in order for it to go away. 
```
Error	C1083	Cannot open include file: 'b44ExpLogTable.h': No such file or directory	IlmImf	E:\github-master-repo\inviwo\inviwo-src\modules\cimg\ext\openexr\openexr\OpenEXR\IlmImf\ImfB44Compressor.cpp	134	
``` 
It seems like the project `ext/openexr/b44ExpLogTable` is not created the first time.

**Comment by r-englund** [comment]
Before rerunning cmake the solution had 110 projects and after 112. So I guess it added the ´b44ExpLogTable´ module and another one

**Comment by petersteneteg** [comment]
Think cmake creates a target to generate that file, the next time when the file exists the target is removed.... some one does not understand cmake....

**Comment by r-englund** [comment]
Quite sure this has been fixed
