### ISSUE TITLE
BasisProperty ignores override flag

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#473]
The `BasisProperty` ignores the override flag when it is updated for a new entity, e.g. when loading a different dataset/volume. Unchecking and checking "Override" correctly reapplies the override values.

**Comment by petersteneteg** [comment]
Im not able to reproduce this. can you give more detailed steps?

**Comment by martinfalk** [comment]
Hm, seems to be fixed in the meantime. 

**Steps to reproduce**
1. open boron network
2. in `Volume Source` disable `Update on new data`, check `Override`
3. set basis to something arbitrary like 1,0,0, 0,2,0, 0,0,4
4. load different volume like bismuth 

Before, the basis of the second dataset would be initially used.
