### ISSUE TITLE
Clock, ClockGL, and ClockCL should have similar interface

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#48]
At the moment the interfaces of `Clock` and `ClockGL` differ. The header file `clockcl.h` does not even provide a `ClockCL`.

e.g. `Clock::tick()` vs. `ClockGL::stop()`

`getElapsedTime()` should potentially return a std::duration.

**Comment by ResearchDaniel** [comment]
Second that, we should probably provide an abstract class for the clock(s)
