### ISSUE TITLE
Regresion report scripts does not run

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#481]
The scripts included in the regression report HTML does not run (test in Firefox, chrome and edge).  Hence all divs are unfolded and can't be folded which makes it quite tedious to find the failed tests. 
Related to [this](https://stackoverflow.com/a/34372607)? 

Error reported by chrome: 
```
Blocked script execution in 'http://jenkins.inviwo.org:8080/job/inviwo/job/feature%252Fvarious/Regression/report.html' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

**Comment by petersteneteg** [comment]
This is a known CSP issue. Did someone reboot jenkins?

**Comment by r-englund** [comment]
Yes, we had to reboot it since a we manage to get the regression tests to end up in an infinite loop and no one of our users has permision to abort jenkins jobs. @martinfalk will know more
