### ISSUE TITLE
Parallel coordinates property link error

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#484]
**Issue**
Error is produced when loading old workspace where "colors" property in parallel coordinates is linked.
> Could not create Property Link from:
>    Property 'colors' of class 'org.inviwo.CompositeProperty' in
>    Processor 'Parallel Coordinates' of class 'org.inviwo.ParallelCoordinates'
> to
>    Property 'colors' of class 'org.inviwo.CompositeProperty' in
>    Processor 'Parallel Coordinates2' of class 'org.inviwo.ParallelCoordinates'
> Source and destination properties not found.

**Steps to reproduce**
Load an old version where colors property in parallel coordinates is linked.

I guess the property was renamed?

**Comment by petersteneteg** [comment]
That composite is removed. I will not fix it. Way to much work just for some cosmetic.
