### ISSUE TITLE
Linking broken for OrdinalProperty

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#494]
Linked ordinal properties are not synchronized **if only the maximum** of one property is changed (`OrdinalProperty::setMax()`).

Changing the value afterward also updates the new bounds.

**Comment by petersteneteg** [comment]
Problem is here, https://github.com/inviwo/inviwo/blob/88e481a0b0925602a3c82e7c8e57885277984269/include/inviwo/core/properties/ordinalproperty.h#L207

TenplateProperty will only call propertyModified if the value also changed...  solution: don't call the base class but reimplement...
