### ISSUE TITLE
Better way of setting IVW_EXTERNAL_MODULES

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#496]
Right now we use a semicolon separated list to specify external modules (`IVW_EXTERNAL_MODULES`), which is getting to be a bit tedious when having a few folders to add.

An option could be to use several cmake variables instead, one for each folder, call them on the form `IVW_EXTERNAL_MODULE_N` and in cmake loop over them using something like:
```cmake
foreach(i RANGE 1 100)
    if(IVW_EXTERNAL_MODULE_${i})
        # Add ${IVW_EXTERNAL_MODULE_${i}} to list of external modules 
    endif()
endforeach()
```  

# PROS
 * Can use variable with type path instead of string, which lets the user use a dialog to choose the path
* Easiser for the "user" to work with in cmake-gui

# CONS
* Needs a for loop over an arbitrary range (1 -> 100 in the example) or force the indices to be incremental. If forced incremental and one removes one or more of the variables one has to change all with higher index. 
* Needs to manually add variables. (We could by default add 1-10 as empty paths, and also add more when/if 1-10 is being used)

**Comment by r-englund** [comment]
For example, when using [inviwo/modules](https://github.com/inviwo/modules/) one need to add up to 6 folders 
Edit: its 7, not 6

**Comment by martinfalk** [comment]
Would it be possible from CMake side when running CMake to add another "empty" option for module paths after the existing ones? That would make adding them a bit easier.

**Comment by martinfalk** [comment]
I like the idea of that. In particular with the folder dialog.

**Comment by r-englund** [comment]
> 
> 
> Would it be possible from CMake side when running CMake to add another "empty" option for module paths after the existing ones? That would make adding them a bit easier.

Yes, we should a few by default, and we could add a few more when running out. What I don't want though, is to add one, run cmake, add another, run cmake and so on. For example: Add 10 on a dry run and make sure there is always at least 3 empty

**Comment by martinfalk** [comment]
@r-englund that was what I had in mind as well.

**Comment by petersteneteg** [comment]
I would generally want to avoid adding even more complexity to our cmake stuff...

**Comment by petersteneteg** [comment]
Think having multiple options of how to add modules to inviwo will make it more confusing to said "user". I also find adding options to cmake dynamically quite strange. We want to have our cmake stuff as declarative as possible. It not supposed to be used as an interactive gui.
