### ISSUE TITLE
automatically set project folders for modules

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#513]
Many of us have a lot of enabled modules when building our projects in Inviwo, this makes it tedious to browse the projects (in the solution explorer in MSVC). 

I think we, at some point, discussed this at some Inviwo meeting with the suggestion to add each module to a project folder in some smart way. I did some experimenting and got something working (https://github.com/inviwo/inviwo/commit/d19878c64e492b0033ccb49cf0a2c4694caa3571). This places each module in a nice tree structure based on where the modules is located on disc: 
![image](https://user-images.githubusercontent.com/534670/57376284-ece9e100-719f-11e9-896f-addb3ea6e258.png)
IMO that is much nicer then having a long list like this: 
![image](https://user-images.githubusercontent.com/534670/57376491-65e93880-71a0-11e9-9deb-4d779d5e6ec9.png)

**Comment by martinfalk** [comment]
I second that idea. Much nicer and better organization.

**Comment by petersteneteg** [comment]
This needs a more stable way of naming the groups

**Comment by r-englund** [comment]
> 
> 
> This needs a more stable way of naming the groups

Any suggestions?

**Comment by petersteneteg** [comment]
If I had a easy way I would have done it long ago... So far the only way I have thought of is to add some file next to all the modules with metadata.

**Comment by petersteneteg** [comment]
Such meta data could also be useful in a few other places

**Comment by martinfalk** [comment]
I agree with the idea of metadata. But I am afraid that there needs to be some kind of fall-back mechanism. Maybe not for newly created modules where could automatically place a file but for existing ones (potentially external).
