### ISSUE TITLE
Packing Inviwo fails due to OpenEXR

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#515]
Packing of Inviwo fails due to OpenEXR. 
Commenting out the their calls to INSTALL in their cmake files removed the error ( breaks other stuff) 
https://github.com/inviwo/openexr/blob/master/OpenEXR/CMakeLists.txt#L212-L250
https://github.com/inviwo/openexr/blob/master/OpenEXR/IlmImfUtil/CMakeLists.txt#L78-L99

**Comment by r-englund** [comment]
When packing worked (after commenting out the lines I mentioned). Inviwo fails to start  because IlmImf-2_3.dll was not found the other IlmImf dll's are there. 
When adding IlmImf-2_3.dll manually to the unzipped folder Inviwo starts

**Comment by ResearchDaniel** [comment]
I think that this has been fixed. We now have CI testing of installer.
