### ISSUE TITLE
Incorrect canvas size when reloading network

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#536]
# Step to reproduce
1. Load the boron network
2. change the canvas size (to for example 300x300)
3. Reload the network, the canvas is now 16x39 pixels smaller (284x261)

**Comment by martinfalk** [comment]
That almost sounds like the window decoration size is taken into consideration...

**Comment by r-englund** [comment]
QT issue? I have 5.12.3

**Comment by r-englund** [comment]
Could be a Qt issue, tested with 5.9.0 and there it does not seem to be a probelm

**Comment by martinfalk** [comment]
If it is a Qt issue, it could be related to our workaround for positioning widgets while considering window decoration on Windows.

See
https://github.com/inviwo/inviwo/blob/88e481a0b0925602a3c82e7c8e57885277984269/modules/qtwidgets/src/inviwoqtutils.cpp#L362-L379

**Comment by martinfalk** [comment]
Suggestion: create a plain QWidget, set its size/geometry prior showing, then print the size and position.

**Comment by r-englund** [comment]
Can't reproduce it anymore....

**Comment by martinfalk** [comment]
Closing the issue for now.

**Comment by r-englund** [comment]
This happens when I save a canvas that is not on the same monitor as the MainWindow

**Comment by r-englund** [comment]
> 
> 
> This happens when I save a canvas that is not on the same monitor as the MainWindow

It is two of the same monitor (brand, model and size) and has same resulution and scaling (1920x1200, 100% aka no scaling)

**Comment by r-englund** [comment]
When saving with: 
Monitor 1: 1920x1200 100%, InviwoMainWindow
Monitor 2: 1920x1200 100% A canvas that is 600x600
and reloading the canvas get size 584x561

When saving with: 
Monitor 1: 1920x1200 100%, InviwoMainWindow
Monitor 2: 1920x1200 125% A canvas that is 600x600
and reloading the canvas get size 750x750


When moving a canvas between two monitors with different scaling the size of the canvas changes
from 100%->125% the canvas changes from 600x600 to 754x760
from 100%->150% the canvas changes from 600x600 to 908x920

**Comment by r-englund** [comment]
https://www.youtube.com/watch?v=zV1Msi6-3r0

**Comment by r-englund** [comment]
After some investigation, I have found a fix but not really the actual causation.  
In `canvasprocessorwidgetqt.cpp`  we have the following code: 
```c++
#if QT_VERSION > QT_VERSION_CHECK(5, 6, 0)
        // Trigger both resize event and move event by showing and hiding the widget
        // in order to set the correct, i.e. the de-serialized, size and position.
        //
        // Otherwise, a spontaneous event will be triggered which will set the widget
        // to its "initial" size of 160 by 160 at (0, 0) thereby overwriting our values.
        util::KeepTrueWhileInScope ignore(&ignoreEvents_);
        QWidget::setVisible(true);
        QWidget::setVisible(false);
#endif  // QT_VERSION
```
if inspecting the `QWidget::size()` before and after the `QWidget::setVisible(true);` it has the correct size before and incorrect after. Inserting `QWidget::resize(QSize(dim.x, dim.y));` directly after we set visible to true will fix my issue and the canvas will have the correct size when loading the network.
