### ISSUE TITLE
Compiling on Visual Studio 2015 fails since half a year, should we deprecate it?

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#538]
Since quite some time back (Jan 2019 #374) compiling Inviwo for VS 2015 has been failing. 
In various places (e.g readme, building docs on the wiki) it states that we do support VS 2015. 

We should either update the documentation to say 2017 instead of 2015 or fix the compile issues on 2015. 
Right now `ImageStackToVolumeSource` and `ShaderObject` fails to compile. Also, some of the `unittest` fails to compile. 

I am quite sure it has been broken since at least Dec 2018 (8d887fdbe167b4fcd930d3435608774067703b6c) and since only one issue (#374) has been reported, I think it is safe to assume no-one still uses 2015 to compile Inviwo and we can update the requirement to 2017

**Comment by petersteneteg** [comment]
Yes, we should probably specify witch version of 17 also... preferably the latest point release since we are going to require c++17 soon...

**Comment by ResearchDaniel** [comment]
Agree, we should change the instructions and move to 17
