### ISSUE TITLE
PythonProcessor: import of local python script fails

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#551]
When importing a local python script (here `vtkutility.py`), Inviwo reports an error that there is no such module and there is no processor `vtkutiliy`.

### The python script of the processor:
```python
# Name: VtkImageData 

import inviwopy as ivw

import numpy

import vtkutility

class VtkImageData(ivw.Processor):
    def __init__(self, id, name):
    ...
```

### Inviwo error message
```
**PythonProcessorFolderObserver**	Failed to load processor VtkImageData from script: C:/dev/inviwo/inviwo/modules/python3/processors/vtkimagedata.py.
ModuleNotFoundError: No module named 'vtkutility'
At:
  <string>(8): <module>

**PythonProcessorFolderObserver**	Failed to find python processor "vtkutility" in pythons object register
```

**Comment by petersteneteg** [comment]
What do you mean by local? Is it in the python path?

**Comment by petersteneteg** [comment]
The python processor dir is not in the path... Not sure if it should be... should probably not put any other scripts in that dir anyway...

**Comment by martinfalk** [comment]
By local I mean in the same directory as the python processor script, i.e. `modules/python3/processors`.

**Comment by petersteneteg** [comment]
Not sure what you want me to do about this?

**Comment by petersteneteg** [comment]
added pyutil::ModulePath to make it easy to add script paths.
