### ISSUE TITLE
PythonProcessor: Access violation on exist

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#552]
Access violation on Windows/VS2017 when exiting Inviwo

Using a python processor with two properties (callstack below):
```
import inviwopy
from inviwopy.properties import ButtonProperty

import numpy

"""
The PythonScriptProcessor will run this script on construction and whenever this
it changes. Hence one needs to take care not to add ports and properties multiple times.
The PythonScriptProcessor is exposed as the local variable 'self'.
"""

if not "openVolumeFolderFileDialog" in self.properties:
	self.addProperty(ButtonProperty("openVolumeFolderFileDialog", "Open Volume Folder File Dialog"))

if not "openClinicalParametersSheetFileDialog" in self.properties:
	self.addProperty(ButtonProperty("openClinicalParametersSheetFileDialog", "Open Clinical Parameters Sheet File Dialog"))

def process(self):
	"""
	The PythonScriptProcessor will call this process function whenever the processor process 
	function is called. The argument 'self' represents the PythonScriptProcessor.
	"""
	if self.properties.openVolumeFolderFileDialog.isModified:
		inviwopy.app.network.Volume4DSequenceSource.folder.requestFile()
	if self.properties.openClinicalParametersSheetFileDialog.isModified:
		inviwopy.app.network.CSVSource2.inputFile_.requestFile() 
	pass

def initializeResources(self):
	pass

# Tell the PythonScriptProcessor about the 'initializeResources' function we want to use
self.setInitializeResources(initializeResources)

# Tell the PythonScriptProcessor about the 'process' function we want to use
self.setProcess(process)
```

>	[Inline Frame] inviwopy.cp36-win_amd64.pyd!inviwo::detail::PropertyDeleter<inviwo::ButtonProperty>::operator()(inviwo::ButtonProperty *) Line 91	C++
 	[Inline Frame] inviwopy.cp36-win_amd64.pyd!std::unique_ptr<inviwo::ButtonProperty,inviwo::detail::PropertyDeleter<inviwo::ButtonProperty> >::{dtor}() Line 2296	C++
 	inviwopy.cp36-win_amd64.pyd!pybind11::class_<inviwo::ButtonProperty,inviwo::Property,std::unique_ptr<inviwo::ButtonProperty,inviwo::detail::PropertyDeleter<inviwo::ButtonProperty> > >::dealloc(pybind11::detail::value_and_holder & v_h) Line 1341	C++
 	inviwopy.cp36-win_amd64.pyd!pybind11::detail::clear_instance(_object * self) Line 327	C++
 	inviwopy.cp36-win_amd64.pyd!pybind11_object_dealloc(_object * self) Line 349	C++
 	[Inline Frame] inviwopy.cp36-win_amd64.pyd!pybind11::detail::clear_patients(_object * self) Line 309	C++
 	inviwopy.cp36-win_amd64.pyd!pybind11::detail::clear_instance(_object * self) Line 341	C++
 	inviwopy.cp36-win_amd64.pyd!pybind11_object_dealloc(_object * self) Line 349	C++
 	[External Code]	
 	[Inline Frame] inviwo-module-python3.dll!pybind11::detail::accessor_policies::generic_item::set(pybind11::handle) Line 542	C++
 	[Inline Frame] inviwo-module-python3.dll!pybind11::detail::accessor<pybind11::detail::accessor_policies::generic_item>::operator=(pybind11::object &&) Line 485	C++
 	inviwo-module-python3.dll!inviwo::PythonScriptProcessor::{ctor}::__l2::<lambda>() Line 61	C++
 	inviwo-module-python3.dll!inviwo::PythonScriptProcessor::PythonScriptProcessor(inviwo::InviwoApplication * app) Line 78	C++
 	[Inline Frame] inviwo-module-python3.dll!std::make_unique(inviwo::InviwoApplication * &) Line 2539	C++
 	inviwo-module-python3.dll!inviwo::detail::makeProcessor<inviwo::PythonScriptProcessor>(inviwo::detail::app_constructor __formal, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & id, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & name, inviwo::InviwoApplication * app) Line 109	C++
 	inviwo-module-python3.dll!inviwo::detail::makeProcessor<inviwo::PythonScriptProcessor>(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & id, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & name, inviwo::InviwoApplication * app) Line 94	C++
 	inviwo-module-python3.dll!inviwo::ProcessorFactoryObjectTemplate<inviwo::PythonScriptProcessor>::create(inviwo::InviwoApplication * app) Line 137	C++
 	inviwo-core.dll!inviwo::StandardFactory<inviwo::Processor,inviwo::ProcessorFactoryObject,std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &,inviwo::InviwoApplication *>::create(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & key, inviwo::InviwoApplication * <args_0>) Line 150	C++
 	inviwo-core.dll!inviwo::ProcessorFactory::create(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & key) Line 66	C++
 	inviwo-core.dll!inviwo::Deserializer::getRegisteredType<inviwo::Processor>(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & className) Line 572	C++
 	inviwo-core.dll!inviwo::Deserializer::deserialize<inviwo::Processor>(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & key, inviwo::Processor * & data) Line 1067	C++
 	inviwo-core.dll!inviwo::ContainerWrapper<inviwo::Processor *,std::basic_string<char,std::char_traits<char>,std::allocator<char> > >::deserialize(inviwo::Deserializer & d, ticpp::Element * node, unsigned __int64 ind) Line 320	C++
 	inviwo-core.dll!inviwo::Deserializer::deserialize<inviwo::Processor *,std::basic_string<char,std::char_traits<char>,std::allocator<char> > >(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & key, inviwo::ContainerWrapper<inviwo::Processor *,std::basic_string<char,std::char_traits<char>,std::allocator<char> > > & container) Line 1129	C++
 	inviwo-core.dll!inviwo::util::MapDeserializer<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,inviwo::Processor *>::operator()<std::unordered_map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,inviwo::Processor *,std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,inviwo::Processor *> > > >(inviwo::Deserializer & d, std::unordered_map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,inviwo::Processor *,std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,inviwo::Processor *> > > & container) Line 541	C++
 	inviwo-core.dll!inviwo::ProcessorNetwork::deserialize(inviwo::Deserializer & d) Line 409	C++
 	inviwo-core.dll!inviwo::Deserializer::deserialize(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & key, inviwo::Serializable & sObj) Line 69	C++
 	[External Code]	
 	[Inline Frame] inviwo-core.dll!std::_Func_class<void,inviwo::Deserializer &>::operator()(inviwo::Deserializer &) Line 247	C++
 	inviwo-core.dll!inviwo::WorkspaceManager::onLoad::__l2::<lambda>(inviwo::Deserializer & d, const std::function<void __cdecl(inviwo::ExceptionContext)> & exceptionHandler) Line 247	C++
 	[Inline Frame] inviwo-core.dll!std::_Func_class<void,inviwo::Deserializer &,std::function<void __cdecl(inviwo::ExceptionContext)> const &>::operator()(inviwo::Deserializer &) Line 157	C++
 	[Inline Frame] inviwo-core.dll!inviwo::Dispatcher<void __cdecl(inviwo::Deserializer &,std::function<void __cdecl(inviwo::ExceptionContext)> const &)>::invoke(inviwo::Deserializer &) Line 69	C++
 	inviwo-core.dll!inviwo::WorkspaceManager::load(std::basic_istream<char,std::char_traits<char> > & stream, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & refPath, const std::function<void __cdecl(inviwo::ExceptionContext)> & exceptionHandler) Line 157	C++
 	inviwo-core.dll!inviwo::WorkspaceManager::load(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & path, const std::function<void __cdecl(inviwo::ExceptionContext)> & exceptionHandler) Line 173	C++
 	inviwo-qteditor.dll!inviwo::InviwoMainWindow::openWorkspace(QString workspaceFileName, bool isExample) Line 1007	C++
 	inviwo-qteditor.dll!inviwo::InviwoMainWindow::openWorkspace(QString workspaceFileName) Line 939	C++
 	[Inline Frame] inviwo-qteditor.dll!inviwo::InviwoMainWindow::addActions::__l14::<lambda_70f1803b554509dd1046ccd7bec722d3>::operator()() Line 482	C++
 	[Inline Frame] inviwo-qteditor.dll!QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,<lambda_70f1803b554509dd1046ccd7bec722d3> >::call(inviwo::InviwoMainWindow::addActions::__l14::<lambda_70f1803b554509dd1046ccd7bec722d3> &) Line 146	C++
 	[Inline Frame] inviwo-qteditor.dll!QtPrivate::Functor<<lambda_70f1803b554509dd1046ccd7bec722d3>,0>::call(inviwo::InviwoMainWindow::addActions::__l14::<lambda_70f1803b554509dd1046ccd7bec722d3> &) Line 256	C++
 	inviwo-qteditor.dll!QtPrivate::QFunctorSlotObject<<lambda_70f1803b554509dd1046ccd7bec722d3>,0,QtPrivate::List<>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 439	C++
 	[External Code]	
 	inviwo-qtapplicationbase.dll!inviwo::InviwoApplicationQt::notify(QObject * receiver, QEvent * e) Line 312	C++
 	[External Code]	
 	inviwo-qtapplicationbase.dll!inviwo::InviwoApplicationQt::notify(QObject * receiver, QEvent * e) Line 312	C++
 	[External Code]	
 	inviwo-cli.exe!main(int argc, char * * argv) Line 122	C++
 	[External Code]

**Comment by petersteneteg** [comment]
Use the new Python processors... Will not maintain this old system

**Comment by ResearchDaniel** [comment]
This is the new based on python code.
Title should have said pythonscriptprocessor I guess

**Comment by petersteneteg** [comment]
The script you pasted is using the old deprecated methods. Don’t use the pythonscriptprocessor, create a python processor directly instead

**Comment by ResearchDaniel** [comment]
Ah, we should remove Python3/data/scripts/scriptprocessorexample.py

**Comment by petersteneteg** [comment]
Very true
