### ISSUE TITLE
Shader::verify

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#553]
The `Shader::verify()` method is way to render specific. It always throws an exception if we have no vertex shader. 
https://github.com/inviwo/inviwo/blob/master/modules/opengl/src/shader/shader.cpp#L146-L150

There are cases where a shader programs don't require a vertex shader. For example with a compute shader. 

Trying to write a verify function that takes all use cases into account is very tricky. Wouldn't the glLinkProgram generate a warning/error if needed shaders are missing? If not, will we not get an OpenGL warning/error when trying to use the shader?

**Comment by petersteneteg** [comment]
Think that can be removed
