### ISSUE TITLE
Suspicious handling of uint16 in PVMVolumeReader

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#567]
Why is uint16 data handled differently in `PVMVolumeReader`?

https://github.com/inviwo/inviwo/blob/64e737d97bf857405b8f098e969fb7bcdb979ae5/modules/pvm/src/pvmvolumereader.cpp#L123-L132

In particular, why is the minimum value set? In line 173, the data mapper is re-initialized with the data format...
https://github.com/inviwo/inviwo/blob/64e737d97bf857405b8f098e969fb7bcdb979ae5/modules/pvm/src/pvmvolumereader.cpp#L173

which resets the lower bound to 0 for uint16:
```c++
void DataMapper::initWithFormat(const DataFormatBase* format) {
    dataRange.y = format->getMax();
    switch (format->getNumericType()) {
        case NumericType::Float:
            dataRange.x = -format->getMax();
            break;
        case NumericType::UnsignedInteger:
            dataRange.x = 0.0;
            break;
        case NumericType::SignedInteger:
```

**Comment by ResearchDaniel** [comment]
I think that @timoropinski implemented this reader.

**Comment by petersteneteg** [comment]
> I think that @timoropinski implemented this reader.

no, erik did long long ago

**Comment by ResearchDaniel** [comment]
I think that it is just a bug and that we should handle PVM uint16 in the same way as other uint16 readers

**Comment by petersteneteg** [comment]
Think this is related to old 12bit support...

**Comment by martinfalk** [comment]
Specific uint16 handling removed in ff58640
