### ISSUE TITLE
Module name with initial s

### ISSUE THREAD

**Issue by petersteneteg** [inviwo/inviwo#580]
https://github.com/inviwo/inviwo/commit/e0b12c5443e71fa59577096950fd78d30a729833#r34155242

**Comment by r-englund** [comment]
Adding the comment referenced above for ease of reading: 

> I think I may have encountered a problem which I doesn't seem to have been reported. When making a new module ( through Inviwo ) with a name beginning by 's' or several 's's the cmake doesn't register it under the right name and absorbs the 's's. That causes conflicts as the directory will have the proper name ('spline' for example) but the module will not ('pline'). The CMakeList file also has the proper line: ivw_module(spline) I have tried with a bunch other letters at the beginning and they seem to be working ok. For now I have resorted to naming the module bspline (which is the name of the specific type of spline used).

**Comment by r-englund** [comment]
I\ll bet there is a \s somewhere being interpreted as a whitespace

**Comment by r-englund** [comment]
I think we might have found a bug in cmake, in the function `ivw_private_get_ivw_module_name` in globalutils.cmake we have a regexpt mathcing whitespaces using \\s, it seems that one is also catching the regular s as a whitespace.
