### ISSUE TITLE
PropertyPresetManager overrides the displayname

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#585]
When setting a property using a preset the display name gets set to the display name to the was set to the property when the preset was created. 
This is especially bad for Workspace and Application level presets. 

**Steps to reproduce**
1. Add a background processor
2. Create a workspace or application preset on `Color 1`
3. Set `Color 2` using the preset from `Color 1`

Edit: Added steps to reproduce

**Comment by ResearchDaniel** [comment]
Rephrasing:
The property preset overrides the display name
This is what you meant?

**Comment by r-englund** [comment]
yes

**Comment by r-englund** [comment]
**Steps to reproduce**
1. Add a background processor
2. Create a workspace or application preset on `Color 1`
3. Set `Color 2` using the preset from `Color 1`

**Comment by r-englund** [comment]
> // We deserialize into a clone here and link it to the original to only set value not
        // identifiers and such.

what is such?

https://github.com/inviwo/inviwo/blob/master/src/core/properties/propertypresetmanager.cpp#L55-L59

**Comment by r-englund** [comment]
Hrm, it seems only the widget get a new display name, the displayname of the property is actually correct

**Comment by r-englund** [comment]
The property copy/clone makes a shallow copy of `std::vector<PropertyWidget*> propertyWidgets_;`

**Comment by r-englund** [comment]
> 
> 
> The property copy/clone makes a shallow copy of `std::vector<PropertyWidget*> propertyWidgets_;`

That was wrong, it is the copy ctor of Observer that "copies" the observers. 
```
Observer::Observer(const Observer& rhs) {
    for (auto observable : rhs.observables_) addObservation(observable);
}
```

adding `temp->stopBlockingNotifications();` to  `PropertyPresetManager::loadPreset::apply` fixes the issue, but the question remain, should the Observer copy who observs it?

**Comment by ResearchDaniel** [comment]
We hade issues before when they were not copied, especially since it is the copy constructor.

In the case of Property presets we should probably clear the observers?

**Comment by r-englund** [comment]
Can't clear them, but block notifications, testing it now, just found another related bug with observers, a PR will be up within 30 min

**Comment by ResearchDaniel** [comment]
I think that we should expose the removeObservers function in Observable

**Comment by r-englund** [comment]
> I think that we should expose the removeObservers function in Observable 

Isn't it made private for a reason? IMO it should be private, making it public would allow anyone to remove all observers when they are not supposed to.

**Comment by petersteneteg** [comment]
@r-englund we can close this right?

**Comment by r-englund** [comment]
No, it has not been fixed

**Comment by petersteneteg** [comment]
Ahh ic, it was not merged....
