### ISSUE TITLE
FileProperty does not store extension/type of selected reader

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#590]
When a `FileProperty` is serialized, it stores a list of all registered file extensions (`<nameFilter>`). However, neither the currently used reader nor the extension is not stored. This can cause problems when multiple readers are registered for the same file extension.

Example: 
* TIFF-Reader registers `tif` and `tiff
* DICOM-Reader registers `tif` and `dcm`
* TIFF volume data is loaded in `VolumeSource` with `TIFF reader` selected, then the workspace is saved
* Loading the workspace results in an error that the DICOM reader failed to read the tiff file (it might be the first reader in the factory handling a tiff extension)

How should we deal with this?

**Comment by ResearchDaniel** [comment]
Not sure if there is a reason why selectedExtension is not stored. Should be an easy fix.

As for the reader it is more of a problem that the loader registers a reader for a format it does not fully support?

**Comment by petersteneteg** [comment]
We might serialize the reader identifier last used...
Think we usually clear the list of deserialized extensions anyway....
We might need to track is a special reader is selected or if the "default" is used also

**Comment by martinfalk** [comment]
What is considered to be the "default" then? That is really depending on the registration or is it even random?

**Comment by martinfalk** [comment]
@ResearchDaniel `selectedExtension` is missing in `deserialize/serialize`

**Comment by martinfalk** [comment]
but that will interfere with #591. As pointed out there, just saving the extension doesn't do the trick.

**Comment by petersteneteg** [comment]
don't think we should serialize the selected extenstion but rather the reader used...

**Comment by petersteneteg** [comment]
default would probably be like (*) if the user actually makes a manual selection then its not default any more... 

We might want to actively set the selectedext to * when one edits the text also...

we should probably also show which reader that was used.
