### ISSUE TITLE
FileDialog: Multiple extensions of same reader should be collapsed

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#591]
Some DataReaders register multiple extensions. My suggestion: the file dialog should collapse these as much as possible based on the description string.

E.g. `TIFF Stack (*.tif)` and `TIFF Stack (*.tiff)` clearly belong together and could be merged into `TIFF Stack (*.tif;*.tiff)`.

![image](https://user-images.githubusercontent.com/9251300/60616793-97623700-9dd2-11e9-95c0-870d1ab6cfcf.png)

**Comment by ResearchDaniel** [comment]
Agree

**Comment by petersteneteg** [comment]
Does that work in qt?

**Comment by ResearchDaniel** [comment]
It seems so:
https://doc.qt.io/qt-5/qfiledialog.html#setMimeTypeFilters

**Comment by martinfalk** [comment]
yes, `dialog.setNameFilter("All C++ files (*.cpp *.cc *.C *.cxx *.c++)");`

**Comment by petersteneteg** [comment]
so would you group them by reader identifier, first and then by description second? PRs are welcome

**Comment by ResearchDaniel** [comment]
By MIME-type would be even better?

**Comment by petersteneteg** [comment]
so you think there is a mime type for our dat files

**Comment by ResearchDaniel** [comment]
No, but for images, csv files etc.

**Comment by martinfalk** [comment]
MIME type can also cause issues. E.g. CImg reads png and tiff, but we also have dedicated tiff and png readers.

**Comment by petersteneteg** [comment]
wondering it is would not be more useful to sort that list on extension first and then description...

Usually you know the extension of the file you want to open and then might want to see which readers are around for that extension...

**Comment by r-englund** [comment]
> 
> 
> wondering it is would not be more useful to sort that list on extension first and then description...
> 
> Usually you know the extension of the file you want to open and then might want to see which readers are around for that extension...

I like that, but then we can't group them, in for example `dialog.setNameFilter("All C++ files (*.cpp *.cc *.C *.cxx, *.c++,*.h,*.hpp,*hxx)");` would need to be sorted on both 'c' and 'h'

**Comment by martinfalk** [comment]
Example from paint.net:
![image](https://user-images.githubusercontent.com/9251300/60650101-bfd64980-9e43-11e9-97c1-4c27114e709e.png)

**Comment by martinfalk** [comment]
ParaView is probably not the best example
![image](https://user-images.githubusercontent.com/9251300/60650173-e300f900-9e43-11e9-98d9-37bbd94e98a2.png)

**Comment by petersteneteg** [comment]
yes, then we don't get that kind of grouping, but I would argue that that is not what you want. you want to see which readers are atound for your file ext. and when we group the file extensions finding all instances of one specific one is very hard.

**Comment by petersteneteg** [comment]
I've looked into this some more and this would require changes to all our data readers since they use the inviwo::FileExtension to id them self...

**Comment by petersteneteg** [comment]
Will not do
