### ISSUE TITLE
Copy Constructor of Observer copies the observers of the orignal

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#594]
The Copy Constructor of Observer copies the observers of the orignal, should it?
https://github.com/inviwo/inviwo/blob/master/src/core/util/observer.cpp#L34-L36
```c++
Observer::Observer(const Observer& rhs) {
    for (auto observable : rhs.observables_) addObservation(observable);
}
```
casuses issue in the `PropertyPresetManager` #585

**Comment by petersteneteg** [comment]
Tread very carefully here, this has lot and lots of implications many of them which is very hard to detect...

**Comment by r-englund** [comment]
![image](https://user-images.githubusercontent.com/534670/60646190-03788580-9e3b-11e9-8931-d81927671163.png)

**Comment by ResearchDaniel** [comment]
Short answer: Yes it should and it is not a bug :)

**Comment by ResearchDaniel** [comment]
I don't exactly remember where it was needed but I guess you can try to remove it and see if anything breaks.

I'm not sure if it is logical that a copy does not observe the same thing though.
