### ISSUE TITLE
glUseProgram access violation - Intel HD Graphics 520

### ISSUE THREAD

**Issue by VisComKreiser** [inviwo/inviwo#6]
Hi,
a student of mine can build inviwo and launch it.
But as soon as a Processor tries to activate a shader, the application crashes with an access violation.
The shader builds and links, even the canvas processor fails.

It runs on a Laptop without dedicated graphics card on Intel HD graphics 520 which says it is OpenGL 4.4 ready.
Is this a hardware/OpenGL support problem? Or even a known phenomena on Intel only Systems?

Best Julian

**Comment by ResearchDaniel** [comment]
Could it be the same error as issue #3?

**Comment by VisComKreiser** [comment]
Thanks for the fast reply,
I'll try to contact her and add the suggested Code

**Comment by ResearchDaniel** [comment]
We might have a better fix for it in an upcoming release. The problem could be caused by an outdated GLEW version. We have updated GLEW to 2.0.0, which fixed a similar problem on some ATI/Intel cards.

**Comment by VisComKreiser** [comment]
Can you tell when this update is going to be available?

**Comment by ResearchDaniel** [comment]
Will check and get back to you ASAP

**Comment by VisComKreiser** [comment]
Perfect, thanks!

**Comment by ResearchDaniel** [comment]
On second thought it seems as the GLEW changes where already pushed in version 0.9.8 so this must be a different problem

**Comment by VisComKreiser** [comment]
okay, do you have any suggestion on how to narrow down the problem maybe?

**Comment by ResearchDaniel** [comment]
We have tried to nail it down internally (we have an Intel Graphics card HD 4000 with what we believe is the same problem). The workaround right now in is to do as suggested in #3 . We will get back to you if we need more input

**Comment by VisComKreiser** [comment]
Thanks for investigating, I'm glad to help.

**Comment by ResearchDaniel** [comment]
We seem to have resolved the problem and aim to release a new version next week.

**Comment by VisComKreiser** [comment]
great, we will try it out when it is released. what exactly was the issue then?

**Comment by ResearchDaniel** [comment]
We think that it was issues with synchronization between OpenGL contexts. We did some cleanup and added better OpenGL debug output so that it is easier to find issues ( https://www.opengl.org/wiki/Debug_Output ). 
Would be great if you can confirm if it has been resolved after the release!

**Comment by VisComKreiser** [comment]
do you know which versions of intel HD graphics should work?

we now have a students laptop with an intel i5-2520m and HD graphics 3000 which crashes with access violation when calling glCreateProgram.

**Comment by ResearchDaniel** [comment]
We have tested it using Intel HD 4000. We recently tried it using Intel HD 620, where it still does not work though.

**Comment by petersteneteg** [comment]
Try updating to the latest git version now. Hopefully that will help

**Comment by VisComKreiser** [comment]
thanks, I'll forward that to my students
