### ISSUE TITLE
CMake configuration error - ZLIB_INCLUDE_DIR

### ISSUE THREAD

**Issue by Bishares** [inviwo/inviwo#623]
Hey,

I was trying to compile Inviwo on my machine:

Windows 10
Visual Studio 2017
CMake 3.15.0
Qt 5.13.0
Radeon RX Vega

I'm on the master branch and have updated all submodules using:
git submodule update --init --recursive

the following error occures when i try to configure. However, I was able to build Inviwo after switching back to the last release commit 0.10.

![image](https://user-images.githubusercontent.com/38129103/62470094-f3d1c100-b799-11e9-87a3-7915dc66cadf.png)

Another issue is that when I have built Inviwo, some errors show up in the console for the running version 0.10:

![image](https://user-images.githubusercontent.com/38129103/62472281-a7d54b00-b79e-11e9-8461-d02a48818a3e.png)

**Comment by petersteneteg** [comment]
Ahh I think I now whats going on. We use out own zlib in openexr. But in a reset update to freetype it now also looks for zlib and cant find it... then the following use in openexr also will not find it..

**Comment by petersteneteg** [comment]
@Bishares I think this should be fixed in the lastest master. Let me know it you still run into problems.

**Comment by ResearchDaniel** [comment]
Looks like the fix only works for Cmake version >=3.15

**Comment by petersteneteg** [comment]
Fixed in #630
