### ISSUE TITLE
Inviwo fails to load qt resources when building statically (Windows)

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#629]
One solution is to add 
```c++
#ifndef INVIWO_ALL_DYN_LINK
    Q_INIT_RESOURCE(inviwo);
#endif
```
to the beginning of the main() in inviwo.cpp (and `Q_CLEANUP_RESOURCE` at the end of main) 

another option is to add the following struct to the global namespace in `qtwidgetsmodule.cpp`
```
struct InitQtRCC {
    InitQtRCC() { Q_INIT_RESOURCE(inviwo); }
    ~InitQtRCC() { Q_CLEANUP_RESOURCE(inviwo); }
} initQtRCC;
```

a third option is to call the `Q_INIT_RESOURCE`/`Q_CLEANUP_RESOURCE` in the ctor and dtor of `QTWidgetsModule`

The reason of putting it in the QtWidgetsModule is that is the project that is also compiling the resources. 

If we put it in inviwo.cpp I guess we also need to put it in the any other main function (e.g. the TinyQtApp) where we use our Qt Widgets 

![image](https://user-images.githubusercontent.com/534670/62610397-ecc6c200-b903-11e9-8145-ec7a24b27ff2.png)

**Comment by r-englund** [comment]
A note on why this is happening for static linking and not dynamic linking: [source](https://wiki.qt.io/QtResources 
 > The constructor function trick works only if the generated C++ file is compiled and linked to the main application directly. If the resources are used in a static library and the library is then linked to the main application, the constructor function will never get called. This is the by nature of C/C++ linking- functions and variables in libraries that are unused/uncalled from the final program are removed from the final binary (optimized out). If the resources are in a shared library, then the constructor function does get invoked. However, most platforms load shared libraries on demand and the constructor function gets called only when the shared library gets loaded. The consequence is that any resources in plugins used by the main program will not be found by Qt until the plugin itself gets loaded - it's not a problem if the resources in the shared library are used only in the shared library. Note that accessing the resource inside a shared object in the main application does not trigger loading of the shared object since no symbol is exported by QRC system to trigger loading of the shared object.
> 
> A solution to the above problems is to use the Q_INIT_RESOURCE macro, placed at the beginning of main(), which ensures that the resources are linked into the application in the case of static linking, or forces the loading of the library in the case of dynamic linking.

**Comment by petersteneteg** [comment]
think I like version 2 best
