### ISSUE TITLE
PythonEditor: file modified dialog pops up twice

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#63]
1) open a script in the Inviwo Python Editor
2) edit script in an external editor and save it
3) the Python Editor will show the "file has been modified" dialog twice.

![image](https://user-images.githubusercontent.com/9251300/38497722-55711506-3c02-11e8-9e3b-0ca7274b8a65.png)

**Comment by martinfalk** [comment]
Every time the external file is modified, the dialog pops up. Even if it is already visible.

Suggestion: make the dialog pop up only if the widget is currently in focus, i.e. active.

**Comment by martinfalk** [comment]
The dialog also pops up even if the python editor is not visible.

**Comment by r-englund** [comment]
I recall something about this. Either we discussed it somewhere or I had/have some fix for it. Prefarably there should be an option (like in sublime and other editors) to auto reload without popup if no local change is made.

**Comment by martinfalk** [comment]
agreed. Experimenting with showing the popup dialog only when active.

**Comment by r-englund** [comment]
fixed now
