### ISSUE TITLE
Reason for using __FUNCTION__ in macros?

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#66]
Any particular reason why we use the `__FUNCTION__` macro, e.g. in the Log messages?

Why not `__FUNCSIG__` (Visual Studio) or `__PRETTY_FUNCTION__` (gcc / clang)?

Results for `bool func(bool *bla) { return false; }`:
- `__FUNCTION__`  --> `func`
- `__FUNCSIG__` -->  `bool __cdecl func(bool *)`
- `__PRETTY_FUNCTION_` --> `bool func(bool *)`

**Comment by petersteneteg** [comment]
```__FUNCTION__``` is in the standard....

**Comment by petersteneteg** [comment]
FUNCSIG/PRETTY_FUNCTION can also be quite verbose in some situations... But I guess it could also be quite useful in some cases...

**Comment by petersteneteg** [comment]
Unless you think we should do something herr I close this
