### ISSUE TITLE
Jenkins: Run clang-format test only on changed files

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#666]
Currently, we check the formating of all files in the repo in the format stage which often gives "false positives*" and therefore the `J: Format test failure` is often ignored. 
We could change the script to only test the files that has changed in current branch. We can get a list of changed files using `git diff --name-only $(git merge-base origin/master HEAD)` (might use just `master` instead of `origin/master`) 

\* They are wrongly formated, but not caused by the changes in the current branch.

**Comment by petersteneteg** [comment]
Has been on my list of todis :)

**Comment by petersteneteg** [comment]
Problem is when one builds master and not a branch that should merge, then that diff will fail I think...

**Comment by petersteneteg** [comment]
If we do this then those errors should also be hard errors or?

**Comment by r-englund** [comment]
> Problem is when one builds master and not a branch that should merge, then that diff will fail I think...

Master should already be correctly formated ;) 

> If we do this then those errors should also be hard errors or?

Probably yes. maybe allow the user to download/copy the formated version if they do not have clang-format on their machine?

**Comment by r-englund** [comment]
On a related topic, I've been following a "Merge Request" for [PCH in cmake ](https://gitlab.kitware.com/cmake/cmake/merge_requests/3553). They can tell the system to format the files for them by commenting `do: reformat` in the merge request. It would be nice if we had a similar feature xD

**Comment by petersteneteg** [comment]
hehe

**Comment by petersteneteg** [comment]
Fixed
