### ISSUE TITLE
Update Qt version dependency

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#671]
**Issue**
Get a compile error from qt-usage even though everything goes through without errors in CMake.

Cmake should produce an error if an old Qt version is used. Get a compile the same compile error as in #398
We need to update cmake scripts as well as the Wiki. Currently we support version 5.12

**Environment information**
* Operating System: Mac
* Compiler/IDE: XCode
* QT Version: 5.8

**Comment by ResearchDaniel** [comment]
i updated the wiki

**Comment by petersteneteg** [comment]
PR welcome
