### ISSUE TITLE
Should we copy Qt DLL's to build folder

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#691]
By adding the following to our cmake we would copy QT dll's and other necessary files to our build directory. 
```cmake
if(WIN32)
    # Run winddeployqt if it can be found
    find_program(WINDEPLOYQT_EXECUTABLE NAMES windeployqt HINTS ${QTDIR} ENV QTDIR PATH_SUFFIXES bin)
    add_custom_command(TARGET inviwo POST_BUILD COMMAND ${WINDEPLOYQT_EXECUTABLE} $<TARGET_FILE:inviwo>)
endif()
```
`windeployqt.exe` is a executable supplied by QT that looks at an executable to see which qt dependencies that has and copies the files needed by that application. In our case it looks at inviwo.exe and copies the necessary files to build/bin/[Config]. 

Adding this to our build pipeline would prevent issues with multiple QT in the system path (e.g. when having Miktex or anaconda in the path). 

I've breifly tried it on my machine and it work, but If we want to add this I would do more testing with different qt version before adding.

**Comment by petersteneteg** [comment]
an ugly solution to a ugly problem... makes sense I guess

**Comment by martinfalk** [comment]
Do you really want this also for debug libraries?

**Comment by r-englund** [comment]
PR merged 7 days ago
