### ISSUE TITLE
SpinBox semantics for int properties results in decimal values. 

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#692]
![image](https://user-images.githubusercontent.com/534670/64323374-aaf17000-cfc4-11e9-8541-acf4e01f55de.png)

**Comment by martinfalk** [comment]
The internal representation of a spinbox is always double. What's shown should be rounded for int types. Seems that the internal logic is flawed... Also doesn't work for `int`.

https://github.com/inviwo/inviwo/blob/cb0709fddc1c73ecd24d35fcf775eb84f7ab5195/modules/qtwidgets/include/modules/qtwidgets/properties/ordinalspinboxwidget.h#L133-L146

**Comment by ResearchDaniel** [comment]
@martinfalk fixed?

**Comment by martinfalk** [comment]
Maybe, need to look into this. However, `double reprToEditor(T val)` looks strange with no difference between if and else statements.
https://github.com/inviwo/inviwo/blob/5728b3368984bd19446d8c74f9981c0e9442f606/modules/qtwidgets/include/modules/qtwidgets/properties/ordinalspinboxwidget.h#L102-L116
