### ISSUE TITLE
TF editor sliders not properly initialized in Qt 5.12/5.13

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#693]
It appears that the latest Qt version (5.13.0) breaks some sliders in the TF editor

![image](https://user-images.githubusercontent.com/9251300/64326348-18ec6600-cfca-11e9-935c-ade9919b7373.png)

**Steps to reproduce**
1.  Add a Volume Raycaster 
2. Open the TF editor
3. Modify the sliders
4. Save and reload the network
5. Open the TF editor, sliders are wrong

Edit: Added steps to reproduce // Rickard

**Comment by r-englund** [comment]
Care to elaborate, I can't reproduce on my machine?

**Comment by martinfalk** [comment]
See the sliders on the left? Empty workspace, drop e.g. a volume raycaster, and open the TF editor. The initial slider position is off. However, the moment you start adjusting them, it snaps back into correct behavior.

**Comment by r-englund** [comment]
Strange, works fine on my machine

**Comment by r-englund** [comment]
I could reproduce:
1.  Add a Volume Raycaster 
2. Open the TF editor
3. Modify the sliders
4. Save and reload the network
5. Open the TF editor, sliders are wrong

**Comment by petersteneteg** [comment]
I have the same issue in qt 5.12

**Comment by martinfalk** [comment]
Affects only the vertical sliders.
