### ISSUE TITLE
"\modules\_generated\modules" subdirectory does not appear when building from the .zip archive

### ISSUE THREAD

**Issue by VisComKreiser** [inviwo/inviwo#7]
We tried to build Inviwo from the downloadable .zip archive on the homepage together with a module having dependencies on:

- InviwoOpenGLModule
- InviwoBaseGLModule

In the build directory, the generated files in "\modules\_generated\modules" do not appear.
E.g. "modules/basegl/shader_resources.h"

When using the source code from Github, everything is generated fine with CMake.

**Comment by petersteneteg** [comment]
The links on the webpage was outdated, they are now up to date. Hopefully it should work better now

**Comment by VisComKreiser** [comment]
thanks for the quick update
