### ISSUE TITLE
Missing Python exports for PlaneProperty and VolumeIndicatorProperty

### ISSUE THREAD

**Issue by andkem** [inviwo/inviwo#70]
## Problem
Exports to Python for the PlaneProperty and VolumeIndicatorProperty seem to be missing. These are used in the Volume Raycaster.

## Reproduction
```python
#Inviwo Python script 
import inviwopy


app = inviwopy.app
network = app.network

processor = app.processorFactory.create('org.inviwo.VolumeRaycaster')
position_indicator = processor.getPropertyByIdentifier('positionindicator')
help(position_indicator)
```

Note that there doesn't seem to be any way of getting the properties under the positionindicator.

## Fix applied by us in our project
We simply added exports for the settings found under the positionindicator. Our changes made to the 0.9.9 version of Inviwo can be found [at this commit](https://github.com/andkem/inviwo/commit/d4bd8269874aee4fdbe2d988fc2ff64500f04084). It has been tested on Linux Ubuntu 16.04 and FreeBSD 11.1-RELEASE-p9.

The member variables in the two property-classes were all public and no attempt was made to make them private when adding setters and getters.

**Comment by petersteneteg** [comment]
does not ```app.network.VolumeRaycaster.positionindicator.plane1.position``` etc work?

**Comment by andkem** [comment]
It does not work in version 0.9.9, no. I haven't tested with the latest master.

**Comment by petersteneteg** [comment]
I think it should work in 0.9.9. Anyway, the line above works in the latest master. So it is not likely that we will try and do anything about this in 0.9.9. 

Remember that PlaneProperty and VolumeIndicatorProperty are CompositeProperties, so you can get to their sub properties using either the ```positionindicator.plane1.position``` syntax above or using positionindicator.getPropertyByIdentifier('plane1') etc

**Comment by andkem** [comment]
Trying to use getPropertyByIdentifier('plane1') just tells us that the positionindicator doesn't have any such method on v0.9.9.

If it works on master and you have no time to back port a fix, that's fine since we got it working with our own little fix.

**Comment by r-englund** [comment]
I think that the reason for the `getPropertyByIdentifier` for PlaneProperty and VolumeIndicatorProperty in your code is that you in commit https://github.com/andkem/inviwo/commit/d4bd8269874aee4fdbe2d988fc2ff64500f04084 do
```
py::class_<PlaneProperty, Property, PropertyPtr<PlaneProperty>>(...);
py::class_<VolumeIndicatorProperty, Property, PropertyPtr<VolumeIndicatorProperty>>(...);
```
The second template argument (`Property`) is telling pybind which is class is the base class. This needs to be `CompositeProperty` for `getPropertyByIdentifier` and the `.` operator to work.  ( The `getPropertyByIdentifier` is actually defined in `PropertyOwner`, which is base class for the `CompositeProperty` and but not for ´Property´)

**Comment by andkem** [comment]
Sure, that is probably the case. I didn't look further into that issue since the `.` operator worked by exporting the properties like I did in my commit. I'll try changing it if I get some time to spare.

Thank you for having a look!
