### ISSUE TITLE
Brushing and linking revamp

### ISSUE THREAD

**Issue by PetiteViking** [inviwo/inviwo#715]
## Idea
Instead of one set each for `selected`/`filtered`/`selectedColumn` we would have a `std::map<std::string, std::unordered_set<size_t>>` for selected and filtered indices. This has the advantage that one can have as many filtering/selection sets as desired or needed. The `selectedColumns` set would then be a subset of the `selectedIndices` map.

### Design choices
There are some open aspects regarding the design of the implementation.

#### What should happen when `getSelectedIndices()` is called with a string that does not exist?
- Insert new empty set -> loose constness of the method which also trickles down into the `BrishungAndLinkingPort` and `BrushingAndLinkingEvent` (sub)classes.
- Return an empty set -> This conveys false information since the set actually does not exist.
- Throw exception -> ugly af

**Comment by petersteneteg** [comment]
You can return an optional

**Comment by r-englund** [comment]
We had quite a long discussion/meeting about this a while ago where we talked about changing from maps to vector<bool> and also talked about replacing the hard_coded sets. Was this documented somewhere?

**Comment by JochenJankowai** [comment]
@petersteneteg Should have thought about that...

**Comment by petersteneteg** [comment]
I have a design in mind for this, but I have not had time to work on it yet...

**Comment by ResearchDaniel** [comment]
I think this has been fixed in the latest brushing and linking PRs by @martinfalk
