### ISSUE TITLE
Memory leak with Python Script Processor

### ISSUE THREAD

**Issue by xeTaiz** [inviwo/inviwo#748]
I built a Python script processor, which does the following:
```
if not "outport_ao" in self.outports:
    self.addOutport(VolumeOutport('outport_ao'))
if not "reload_ao" in self.properties:
    self.addProperty(ButtonProperty("reload_ao", "Reload AO", load_ao))

def process(self):
    ao = Volume(self.current_ao.astype(np.float32))
    self.outports.outport_ao.setData(ao)

def load_ao():
    self.current_ao = np.load(...)
``` 

So my processor has a button that triggers `load_ao` which loads an array from disc.
My `process()` just wraps this in a `Volume` and passes it to the outport. 

Calling this `load_ao()` function using the button adds the size of the array to my memory usage, indicating that the memory for the old array was not freed. If i connect this volume to something that needs an OpenGL representation, my gpu ram fills up in a similar way.

I also noted that no memory is freed upon deleting the processor, neither CPU nor GPU memory. However I suspect this might have the same cause as the above.

Also, having seen the `FlickrAPI` processor example from the VCBM workshop, I wonder whether the "style" of defining a processor without a class, using the global `self`, is still inteded to be used? I also had great issues in deserializing a workspace that has a PythonScriptProcessor with my script set up like this. 

If this is not intended to be used in this way anymore, but only using classes as suggested in the VCBM slides, I would suggest we adapt the PythonScriptProcessor [template](https://github.com/inviwo/inviwo/blob/master/modules/python3/data/scripts/scriptprocessorexample.py) and [examples](https://github.com/inviwo/inviwo/tree/master/modules/python3/data/scripts).

**Comment by petersteneteg** [comment]
So the python script processor is (or should be) deprecated, and yes we should update any examples. That said my experience is the the memory management work better with the new python processors but it is still far from perfect. And crashes and memory leaks happens sometimes,  unfortunately fixing it is not trivial, in some aspects it is quite hard to get python to play but c+c rules...

**Comment by martinfalk** [comment]
@xeTaiz The `PythonScriptProcessor` has been marked as deprecated and yes, the examples need a major overhaul. Some of them are quite outdated as well.

The memory problem might persist even with the newer type of python processor...

**Comment by xeTaiz** [comment]
After switching to the newer type I immediately got rid of my memory issues ;)
