### ISSUE TITLE
Uncaught Exception in Pybind11

### ISSUE THREAD

**Issue by VisComKreiser** [inviwo/inviwo#756]
I've tried no to compile the stock inviwo in the master an get a runtime error in pybind11 -> embed.h line 109 directly on startup during the splash screen.

![image](https://user-images.githubusercontent.com/11948756/67212434-a79f3000-f41c-11e9-8e30-9cc01a5d84ae.png)

**Comment by r-englund** [comment]
Both @martinfalk and @MutterOberin had this issue recently. IIRC, to solve it, you need to set your PYTHON_HOME environment variable. 

@martinfalk/@MutterOberin might have more details

**Comment by VisComKreiser** [comment]
Okay, is that still needed when I try to bundle everything to a portable oder installer if the target system has no Python installed and is shipped with Inviwo?

**Comment by r-englund** [comment]
I dont know under what circumstances one need to set the python home variable. I have not set it on my machine and I have quite similar python setup as other who had the issue. 

It is possible to override the PYTHON_HOME environment variable by calling [Py_SetPythonHome()](https://docs.python.org/3/c-api/init.html#c.Py_SetPythonHome) before initializing the interpreter in (https://github.com/inviwo/inviwo/blob/master/modules/python3/src/pythoninterpreter.cpp#L60). 
But then we would need someway to correctly know which to set on the current machine.

**Comment by r-englund** [comment]
I am not sure, but the original issue may be caused by having Python support for Visual Studio installed. I remember having a similar issue about a year ago on my previous computer that start after I installed python for visual studio.

**Comment by martinfalk** [comment]
@VisComKreiser when Inviwo is bundled, it will include a small python installation with pip and numpy. However, that does not guarantee it will work... :-(
