### ISSUE TITLE
Integration test compile error 

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#76]
Get following compile error when building with Visual Studio 2017 (IVW_INTEGRATION_TESTS enabled):

Error	C2084	function 'inviwo::RuntimeModuleLoading inviwo::getModuleList(void)' already has a body	inviwo-integrationtests	H:\build\inviwo\modules\_generated\moduleregistration.h	6

**Comment by petersteneteg** [comment]
Has this been fixed? Im not able to reproduce, VS 2017 update 6

**Comment by martinfalk** [comment]
fixed in 4a8bc80
