### ISSUE TITLE
No Log output for non-caught exceptions

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#763]
If there is an exception at application level, the error log contains an empty message.

**Messagebox for unhandled exception**
![image](https://user-images.githubusercontent.com/9251300/68029452-890c2500-fcb7-11e9-905f-43d12d1978ca.png)

**Console widget**
![image](https://user-images.githubusercontent.com/9251300/68029485-9cb78b80-fcb7-11e9-973c-68a51480fa39.png)

**Comment by martinfalk** [comment]
The exception **is** actually printed, but as a plain log message (see line above the empty log error)

**Comment by petersteneteg** [comment]
fixed
