### ISSUE TITLE
Context menu for the scrollbars on the networkeditor has broken stylesheet

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#767]
If you right-click on the scrollbars of the network editor you get a quite ugly context menu
![image](https://user-images.githubusercontent.com/534670/68676042-68ff2000-0559-11ea-9891-7993661d492a.png)

**Comment by petersteneteg** [comment]
What! the menubar has a context menu!?!

**Comment by r-englund** [comment]
> 
> 
> What! the menubar has a context menu!?!

Scrollbar!

**Comment by martinfalk** [comment]
Might be just a stylesheet issue with the background color of the scrollbar or maybe even setting that one to transparent...

**Comment by martinfalk** [comment]
Doesn't seem to be an issue anymore.
![image](https://github.com/inviwo/inviwo/assets/9251300/2a5fbdae-bcfd-486a-bad6-dd2aa84f878d)

**Comment by petersteneteg** [comment]
On Mac there is no context menu on the scrollbar at all.. so no issue ;)
