### ISSUE TITLE
Split Image is broken?

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#768]
Step to reproduce: 
1. Load the boron network
2. Add a Split Image processor
3. Connect the entry and exit points to each of the port
4. Add canvas (I added using Add Visualizer), make sure the canvas for SplitImage is smaller than the at least one other canvas) 
5. Drag the slider:
![image](https://user-images.githubusercontent.com/534670/68688440-057fed00-056f-11ea-85bc-28ec134c9a30.png)

**Comment by ResearchDaniel** [comment]
Is the other canvas bigger? Could be due to auto-resize

**Comment by r-englund** [comment]
Yes, the other canvas is bigger, but I also got it in a canvas with the same size in my other network

**Comment by r-englund** [comment]
> 
> 
> Yes, the other canvas is bigger, but I also got it in a canvas with the same size in my other network

The output with the same size was actually one pixel smaller, had it in a image layout with 3 equally spaced inports, but since the canvas width (1547) is not divisable with three the two first images where 1 pixel wider. 

I've updated the issue description to indicate that canvas size is related.

**Comment by martinfalk** [comment]
The Split Image processor _should_ propagate the requested output dimensions. Splitting is done using `GL_SCISSOR`.

**Comment by martinfalk** [comment]
This issue was probably fixed during a refactoring of the `Split Image` processor and I can no longer reproduce it.
![image](https://user-images.githubusercontent.com/9251300/158597167-fbf2518d-34b1-45d4-bcb8-7c2d6d5ac231.png)
