### ISSUE TITLE
OpenEXR: Compile error with VS 2019

### ISSUE THREAD

**Issue by PetiteViking** [inviwo/inviwo#778]
When compiling with VS2019, I (and someone else on Slack) get this error:

```
'binary_function': is not a member of 'std'
```

in `ImfAttribute.cpp` which is part of the OpenEXR submodule and used by default by CIMG. It can be turned off by disabling the `IVW_CIMG_USE_OPENEXR` flag in CMake. `binary_function` has been deprecated in C++11 and been removed in C++17.

Does anyone know whether OpenEXR is going to update or has already updated their code with respect to this? Otherwise, the flag should probably be disabled by default.

**Comment by petersteneteg** [comment]
it's fix in the latest version at least 
https://github.com/AcademySoftwareFoundation/openexr/blob/master/OpenEXR/IlmImf/ImfAttribute.cpp

**Comment by ResearchDaniel** [comment]
6 days ago :)
