### ISSUE TITLE
Height Field Renderer

### ISSUE THREAD

**Issue by MutterOberin** [inviwo/inviwo#785]
The Height Field Renderer does currently not calculate the correct normals. 

![image](https://user-images.githubusercontent.com/11873547/69727397-c206b080-1122-11ea-9993-c3eb09d482f2.png)

There are two options:

1) Rework the Height Field Renderer based on a tessellation + geometry shader approach. This is motivated by the fact that the base mesh for the height field is not needed on CPU side. It is ok if it only exists on the GPU. 

2) Easiest would be to just put the calculation for the normals in.

**Comment by martinfalk** [comment]
Feel free to do that. The normal computation is correct when applying a normal map.

**Comment by martinfalk** [comment]
On a side note: enable the OpenMesh module and then use the processor for creating mesh normals.

**Comment by r-englund** [comment]
> able the OpenMesh module and then use the proces

There is no output mesh

**Comment by martinfalk** [comment]
@r-englund good point. Forgot about that...
