### ISSUE TITLE
after git submodule update --init --recursives

### ISSUE THREAD

**Issue by firebrain7** [inviwo/inviwo#788]
error: Server does not allow request for unadvertised object 3ac6af666cd304b958631013195413b936a9aac4
Fetched in submodule path 'hdf5/ext/hdf5', but it did not contain 3ac6af666cd304b958631013195413b936a9aac4. Direct fetching of that commit failed.

Fetched in submodule path 'hdf5/ext/hdf5', but it did not contain 3ac6af666cd304b958631013195413b936a9aac4. Direct fetching of that commit failed.

how to solve it?

I have tried:
clone directly from the hdf5's url, but it did not contain the ext folder which is required in the cmakeLists.

**Comment by firebrain7** [comment]
just clone the hdf5 from url diretly and put the hdf5 folder inside hdf5/ext/

**Comment by firebrain7** [comment]
solution : just clone the hdf5 from url diretly and put the hdf5 folder inside hdf5/ext/

**Comment by r-englund** [comment]
try run a `git submodule sync` before you run the update

**Comment by firebrain7** [comment]
thanks
actually i have run it before but did not work

**Comment by r-englund** [comment]
Was this issue on a fresh clone of latest master? or did it arise after pulling?

**Comment by r-englund** [comment]
I just tried this on a fresh clone without any issues

**Comment by r-englund** [comment]
I will close this issue for now, we can reopen it if it is still an issue.
