### ISSUE TITLE
compile error: tr1: is not a member of 'std'

### ISSUE THREAD

**Issue by firebrain7** [inviwo/inviwo#790]
![image](https://user-images.githubusercontent.com/16367644/70155744-c7996300-16ed-11ea-8629-8124d4b0a9f8.png)
![image](https://user-images.githubusercontent.com/16367644/70155967-22cb5580-16ee-11ea-9cdc-545961510a50.png)

main mistakes:
tr1: is not a member of 'std'  

error example:
![image](https://user-images.githubusercontent.com/16367644/70155825-eef03000-16ed-11ea-96e8-75c9ada79b98.png)

**Comment by petersteneteg** [comment]
Are you compiling the master branch?

**Comment by ResearchDaniel** [comment]
@firebrain7 This is more related to this code?
https://github.com/ResearchDaniel/Correlated-Photon-Mapping-for-Interactive-Global-Illumination-of-Time-Varying-Volumetric-Data

I just updated that code to work with the latest Inviwo version

**Comment by firebrain7** [comment]
thanks guys
yes,master branch and latest Inviwo version @petersteneteg , and try to build inviwo with your module @ResearchDaniel

**Comment by firebrain7** [comment]
the errors still here, i will try to clone a fresh inviwo and build again.

**Comment by petersteneteg** [comment]
Seems you have the wrong version of google test, did you use our submodule or do something different? What version of VS are you using? Did you select 64bit build?

**Comment by firebrain7** [comment]
Hi@petersteneteg
using vs 2017, 64bit version.
i could not use  command " git submodule sync --recursive , git submodule update --init --recursive --progress --jobs=6" to update the module successfully.
So I open .gitmodule file and follow the link in this file to git clone individually.

**Comment by ResearchDaniel** [comment]
@firebrain7 that is probably the cause of the error. What was the error when syncing sub modules? We fixed the non-availability issue with freetype a few weeks ago so perhaps there is no issue with syncing anymore?

**Comment by firebrain7** [comment]
clone a fresh version and sync again, build ok : )
