### ISSUE TITLE
After activating Property Animator memory consume increases

### ISSUE THREAD

**Issue by DavidNeus** [inviwo/inviwo#8]
Hello,
while using the timer of the property animator I detected an issue probably with the Timer class. 

After clicking the active button of the property animator processor the memory consume slowly increases. You can check this with the windows task manager (see the picture which i attachedn).

After talking to Julian we assume that the reason is somewhere in the Timer::timer() function in the timer.cpp file. I also detected, that if i use more variables in the callback function of the timer, the memory consume increases faster.

Would be great if you have a look on this problem.

Kind regards David

![propertyanimator](https://cloud.githubusercontent.com/assets/6633139/21772374/52b9af72-d68b-11e6-805f-c2a68751fb7b.PNG)

**Comment by r-englund** [comment]
I could reproduce this issue, will investigate

**Comment by r-englund** [comment]
The increased memory consumption is related to the undo/redo stack. Each iteration in the Property Animator the the property is modified and hence we make a push to the undo stack. 
The action we will take is to disable pushing to the undo stack while the animator is active.

**Comment by DavidNeus** [comment]
Thank you for providing a solution. I think we probably discovered an other issue.

The use case is the same as described in the first message, but you have to build in Debug mode. If you activate the property animator the float property increases slowly. But if you for example click and hold the Delta Property (and not change the actual property value), the timer runs maybe twice as fast. Is this also related to the undo/redo stack?
Regards David

**Comment by petersteneteg** [comment]
Yes... while holding the mosue we don't push on the stack... we will update the animator to avoid pushing to the undo stack for each iteration...

**Comment by petersteneteg** [comment]
This should be fixes now withe the latest commits.
