### ISSUE TITLE
OpenEXR: lots of warnings

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#826]
When enabled, i.e. `IVW_CIMG_USE_OPENEXR`, compiling OpenEXR results in >200 warnings.

**Comment by r-englund** [comment]
WWe should probably do someting like: 
https://github.com/inviwo/modules/blob/38a97cfa1dc9c96516c93cdcd0cfe703a1ded389/topovis/topologytoolkit/ext/ttk/CMakeLists.txt#L42
