### ISSUE TITLE
GLSL compile error when using extensions

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#84]
GLSL specification requires that only `#version` directive is before `#extension` directive. However, we include other defines in between, for example #define MAX_PROGRAM_LOOP_COUNT in `void OpenGLCapabilities::rebuildGLSLHeader()`

Tested on Windows with nvidia graphics card. Could not reproduce on Mac

The error is produced when using `ShaderObject::addShaderExtension`
Example:
```
ShaderObject* fragObj = shader->getFragmentShaderObject();
fragObj->addShaderExtension("GL_EXT_shader_image_load_store", true);
```

**Comment by martinfalk** [comment]
This might be tricky. The problem is that `OpenGLCapabilities::rebuildGLSLHeader()` injects both the version flag as well as some defines before the shader object can add the requested extensions, as @ResearchDaniel pointed out.

**Comment by petersteneteg** [comment]
Have a fix

**Comment by petersteneteg** [comment]
Have a fix
