### ISSUE TITLE
Color Scale Legend does not handle discrete transfer functions

### ISSUE THREAD

**Issue by PetiteViking** [inviwo/inviwo#846]
The Color Scale Legend processor does not accurately represent the transfer function when it's discrete.

![image](https://user-images.githubusercontent.com/2997626/73345329-2dd0db00-4284-11ea-8097-6a5070821c91.png)

**Comment by petersteneteg** [comment]
What happens if you change the "background" mode?

**Comment by martinfalk** [comment]
fixed in 6821db8
