### ISSUE TITLE
parseShaderSource fails to parse with some types of block comments

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#847]
For example, the following code will not be correctly parsed. While debugging, after the parser has reached the eof  the state mahcine says it is still in `BlockCom1` state. 
```c++
/*
**/
```

**Comment by r-englund** [comment]
An example where this happens is the `geometrysilhouette.vert` in research-dev/experimental

**Comment by r-englund** [comment]
Added a branch `feature/shader-parsing-block-com-failing` with additional unittest (2c03b14b6eeea05eb2990dd05cbda4a1940eb191)

**Comment by ResearchDaniel** [comment]
@petersteneteg has a fix for this in another branch
