### ISSUE TITLE
NIfTI reader is broken

### ISSUE THREAD

**Issue by josejonasj** [inviwo/inviwo#850]
**Issue**

It looks like the changes in the NIfTI reader from the 0.9.11 release to the current version introduced a bug. Please see the attached images:

_0.9.11 version using the Volume Raycaster processor_
<img width="481" alt="03" src="https://user-images.githubusercontent.com/58182481/73499576-71b00700-438e-11ea-8a31-4d41aeda21d2.png">

_Current version using the Volume Raycaster processor_
<img width="481" alt="04" src="https://user-images.githubusercontent.com/58182481/73499661-b2a81b80-438e-11ea-997e-d2c50fda643f.png">

_0.9.11 version using the ISO Raycaster processor_
<img width="481" alt="05" src="https://user-images.githubusercontent.com/58182481/73499675-bd62b080-438e-11ea-9a04-196f7dc0b993.PNG">

_Current version using the ISO Raycaster processor_
<img width="481" alt="06" src="https://user-images.githubusercontent.com/58182481/73499684-c5baeb80-438e-11ea-8a18-a25939cc8bcf.PNG">

**Steps to reproduce**

Use the *raycaster.inv* and *isoraycaster.inv* regression tests workspaces and change the volume source with the following input NIfTI file:
[spmMotor.nii.gz](https://github.com/inviwo/inviwo/files/4136765/spmMotor.nii.gz)

plus the Transfer Function file (for volume raycaster):
[spmMotor.zip](https://github.com/inviwo/inviwo/files/4136794/spmMotor.zip)

and an ISO value of 0.3719 (for ISO raycaster).

**Environment information**
* Operating System: Windows 10 (1903)
* Compiler/IDE: Visual Studio 2019
* QT Version: 5.13.1
* Python version: 3.8.1

**Log file**

No errors found
[output.zip](https://github.com/inviwo/inviwo/files/4136789/output.zip)

Thanks!

**Comment by petersteneteg** [comment]
Hi, I have been able to reproduce the issue, will investigate further
