### ISSUE TITLE
Move wiki to doxygen

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#86]
This Pull Request is for feedback/discusion rather than for merging. Making a PR instead of Issue to make it easier to look at code and results at the same time. 

The main idea is to move (and improve) the content of the wiki into the doxygen.
See http://jenkins.inviwo.org:8080/job/inviwo-pub/job/feature%252Fdoxy%252Freplace-wiki/Doxygen_Documentation/ for how it could look 

**Pros**
* All documentation in one place
* Easier to keep documentation update in sync with master ( When using wiki, the edits are public directly and when a PR impacts the documentation the master branch and the wiki will be out of sync until the PR is merged, or the opposite) 
* Easier management of documentation for different releases since the documentation can be included with the release which is not really possible with the wiki.   

**Cons**
* Wiki has a closer edit to result cycle (you can edit directly online with preview). Though: see footnote A

**Note: **
The current text in the .md files is not finished so don't  focus on that, more of the idea of using doxygen rather then the wiki. 

**Footnote A**
It will still be possible to edit the documentation online. But there are a few doxygen specfic "tag" in the .md files. See for example https://github.com/inviwo/inviwo/blob/feature/doxy/replace-wiki/docs/manual/manual.md

**From comments in #24**
@martinfalk wrote: 
One thing you forgot to mention is that doxygen parses markdown syntax. Meaning almost no changes need to be made and the `.md` files are reused and still usable.

I think that is a good idea.

**Comment by xeTaiz** [comment]
This should be mostly obsolete by now.
Just checking the wiki for infos that are not in our current documentation. I found
1. [Docs for Doxygen](https://github.com/inviwo/inviwo/wiki/Documentation-guide)
2. Spaces and Transforms figure and explanations.
3. Some debugging tips we might put into a "Troubleshooting" or FAQ page, although I'm unsure if they're still relevant.

I added those things to the new docs in [this PR](https://github.com/inviwo/inviwo.github.io/pull/5), let me know if I'm missing something.

I would then suggest maybe removing the Github wiki as it has quite some outdated infos as well and just put a link to our docs there?
