### ISSUE TITLE
Not all shared libraries are installed, is this on purpose?

### ISSUE THREAD

**Issue by emmenlau** [inviwo/inviwo#870]
**Issue**

Thanks for the awesome work! This is more like a feature request than an issue.

I use something like `mkdir build && cd build && cmake .. && ninja && ninja install` (very simplified) to create a binary release installation of inviwo. Generally this works well, but I've seen that a number of libraries remain only in the `build/lib` folder. It seems most shared libraries are not copied to the installation directory.

Is that on purpose? If yes, would it be possible to have this configurable? Its really easy to copy them manually, but I think many users expect that `make install` creates a self-dependent `TARGETDIR` with all binaries installed.

**Steps to reproduce**
```
mkdir build && cd build && cmake .. && ninja && ninja install
```
Then check the `build/lib` directory.

**Environment information**
* Operating System: Ubuntu 18.04
* Compiler/IDE: gcc-7.2
* QT Version: Qt 5.14.1
* Python version: 3.6

**Comment by petersteneteg** [comment]
Hi, generally all libs should be installed, I do periodically run the package target that uses the install target to create various installers. That usually works without any manual copying. I have not tested running just the install target, but the behavior "should" be the same. What libs is it that you are missing?

**Comment by emmenlau** [comment]
Dear @petersteneteg thanks for the quick reply! I've run a diff between `build/lib` and `TARGETDIR/lib` and these are the libraries that are *not* installed:
```
 libassimp.so
 libassimp.so.4
 libassimp.so.4.1.0
 libfmt.so
 libfmt.so.5
 libfmt.so.5.3.1
 libfreetype.so
 libfreetype.so.6
 libfreetype.so.6.16.0
 libGLEW.so
 libGLEW.so.2.0
 libGLEW.so.2.0.0
 libglfw.so
 libglfw.so.3
 libglfw.so.3.3
 libglm_shared.so
 libinviwo-core.so
 libinviwo-module-animationqt.so
 libinviwo-module-animation.so
 libinviwo-module-assimp.so
 libinviwo-module-basegl.so
 libinviwo-module-base.so
 libinviwo-module-brushingandlinking.so
 libinviwo-module-cimg.so
 libinviwo-module-dataframepython.so
 libinviwo-module-dataframeqt.so
 libinviwo-module-dataframe.so
 libinviwo-module-eigenutils.so
 libinviwo-module-fontrendering.so
 libinviwo-module-glfw.so
 libinviwo-module-json.so
 libinviwo-module-nifti.so
 libinviwo-module-openglqt.so
 libinviwo-module-opengl.so
 libinviwo-module-plottinggl.so
 libinviwo-module-plotting.so
 libinviwo-module-png.so
 libinviwo-module-postprocessing.so
 libinviwo-module-pvm.so
 libinviwo-module-python3qt.so
 libinviwo-module-python3.so
 libinviwo-module-qtwidgets.so
 libinviwo-module-userinterfacegl.so
 libinviwo-module-vectorfieldvisualizationgl.so
 libinviwo-module-vectorfieldvisualization.so
 libinviwo-qtapplicationbase.so
 libinviwo-qteditor.so
 libsigar.so
 libsigar.so.1.6
 libsigar.so.1.6.4
 libticpp.so
 libticpp.so.0.4
 libtidds.so
```

I did not really check if there are libraries that *did* get installed. What I can say is that a number of install targets work, `bin/Inviwo` is there and a number of images and other files...

**Comment by emmenlau** [comment]
Wait, I found quite a number of them in the `TARGETDIR/bin ` directory. Now there are still two missing, `libfmt` and `libglm`:
```
libfmt.so
libfmt.so.5
libfmt.so.5.3.1
libglm_shared.so
```

**Comment by petersteneteg** [comment]
I.c. the reason they are in the bin folder is probably since on windows that is the case. And we do most of the testing on windows. This section here https://github.com/inviwo/inviwo/blob/5a3bd2f770c550b84a7a1ee9ba0a20c5cbfc6354/cmake/installutils.cmake#L50-L56 is probably responsible for most of that.
Should have a case there for linux to.

If you enable IVW_PACKAGE_PROJECT then fmt should also be install if I think... seems it is not enabled by default since we don't require cmake 3.13 yet... 
https://github.com/inviwo/inviwo/blob/master/ext/fmt/CMakeLists.txt

don't think we link against glm_shared so I dont't think is should be needed. 
Not quite sure why it is built either.

**Comment by emmenlau** [comment]
Thanks a lot @petersteneteg ! Everything makes perfect sense now.

I was anyways considering to take a look at the dependencies, since we have fmt, hdf5 and a number of others pre-built. Would it be ok if I submit a PR (at some point) that first tries to find system-libs for the dependencies and only uses the external repositories as a fallback?

**Comment by petersteneteg** [comment]
You're welcome
We have option to do that for some of the image libs see IVW_USE_EXTERNAL_IMG
for c-libs using the system one usually works fine, but for c++ libs we generally prefer to be able to control the version of our dependences our selfs. Hence I prefer to also build them.

In the case that you want to use a system libs, adding an option similar to the one above would be the way to go. I prefer hard errors if the libs we want is not found the way we like, and not silent fallbacks.  
Does that make sense to you?

**Comment by emmenlau** [comment]
Haha yes, its actually very much the same for us :-) However we share quite a bit of your tech-stack, so it would be quite convenient if we could avoid duplicate binaries (i.e. in case we have patches like for hdf5, the duplicate copies become a maintenance burden).

So I'll try to follow your approach and propose a PR at some point.

**Comment by petersteneteg** [comment]
I'll close this for now...
