### ISSUE TITLE
Use set "Release with debug info" as default mode in Visual studio 

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#882]
Problem:
New users may think that the application is slow since default compile mode in visual studio is debug.

Solution:
Make Release or Release with debug info the default mode. 
https://blog.kitware.com/cmake-and-the-default-build-type/

Any opinions?

**Comment by r-englund** [comment]
+1 for `RelWithDebInfo`, I always hate myself when I have a new build and forget to change that

**Comment by r-englund** [comment]
I think we should make `RelWithDebInfo` and not `Release`, since ppl may report stacktraces in case of crashes and then we have much more info in `RelWithDebInfo`

**Comment by petersteneteg** [comment]
Would be nice, just note that the solution above is not for multi config builds like visual studio. Might be different ways to do it though

**Comment by ResearchDaniel** [comment]
Briefly tried it and could only get it to default to MinSizeRelease for some reason. Will experiment more tomorrow

**Comment by petersteneteg** [comment]
I’m quite skeptical about the existence of such a setting... note CMAKE_BUILD_TYPE does not set this...

**Comment by ResearchDaniel** [comment]
Yes, so I discovered. I could not get it to work with multi-config :(

**Comment by ResearchDaniel** [comment]
An alternative is to add it to the build instructions.

**Comment by r-englund** [comment]
> An alternative is to add it to the build instructions.

I had it in the build instructions when I used inviwo in labs

**Comment by ResearchDaniel** [comment]
I still think that we should add it to the instructions. @xeTaiz Could you do that?
