### ISSUE TITLE
Canvas and Dialogs get destroyed on close, Qt 5.14

### ISSUE THREAD

**Issue by emmwel** [inviwo/inviwo#887]
When closing a canvas using the "x" button the canvas ends up in an invalid state. Upon reopening it it stays blank. Creating a new network, deleting the canvas processor, or closing Inviwo results in a segmentation fault. The unique pointer of the canvas gets destructed on close and calls removes the widget from the layout.
This also applies to the ColorDialog, which now stays partially intact (in contrast to earlier Qt versions where the contents disappeared entirely, see #251)

Tested with Qt 5.14.1

**Comment by petersteneteg** [comment]
Thanks for reporting, will investigate. Does it work if you open/close it by double clicking the canvas processor in the network?

**Comment by martinfalk** [comment]
Yes, when using the show/hide in the processor network, the canvas stays intact.

**Comment by petersteneteg** [comment]
@emmwel should be fixed now, otherwise just reopen this
