### ISSUE TITLE
std::transform_reduce not yet in gcc/clang

### ISSUE THREAD

**Issue by emmenlau** [inviwo/inviwo#888]
`inviwo/src/core/util/timer.cpp` is using `std::transform_reduce`, however current gcc/clang versions do not yet ship this. At least on Ubuntu 18.04 with gcc-7.4 and `-std=c++1z` I get:
```
inviwo/src/core/util/timer.cpp:58:17: error: 'transform_reduce' is not a member of 'std'
```
This impression is supported by https://stackoverflow.com/a/47502855/7200132 where it says
> The "Parallelism TS" is still marked as "No", so it's not been implemented yet. It's also not implemented in Clang.

Would it be possible to find an alternative implementation?

**Comment by petersteneteg** [comment]
Ahh that was my mistake... should be easy to fix

**Comment by petersteneteg** [comment]
Just a note we do require c++17 generally so you should compile with -std=c++17. However we have been a bit careful about not using some of the standard library that have not been implemented in so many compilers yet. But we will probably start to require a more complete 17 standard library soon. So I would recommend you try to use something newer then gcc 7. And if you use Ubuntu which btw is notoriously slow to update to new compiler versions, try to at least use the latest Ubuntu...

**Comment by emmenlau** [comment]
> Just a note we do require c++17 generally so you should compile with -std=c++17.

I agree. I was surprised by this setting that's why I brought it up in the issue. It took me some 10 minutes to figure out whats going on. But I'm currently under the impression that this is cmake's setting, and not my change. I traced it back to `cmake/globalconfig.cmake`:
```cmake
if(compiler_supports_cxx17)
    message(STATUS "C++17 enabled")
    set(CMAKE_CXX_STANDARD 17 CACHE STRING "C++ ISO Standard" FORCE)
else()
    message(FATAL_ERROR "The compiler ${CMAKE_CXX_COMPILER} has no C++17 support. "
            "Please use a different C++ compiler.")
endif()
```
If this is indeed problematic then I would need to figure out how to tweak cmake there...

> So I would recommend you try to use something newer then gcc 7. And if you use Ubuntu which btw is notoriously slow to update to new compiler versions, try to at least use the latest Ubuntu...

Personally I very much agree! But we still support Ubuntu 18.04 for our users and will need to do so for quite a while :-/

**Comment by petersteneteg** [comment]
Hi, I guess you follow the ubuntu LTS releases? that would mean 2023?. I can understand why one would want to support that. But it also introduces a large const on our side since we have to forbid a large part of the toolbox or reimplement it our self. For example if we could use std::filesystem instead of rolling our own hacks we would save a lot... we still don't require that though, but you can see how tempting that would be. Anyway at the moment I think gcc 7.4 support more or less all of c++17 except filesystem and the new stuff in numeric with transform_reduce, i.e. parallel stl.
