### ISSUE TITLE
Orthographic camera panning is not working

### ISSUE THREAD

**Issue by josejonasj** [inviwo/inviwo#895]
**Issue**

When the user tries to pan an orthographic camera what it was visible it just disappears from the canvas.

**Steps to reproduce**

- Open the provided CameraTest workspace: [CameraTest.zip](https://github.com/inviwo/inviwo/files/4325785/CameraTest.zip)
- Press the mouse middle button on the canvas and drag it.

**Environment information**
* Operating System: Windows 10 (1903)
* Compiler/IDE: Visual Studio 2019
* QT Version: 5.13.1
* Python version: 3.8.1

**Log**

No errors found.

**Possible fix**

After some digging it turned out that the problem is in the `Camera::getClipPosFromNormalizedDeviceCoords(const vec3& ndcCoords)` method so here's my two cents if the following change is valid for perspective and orthographic cameras (or maybe split the implementation between the two):

```C#
vec4 Camera::getClipPosFromNormalizedDeviceCoords(const vec3& ndcCoords) const {
    // Original code
    //const auto& projection = getProjectionMatrix();
    //const float clipW = projection[2][3] / (ndcCoords.z - (projection[2][2] / projection[3][2]));

    // Possible fix
    vec4 invClip = getInverseProjectionMatrix() * getInverseViewMatrix() * vec4(ndcCoords, 1.0);
    float clipW = 1.0f / invClip.w;

    return vec4(ndcCoords * clipW, clipW);
}
```

Source: https://feepingcreature.github.io/math.html

Thanks!

**Comment by martinfalk** [comment]
Thanks for reporting this. Consider updating to latest master. The issue has been fixed a couple weeks ago in 12ce29e8ead661abef94b8b585a460f22c35c099.
