### ISSUE TITLE
Tube rendering artifacts

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#897]
Tube rendering is slightly broken, some tubes are rendered twice.
Input is a mesh with individual lines (`Mesh::MeshInfo(DrawType::Lines, ConnectivityType::None)`). There are no duplicate index pairs. Nonetheless there appear some z-fighting artifacts. In particular noticable with different colors per vertex.

![image](https://user-images.githubusercontent.com/9251300/76738425-e4bce380-676a-11ea-89ae-af608c81fd01.png)

**Comment by martinfalk** [comment]
Depth is set to the same value for both front and back sides.

https://github.com/inviwo/inviwo/blob/bf3ac9ff1e42fb2ac948e7c40009e835c969d060/modules/basegl/glsl/tuberendering.frag#L130

**Comment by ResearchDaniel** [comment]
This whole thing must separate between front/back faces, not only the depth?

**Comment by martinfalk** [comment]
yes. That also indicates that enabling backface culling should at least provide some quick fix.
