### ISSUE TITLE
Orthographic camera zoom issue?

### ISSUE THREAD

**Issue by josejonasj** [inviwo/inviwo#898]
I'm not sure if that's the expected behavior because with the orthographic camera the objects should appear at the same size no matter the distance, but as in the perspective camera the mouse right button (or the two fingers pinch) affects the zoom then in the orthographic camera should occur the equivalent thing (like changing the width value), isn't it?

**Issue**

When the user tries to zoom in or zoom out the volume size doesn't change and at some point shows a clipping issue.

![Image](https://user-images.githubusercontent.com/58182481/76803676-60895100-67a8-11ea-9e01-7e9ced395297.png)

**Steps to reproduce**

- Open the **raycaster.inv** regression test located in `modules/basegl/tests/regression/raycaster` path.
- Press the mouse right button and drag it back and forth or place two fingers on the touchscreen and pinch in or stretch out.

**Environment information**
* Operating System: Windows 10 (1903)
* Compiler/IDE: Visual Studio 2019
* QT Version: 5.13.1
* Python version: 3.8.1

**Log**

No errors found.

I would appreciate a clarification if I'm wrong. Thanks!

**Comment by petersteneteg** [comment]
No, you are correct, this has never been handled. The perspective camera move the look from closer when zooming, i.e. a kind if dollying, and the orthographic camera does the same, but then of course nothing happens. One needs to change the "width" of the camera to zoom in this case...
And as of now we have no mouse interaction for doing that. 
I would be nice to fix this, unfortunately the trackball that takes care of the mouse interaction does not know of any other camera types then perspective at this point. So there needs to be some kind of refactoring to handle that interaction properly.

**Comment by josejonasj** [comment]
OK, thanks @petersteneteg !

**Comment by martinfalk** [comment]
Closing this for now. Orthographic camera does not support zooming at the moment..

**Comment by petersteneteg** [comment]
#944 should fix this

**Comment by josejonasj** [comment]
The mouse zoom in/out works fine but the two-finger zoom in/out (expand/pinch) doesn't work.

**Comment by petersteneteg** [comment]
Ahh. I don't use inviwo on any touch device, so I have not tested that.
