### ISSUE TITLE
Static build broken on Jenkins

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#9]
http://130.236.145.152:8080/job/Daily/job/Inviwo-GCC-Static/ 
Seems to be related to python

**Comment by r-englund** [comment]
Now it fails due to installation issue with GLFW 
```
CMake Error at modules/glfw/ext/glfw/glfw/src/CMakeLists.txt:118 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "glfw"
```
http://jenkins.inviwo.org:8080/job/Daily/job/Inviwo-GCC-Static/806/console

**Comment by r-englund** [comment]
https://stackoverflow.com/questions/14990343/cmake-error-targets-given-no-library-destination-for-shared-library-target

**Comment by petersteneteg** [comment]
Work on GHA now
