### ISSUE TITLE
Shader in/out declarations are too limited

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#903]
The current way of adding in and out declarations to shaders is maybe a bit too restricted.

https://github.com/inviwo/inviwo/blob/6ca6fdd28837229ec1fdfa38d7ab35f3f07dd75b/modules/opengl/include/modules/opengl/shader/shaderobject.h#L80-L95

To be more specific, location is fixed to an `int`. However, some extensions require strings. For example `GL_EXT_conservative_depth`:
```glsl
layout (depth_greater) out float gl_FragDepth;
```

**Comment by petersteneteg** [comment]
Just set a custom decl string and https://github.com/inviwo/inviwo/blob/6ca6fdd28837229ec1fdfa38d7ab35f3f07dd75b/modules/opengl/include/modules/opengl/shader/shaderobject.h#L178
