### ISSUE TITLE
Position indicator lines don't rotate when rotating a volume slice

### ISSUE THREAD

**Issue by josejonasj** [inviwo/inviwo#907]
**Issue**

When the user rotates a volume slice the vertical and horizontal lines of the position indicator don't rotate with the volume slice so it mismatches the orientation of the other slices.

<img width="256" alt="Inviwo" src="https://user-images.githubusercontent.com/58182481/77670439-32e49a80-6f54-11ea-99cb-09bbd4927e6e.png">

**Steps to reproduce**

* Use the **diagnosticlayout_head** example (located in Inviwo/0.9.11/data/workspaces).
* Select the **X Volume Slice** processor.
* Select **Free Rotation** in the **Transformations** section.
* Specify an **angle** of **0.7** units.

**Environment information**

* Operating System: Windows 10 (1903)
* Compiler/IDE: Visual Studio 2019 v16.5.1
* QT Version: 5.13.1
* Python version: 3.8.1

**Log**

No errors found

Thanks!

**Comment by martinfalk** [comment]
The reason for that lies in the fact that the position indicator is intended to highlight a pixel position in the canvas and not the orientation.

**Comment by petersteneteg** [comment]
As @martinfalk said, that was never really intended, the 2D marker was only intended to show one 2D position, not any rotation. But PR would be welcome!
