### ISSUE TITLE
Can't merge PR from forks

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#912]
The branch build check is never started and hence it will never be able to turn green. 
This currently effects #902 and #911 
![bild](https://user-images.githubusercontent.com/534670/78122083-88b1ba80-740c-11ea-8eb1-fdd359c1ce0e.png)

**Comment by petersteneteg** [comment]
any idea why the hooks does not work?

**Comment by r-englund** [comment]
Well, I guess jenkins is not setup to build branches on forks

**Comment by petersteneteg** [comment]
From what I can understand it should build from forks too...

**Comment by petersteneteg** [comment]
ahh it's only setup to build the PR from a fork, not the branch... which makes sense since jenkins does not track the branches of all the forks...

**Comment by petersteneteg** [comment]
removed the requirement of having the branch pass...
