### ISSUE TITLE
File dialogue crashes on Pop! OS

### ISSUE THREAD

**Issue by AnkeAnke** [inviwo/inviwo#914]
**Issue**
Issue on Pop! OS, a ubuntu-based linux system. Can currently not test if it appears in vanilla ubuntu as well.
When opening a file dialogue and clicking on some folders, the application crashes at some point. 

**Steps to reproduce**
Open inviwo on Pop! OS. Open up a file dialogue (in image loader etc). The file dialogue looks good, it's the systems one. Clicking on folders will kill the application after some random number of clicks.

Does not seem correlated to the name or symbol of the folder. Selecting/scrolling files within a folder is not affected.
Sampling the behaviour by switching between the empty music folder and non-empty picture folder resulted in crashes after 17, 2, 4, 23 clicks.

**Environment information**
* Operating System: Pop! OS 19.10, (based on Ubuntu 10.10, Gnome 3.34.2)
* Compiler/IDE: VS Code, GCC 8.3.0
* QT Version: 5.14.1
* Python version: 3.7.5

GDB error:
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Pop/16x16/status/image-missing.png: Couldn’t allocate memory for loading PNG (gdk-pixbuf-error-quark, 1)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Pop/16x16/status/image-missing.png: Couldn’t allocate memory for loading PNG (gdk-pixbuf-error-quark, 1)

**Comment by petersteneteg** [comment]
can you try building with https://github.com/inviwo/inviwo/blob/8f9258ca833a1df72eb8af47e9857d4213b5e767/CMakeLists.txt#L125

**Comment by AnkeAnke** [comment]
That fixed it, thank you :100:

Using apt packages zlib1g-dev, libtiff-dev, libjpeg-dev.
Needed to delete the bin to trigger a clean CMake configuration.

**Comment by petersteneteg** [comment]
@xeTaiz should we add that to the linux build docs?
