### ISSUE TITLE
Failed to build meshrenderinggl module

### ISSUE THREAD

**Issue by josejonasj** [inviwo/inviwo#936]
**Issue**

When I try to build the meshrenderinggl module in the current master branch (8be0c52) I get the following error:

`C:\inviwo\modules\meshrenderinggl\src\processors\linerasterizer.cpp(41,51): error C2491: 'inviwo::LineRasterizer::processorInfo_': definition of dllimport static data member not allowed`

**Steps to reproduce**

Just try to build the meshrenderinggl module from scratch.

**Environment information**
* Operating System: Windows 10 (1903)
* Compiler/IDE: Visual Studio 2019 v16.5.4
* QT Version: 5.13.1
* Python version: 3.8.1

Thanks!

**Comment by AnkeAnke** [comment]
I exported the processor for the wrong dll. It is fixed in #934, so will hopefully soon land in master.

**Comment by petersteneteg** [comment]
should work now I hope, otherwise just reopen this

**Comment by josejonasj** [comment]
Yes, it works now. Thanks!
