### ISSUE TITLE
Raycaster with mesh issue when using an orthographic camera

### ISSUE THREAD

**Issue by josejonasj** [inviwo/inviwo#938]
**Issue**

When rotating the volume it seems like the mesh or the volume moves depending on the point of view. This only happens when using an orthographic camera.

*Here you can see that the top of the sphere is not covered by the volume*
<img width="498" alt="04" src="https://user-images.githubusercontent.com/58182481/81993980-78e0e500-960c-11ea-8d2a-44f1e01a9f04.PNG">

*But after changing the point of view the top of the sphere is partially covered by the volume*
<img width="499" alt="05" src="https://user-images.githubusercontent.com/58182481/81993994-81392000-960c-11ea-99ab-cb12b51b3bc6.PNG">

In some other cases that displacement is bigger.

Do you have an idea of what might be causing this issue?

*Tested with the latest commit 8be0c52.*

**Steps to reproduce**

- Use the attached file that contains a modified version of **raycasterwithmeshes.inv** BaseGL regression test ( [RaycasterWithMesh.zip](https://github.com/inviwo/inviwo/files/4631390/RaycasterWithMesh.zip) )
- Update the paths of the volume source
- Rotate the volume to see the visual effect as if the sphere or volume is moving
- Using a perspective camera doesn't show that issue

**Environment information**
* Operating System: Windows 10 (1903)
* Compiler/IDE: Visual Studio 2019 v16.5.5
* QT Version: 5.13.1
* Python version: 3.8.1

**Log**

No errors found

Thanks!

**Comment by petersteneteg** [comment]
I was able to reproduce the issue. Quite strange. So far I don't know why. Might be that we use the wrong matrix somewhere, but Im just guessing...

**Comment by petersteneteg** [comment]
@josejonasj I did some more testing, seems there might be an issue with the aspect ratios in your workspace
Can you check if the max value of the aspect ratio is set to 1 in some of the cameras? 
Think changing that might fix it...

**Comment by josejonasj** [comment]
Thanks @petersteneteg you're right, when I changed the aspect ratio of the cameras to a value below 1.0 (by increasing the window height) the volume reached the right size from any point of view (so the visual effect disappears) like this:

<img width="455" alt="06" src="https://user-images.githubusercontent.com/58182481/82071915-5f877980-969c-11ea-9cac-d3a9c0d9d319.PNG">

Then this showed a new issue that I didn't notice before because when I decreased the window height the volume shrank like this:

<img width="454" alt="07" src="https://user-images.githubusercontent.com/58182481/82072367-3ddac200-969d-11ea-85a2-71e8bd3a77dd.PNG">

which I don't think it should happen.

**Comment by petersteneteg** [comment]
I you go to the camera in the volumeraycaster and right click it there should be a context menu with a item called "Property Settings" click that and then you can modify the max value of the aspect ratio. For some reason the max in the workspace you added is set to 1 meaning that even if the canvas has a wider aspect the camera will cap it at one and then you get the image above...

**Comment by petersteneteg** [comment]
the default max should be much bigger so I don't know how it has become 1...

**Comment by josejonasj** [comment]
I did it but the volume keeps shrinking anyway

![image](https://user-images.githubusercontent.com/58182481/82078194-5d2a1d00-96a6-11ea-9c3b-82b27a1baca7.png)

**Comment by petersteneteg** [comment]
seems you also have to change the one in the entryexit points also... It is read only for me, so you can't change the property setting, but you can click "Reset to default" instead that also reset the max. When doing that the workspace above works fine for me

**Comment by josejonasj** [comment]
You're right. That was causing the change in the volume size. **Lesson learned:** keep track of aspect ratio values between all the involved processors.

Thanks a lot, @petersteneteg for all the support! I'm closing this issue then.
