### ISSUE TITLE
New python processor empty using the installer from the homepage

### ISSUE THREAD

**Issue by VisComKreiser** [inviwo/inviwo#945]
Hey,
in the downloadable installer version v0.9.11 for Windows, the template python processor is empty when you try to create it through the menu bar.
Cheers, Julian

**Comment by martinfalk** [comment]
quite likely that `pymodule->getPath() + "/templates/templateprocessor.py"` is not packaged.

**Comment by martinfalk** [comment]
Should be fixed in the next release.
