### ISSUE TITLE
Unhandled exception (ucrtbase.dll)

### ISSUE THREAD

**Issue by Git-me-outta-here** [inviwo/inviwo#993]
**Issue**

Running my own build throws this exception:
Fatal Python error: unable to load the file system codec
Unhandled exception at 0x00007FFE786A284E (ucrtbase.dll) in Inviwo.exe: Fatal program exit requested.

Seems to be in ....\inviwo\ext\pybind11\include\pybind11\embed.h@109

**Steps to reproduce**

I followed the guide: https://inviwo.org/manual-gettingstarted-build.html#building
Build RelWithDebInfo succeeds.
Running the application immediately stops with the error.

**Environment information**
* Operating System: win10
* Compiler/IDE: VS 2019
* QT Version: 5.15
* Python version: 3.7 (Anaconda3)

**Comment by r-englund** [comment]
Have you tried the suggestion at https://inviwo.org/manual-gettingstarted-build.html#everything-compiles-but-at-runtime-you-get-runtime-error--unhandled-exception-in-pybind11embedh

**Comment by Git-me-outta-here** [comment]
thank you!!
I did not realise this fix applied to me. Can we maybe mention the specific exception in this CommonErrors section?

**Comment by Git-me-outta-here** [comment]
Please add this error (Unhandled exception at 0x00007FFE786A284E (ucrtbase.dll) in Inviwo.exe: Fatal program exit requested.)
to the documentation. I've just had a colleague run into the same error, and the solution is not easily found.

In the build instructions, please mention that we have to set PYTHONHOME. Or mention it in the "Building Inviwopy" section.
