### ISSUE TITLE
OpenGLException Unsupported Wrapping mode encountered

### ISSUE THREAD

**Issue by Git-me-outta-here** [inviwo/inviwo#994]
**Issue**

Exception thrown at 0x00007FFE78383E49 in Inviwo.exe: Microsoft C++ exception: FileFormatException at memory location 0x000000D6B2CF5910.
Exception thrown at 0x00007FFE78383E49 in Inviwo.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFE78383E49 in Inviwo.exe: Microsoft C++ exception: FileFormatException at memory location 0x000000D6B2CF5910.
Exception thrown at 0x00007FFE78383E49 in Inviwo.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFE78383E49 in Inviwo.exe: Microsoft C++ exception: FileFormatException at memory location 0x000000D6B2CF5910.
Exception thrown at 0x00007FFE78383E49 in Inviwo.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFE78383E49 in Inviwo.exe: Microsoft C++ exception: inviwo::OpenGLException at memory location 0x000000D6B39FE860.
Unhandled exception at 0x00007FFE786A284E (ucrtbase.dll) in Inviwo.exe: Fatal program exit requested.

seems to happen at ...\inviwo\modules\opengl\src\openglutils.cpp@85

**Steps to reproduce**

Open boron2.inv file with my own build. (Works fine with the installed version of inviwo. Also, other files open with my build, no problem.)
[boron2.zip](https://github.com/inviwo/inviwo/files/4902443/boron2.zip)

**Environment information**
* Operating System: win10
* Compiler/IDE: VS 2019
* QT Version: 5.15
* Python version: 3.7 (Anaconda3)

**Comment by Git-me-outta-here** [comment]
I have not changed any code. I followed the guide: https://inviwo.org/manual-gettingstarted-build.html#building
Build RelWithDebInfo succeeds.
Running the application works.

When I load any other inv file it works fine, crashes only with this boron2.inv...

I think this is the minimal example for this crash.

**Comment by r-englund** [comment]
After some investigation, I found the issues is in the `Volume Laplacian` processor. It is similar to an issue we had with the `Surface Extraction` processor a while back (#348). 

`Volume Laplacian` does its computation on the CPU while the input volume exists only on the GPU. The algorithm runs on a thread without an active GL context and will crash when it's trying to download the volume to RAM. 

This is a conceptual issue we have to deal with within Inviwo, a possible workaround for you is to add `RenderContext::getPtr()->activateLocalRenderContext();` to the calc-lambda in `VolumeLaplacianProcessor::process`

```c++
void VolumeLaplacianProcessor::process() {
    auto invol = inport_.getData();
    inVolume_.updateForNewVolume(*invol.get());
    
    const auto calc = [volume = invol, postProcessing = postProcessing_.get(),
                       scale = scale_.get()]() -> std::shared_ptr<Volume> {
        RenderContext::getPtr()->activateLocalRenderContext(); // This line is added
        return util::volumeLaplacian(volume, postProcessing, scale);
    };

    outport_.clear();
    dispatchOne(calc, [this](std::shared_ptr<Volume> result) {
        outVolume_.updateForNewVolume(*result);
        outport_.setData(result);
        newResults();
    });
}
```

**Comment by Git-me-outta-here** [comment]
Good workaround. Thank you!

**Comment by petersteneteg** [comment]
@r-englund is it fixed in master?

**Comment by petersteneteg** [comment]
Fixed with the updates to the pool processor
